import { useEffect, useState } from "react";
import { Users, ShieldCheck, KeyRound, Search, Plus, Pencil, ChevronRight, Check, X, Store, LogOut, RefreshCw, LockKeyhole, History, ArrowUpRight, AlertCircle, UserRound, WifiOff } from "lucide-react";
import { useLanguage, AppDialog as Modal, SelectField, CheckField } from "@onebite/ui";
import { roles, moduleDefinitions, hasPermission, permissionDefinitions, ceilings, initialAccessState, can, saveAccount, assignSites, saveGrants, visibleAccounts, AccessError, type Account, type Role, type Permission, type AccessState } from "@onebite/core/access";
import { accessApi, configured, readSession, setSession, ApiError, type Snapshot } from "./access-api";
import logo from "../../../resources/brand/one-bite-logo-orange.svg";
type Tab = "users" | "roles" | "permissions" | "activity";
type Mode = "connecting" | "unavailable" | "login" | "setup" | "change-pin" | "live" | "preview";
const previewKey="onebite-admin-access-preview-v1";
const fresh=(): Snapshot=>({...initialAccessState(),revision:0});
function previewState(): Snapshot {try{const raw=localStorage.getItem(previewKey);if(raw){const parsed=JSON.parse(raw);if(parsed.version===1&&Array.isArray(parsed.users)&&Array.isArray(parsed.sites)&&parsed.grants&&roles.every(r=>Array.isArray(parsed.grants[r]))&&parsed.users.every((u:Account)=>roles.includes(u.role)&&Array.isArray(u.sites))&&Array.isArray(parsed.events))return parsed.permissionSchema===2?parsed:{...parsed,permissionSchema:2,grants:Object.fromEntries(roles.map(r=>[r,[...parsed.grants[r],...moduleDefinitions.filter(m=>ceilings[r].includes(m.id)).map(m=>m.id)]]))};}}catch{}return fresh();}
export function AccessApp(){
 const {t,lang,setLang}=useLanguage();
 const [mode,setMode]=useState<Mode>("connecting"),[state,setState]=useState<Snapshot>(fresh),[actorId,setActorId]=useState("owner"),[session,setToken]=useState(readSession),[tab,setTab]=useState<Tab>("users");
 const [error,setError]=useState(""),[busy,setBusy]=useState(false),[toast,setToast]=useState(""),[search,setSearch]=useState(""),[roleFilter,setRoleFilter]=useState("all"),[statusFilter,setStatusFilter]=useState("all");
 const [editing,setEditing]=useState<Account|null>(null),[creating,setCreating]=useState(false),[editRole,setEditRole]=useState<Role|null>(null),[resetUser,setResetUser]=useState<Account|null>(null);
 const actor=state.users.find(u=>u.id===actorId&&u.active);
 const roleName=(role:Role)=>role==="Owner"?t("ម្ចាស់","Owner"):role==="Supervisor"?t("អ្នកត្រួតពិនិត្យ","Supervisor"):t("អ្នកគិតលុយ","Cashier");
 const errorText=(code:string)=>({forbidden:t("អ្នកមិនមានសិទ្ធិធ្វើសកម្មភាពនេះ","You do not have permission for this action."),invalid_name:t("សូមបញ្ចូលឈ្មោះពី 1 ដល់ 100 តួអក្សរ","Name must contain 1–100 characters."),invalid_username:t("ឈ្មោះអ្នកប្រើត្រូវមាន 3–32 តួអក្សរ ជាអក្សរឡាតាំងតូច លេខ ឬ _ . -","Username must be 3–32 lowercase letters, digits, _, . or -."),duplicate_username:t("ឈ្មោះអ្នកប្រើនេះមានរួចហើយ","This username is already used."),invalid_site:t("សាខាដែលបានជ្រើសមិនត្រឹមត្រូវ","Invalid site assignment."),site_required:t("គណនីដំណើរការត្រូវមានសាខាមួយយ៉ាងតិច","An active staff account needs at least one active site."),last_owner:t("ត្រូវរក្សាម្ចាស់ដែលដំណើរការមួយយ៉ាងតិច","At least one active Owner must remain."),immutable_grant:t("សិទ្ធិរបស់ម្ចាស់ត្រូវបានការពារសម្រាប់គ្រប់គ្រងគណនី","Owner permissions are protected to preserve account administration."),permission_ceiling:t("មិនអាចផ្ដល់សិទ្ធិលើសកម្រិតតួនាទី","Permissions cannot exceed this role’s hard limits."),invalid_credentials:t("ឈ្មោះអ្នកប្រើ ឬ PIN មិនត្រឹមត្រូវ","Incorrect username or PIN."),login_throttled:t("សូមរង់ចាំ រួចព្យាយាមម្តងទៀត។ បើចូលខុសច្រើន ត្រូវរង់ចាំ 15 នាទី។","Please wait before retrying. Repeated failures lock the account for 15 minutes."),invalid_setup:t("កូដបង្កើតម្ចាស់មិនត្រឹមត្រូវ ឬត្រូវបានប្រើរួច","Owner setup code is invalid or already used."),invalid_pin:t("ប្រើលេខ PIN ថ្មី 6 ខ្ទង់","Use a new six-digit PIN."),invalid_account:t("សូមពិនិត្យឈ្មោះ ឈ្មោះអ្នកប្រើ តួនាទី និង PIN","Check the name, username, role, and PIN."),stale_revision:t("ទិន្នន័យបានផ្លាស់ប្ដូរ។ ធ្វើបច្ចុប្បន្នភាព រួចពិនិត្យមុនរក្សាទុក។","Data changed since this editor opened. Refresh and review before saving."),unauthorized:t("សម័យចូលប្រើបានផុតកំណត់។ សូមចូលម្តងទៀត។","Your session expired or was revoked. Sign in again."),network_failed:t("មិនអាចភ្ជាប់ទៅ Supabase។ ពិនិត្យអ៊ីនធឺណិត និងសិទ្ធិបណ្ដាញ។","Cannot reach Supabase. Check your internet connection and network access."),request_timeout:t("សំណើបានហួសពេល។ សូមព្យាយាមម្តងទៀត។","The request timed out. Please retry."),not_connected:t("មិនទាន់បានភ្ជាប់សេវាគណនី","The account service is not connected yet.")}[code]||t("មិនអាចបញ្ចប់សំណើ។ សូមព្យាយាមម្តងទៀត។","Could not complete the request. Please try again."));
 function report(e:unknown){const code=e instanceof AccessError||e instanceof ApiError?e.code:"request_failed";setError(errorText(code));if(code==="unauthorized"){setSession("");setToken("");setMode("login");}}
 function receive(reply:Awaited<ReturnType<typeof accessApi>>){if(reply.state)setState(reply.state);if(reply.actor)setActorId(reply.actor.id);if(reply.session){setToken(reply.session);setSession(reply.session);}setMode(reply.mustChangePin?"change-pin":"live");}
 async function connect(){setMode("connecting");setError("");try{if(!configured){setMode("unavailable");return;}const token=readSession();if(token){try{receive(await accessApi("me",{},token));return;}catch{setSession("");setToken("");}}const status=await accessApi("bootstrap.status");setMode(status.ownerCreated?"login":"setup");}catch(e){report(e);setMode("unavailable");}}
 useEffect(()=>{void connect();},[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(""),3500);return()=>clearTimeout(timer);},[toast]);
 function preview(){setState(previewState());setActorId("owner");setMode("preview");setError("");setTab("users");}
 async function mutate(action:string,payload:Record<string,unknown>,local:(s:AccessState)=>AccessState){setBusy(true);setError("");try{if(mode==="preview"){const next={...local(state),revision:state.revision+1};localStorage.setItem(previewKey,JSON.stringify({...next,permissionSchema:2}));setState(next);if(!next.users.some(u=>u.id===actorId&&u.active)){setActorId(next.users.find(u=>u.role==="Owner"&&u.active)!.id);}}else{const reply=await accessApi(action,{...payload,revision:state.revision},session);if(reply.state)setState(reply.state);if(!reply.state||(payload.id===actorId&&(action==="pin.reset"||(action==="user.update"&&payload.role!==actor?.role)))){setSession("");setToken("");setMode("login");}else if(!reply.state.users.some(u=>u.id===actorId&&u.active)){setSession("");setToken("");setMode("login");}}setToast(mode==="preview"?t("បានរក្សាទុកក្នុងសាកល្បង","Saved in local preview"):t("បានរក្សាទុក","Saved"));return true;}catch(e){report(e);return false;}finally{setBusy(false);}}
 async function refresh(){setBusy(true);setError("");try{if(mode==="preview")setState(previewState());else receive(await accessApi("me",{},session));}catch(e){report(e);}finally{setBusy(false);}}
 async function logout(){setBusy(true);try{if(mode==="live")await accessApi("logout",{},session);}catch{}finally{setSession("");setToken("");setMode("login");setBusy(false);setError("");}}
 const nav=[{id:"users" as Tab,icon:Users,label:t("អ្នកប្រើ","Users")},{id:"roles" as Tab,icon:ShieldCheck,label:t("តួនាទី","Roles")},{id:"permissions" as Tab,icon:KeyRound,label:t("សិទ្ធិ","Permissions")},{id:"activity" as Tab,icon:History,label:t("ប្រវត្តិ","Activity")}];
 if(!["live","preview"].includes(mode))return <div className="access-auth"><div className="auth-card"><img src={logo} alt="OneBite"/><span className="access-eyebrow">ONEBITE ADMIN</span>{mode==="connecting"?<><h1>{t("កំពុងភ្ជាប់","Connecting…")}</h1><p>{t("កំពុងពិនិត្យសេវាគណនី","Checking the account service.")}</p></>:mode==="unavailable"?<><h1>{t("សេវាគណនីមិនទាន់រួចរាល់","Account service is not ready")}</h1><p>{t("សូមភ្ជាប់សេវា Supabase មុនប្រើគណនីពិត។ អ្នកអាចពិនិត្យ UI ដោយទិន្នន័យសាកល្បង។","Connect the Supabase account service before using real accounts. You can review the UI with sample data.")}</p>{error&&<div role="alert" className="access-error">{error}</div>}<button className="access-btn" onClick={()=>void connect()}><RefreshCw size={18}/>{t("ព្យាយាមភ្ជាប់ម្តងទៀត","Retry connection")}</button><button className="access-btn secondary" onClick={preview}>{t("បើកសាកល្បងក្នុងឧបករណ៍","Open local preview")}</button></>:<AuthForm mode={mode} busy={busy} error={error} onSubmit={async payload=>{setBusy(true);setError("");try{receive(await accessApi(mode==="setup"?"bootstrap":mode==="change-pin"?"pin.change":"login",payload,session));}catch(e){report(e);}finally{setBusy(false);}}}/>}<button className="access-text" onClick={()=>setLang(lang==="km"?"en":"km")}>{lang==="km"?"English":"ខ្មែរ"}</button>{(mode==="login"||mode==="setup")&&<button className="access-text" onClick={preview}>{t("មើលទិន្នន័យសាកល្បង","Review sample data")}</button>}</div></div>;
 if(!actor)return <div className="access-auth"><button className="access-btn" onClick={()=>void logout()}>{t("ចូលម្តងទៀត","Sign in again")}</button></div>;
 if(!can(state,actor,"admin.access"))return <div className="access-auth"><div className="auth-card"><img src={logo} alt="OneBite"/><h1>{t("មិនអនុញ្ញាតចូលរដ្ឋបាល","Admin access denied")}</h1><p>{t("តួនាទីរបស់អ្នកមិនអាចប្រើម៉ូឌុលនេះបានទេ។","Your role cannot access this module.")}</p>{mode==="preview"&&<button className="access-btn secondary" onClick={()=>setActorId(state.users.find(u=>u.active&&u.role==="Owner")!.id)}>{t("ត្រឡប់ទៅម្ចាស់សាកល្បង","Return to preview Owner")}</button>}<button className="access-btn" onClick={()=>void logout()}>{t("ចាកចេញ","Sign out")}</button></div></div>;
 const owner=can(state,actor,"users.manage"),canAssign=can(state,actor,"staff.assign");
 const visible=visibleAccounts(state,actor),filtered=visible.filter(u=>`${u.name} ${u.username}`.toLowerCase().includes(search.toLowerCase())&&(roleFilter==="all"||u.role===roleFilter)&&(statusFilter==="all"||u.active===(statusFilter==="active")));
 return <div className="access-app">
  <aside className="access-sidebar"><div className="access-brand"><img src={logo} alt="OneBite"/><span>ADMIN</span></div><p className="access-nav-label">{t("គ្រប់គ្រងគណនី","ACCOUNT MANAGEMENT")}</p><nav>{nav.filter(n=>n.id!=="activity"||owner).map(n=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>{setTab(n.id);setError("");}}><n.icon size={20}/>{n.label}{tab===n.id&&<span className="access-nav-dot"/>}</button>)}</nav><div className="access-sidebar-foot"><div className="access-person"><span className="access-avatar">{actor.name[0]}</span><div><strong>{actor.name}</strong><small>{roleName(actor.role)}</small></div></div><button className="access-text" onClick={()=>void logout()}><LogOut size={16}/>{t("ចាកចេញ","Sign out")}</button></div></aside>
  <div className="access-workspace"><header className="access-header"><div className="access-mobile-brand"><img src={logo} alt="OneBite"/></div><div className="access-breadcrumb">Admin <ChevronRight size={14}/><strong>{nav.find(n=>n.id===tab)!.label}</strong></div><div className="access-header-actions"><button className="access-icon" aria-label="Refresh accounts" onClick={()=>void refresh()} disabled={busy}><RefreshCw size={18}/></button><button className="access-language" onClick={()=>setLang(lang==="km"?"en":"km")}>{lang==="km"?"English":"ខ្មែរ"}</button><span className="access-avatar small">{actor.name[0]}</span></div></header>
  {mode==="preview"&&<div className="access-preview-bar"><span><AlertCircle size={16}/>{t("សាកល្បងក្នុងឧបករណ៍ · មិនមែនគណនីពិត","Local preview · These are not real accounts")}</span><label>{t("មើលជា","View as")}<SelectField aria-label="Preview identity" value={actorId} onChange={e=>{setActorId(e.target.value);setTab("users");setEditing(null);setEditRole(null);setResetUser(null);setError("");}}>{state.users.filter(u=>u.active).map(u=><option key={u.id} value={u.id}>{u.name} · {u.role}</option>)}</SelectField></label></div>}
  <main className="access-main"><div className="access-page-heading"><div><span className="access-eyebrow">{t("គណនី ONEBITE","ONEBITE ACCESS")}</span><h1>{tab==="users"?t("អ្នកប្រើរបស់អ្នក","Your team"):tab==="roles"?t("តួនាទី និងទំនួលខុសត្រូវ","Roles & responsibilities"):tab==="permissions"?t("សិទ្ធិក្នុងការប្រើប្រាស់","Permissions"):t("ប្រវត្តិការផ្លាស់ប្ដូរ","Activity log")}</h1><p>{tab==="users"?t("គណនីផ្ទាល់ខ្លួន តួនាទី និងសាខារបស់បុគ្គលិក។","Individual accounts, role assignments, and site access."):t("សិទ្ធិរបស់តួនាទីមានកម្រិតកំណត់។ មិនអាចរំលងច្បាប់អាជីវកម្ម។","Role permissions stay within hard limits and business rules.")}</p></div>{tab==="users"&&owner&&<button className="access-btn" onClick={()=>{setCreating(true);setEditing({id:crypto.randomUUID(),name:"",username:"",role:"Cashier",sites:[],active:true});setError("");}}><Plus size={19}/>{t("បន្ថែមអ្នកប្រើ","Add user")}</button>}</div>
  {error&&<div className="access-error" role="alert"><AlertCircle size={18}/>{error}<button className="access-text" onClick={()=>setError("")}>{t("បិទ","Dismiss")}</button></div>}
  {tab==="users"&&<><div className="access-stats"><div><span>{t("គណនីដែលអាចមើល","Visible accounts")}</span><strong>{visible.length}</strong><small>{t("តាមសិទ្ធិរបស់អ្នក","Based on your permissions")}</small></div><div><span>{t("គណនីដំណើរការ","Active accounts")}</span><strong>{visible.filter(u=>u.active).length}</strong><small>{t("ចូលប្រើតាមគណនីផ្ទាល់ខ្លួន","Individual sign-in")}</small></div><div><span>{t("តួនាទីស្តង់ដារ","Standard roles")}</span><strong>3</strong><small>Cashier · Supervisor · Owner</small></div></div>
   <div className="access-tools"><label className="access-search"><Search size={18}/><input aria-label="Search users" placeholder={t("ស្វែងរកឈ្មោះ ឬឈ្មោះអ្នកប្រើ","Search name or username…")} value={search} onChange={e=>setSearch(e.target.value)}/></label><SelectField aria-label="Filter role" value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}><option value="all">{t("គ្រប់តួនាទី","All roles")}</option>{roles.map(r=><option key={r}>{r}</option>)}</SelectField><SelectField aria-label="Filter status" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">{t("គ្រប់ស្ថានភាព","All statuses")}</option><option value="active">{t("ដំណើរការ","Active")}</option><option value="inactive">{t("ផ្អាក","Inactive")}</option></SelectField></div>
   <div className="access-user-list"><div className="access-table-head"><span>{t("អ្នកប្រើ","Person")}</span><span>{t("តួនាទី","Role")}</span><span>{t("សាខា","Site access")}</span><span>{t("ស្ថានភាព","Status")}</span><span/></div>{filtered.map(u=><div className="access-user-row" key={u.id}><div className="access-person"><span className={`access-avatar ${u.role.toLowerCase()}`}>{u.name[0]}</span><div><strong>{u.name}</strong><small>@{u.username}</small></div></div><span className={`access-role ${u.role.toLowerCase()}`}>{roleName(u.role)}</span><div className="access-site-tags">{u.role==="Owner"?<span><Store size={12}/>{t("គ្រប់សាខា","All sites")}</span>:u.sites.length?u.sites.map(id=><span key={id}>{state.sites.find(s=>s.id===id)?.name}</span>):<small>{t("គ្មានសាខា","No sites")}</small>}</div><span className={`access-status ${u.active?"active":"inactive"}`}><i/>{u.active?t("ដំណើរការ","Active"):t("ផ្អាក","Inactive")}</span><div className="access-row-actions">{(owner||(canAssign&&u.role==="Cashier"))&&<button className="access-icon" aria-label={`Edit ${u.name}`} onClick={()=>{setCreating(false);setEditing(u);setError("");}}><Pencil size={17}/></button>}{owner&&<button className="access-icon" aria-label={`Reset PIN for ${u.name}`} onClick={()=>{setResetUser(u);setError("");}} disabled={mode==="preview"}><KeyRound size={17}/></button>}</div></div>)}{!filtered.length&&<div className="access-empty"><Users size={32}/><h2>{t("រកមិនឃើញអ្នកប្រើ","No matching users")}</h2><p>{t("សូមប្ដូរពាក្យស្វែងរក ឬតម្រង","Try another search or filter.")}</p></div>}</div><div className="access-rule-note"><ShieldCheck size={20}/><p>{owner?t("ម្ចាស់គ្រប់គ្រងគណនី និងតួនាទី។ អ្នកត្រួតពិនិត្យអាចចាត់បុគ្គលិកតែទៅសាខាដែលគ្រប់គ្រង។","Owners manage accounts and roles. Supervisors can assign existing staff only within their managed sites."):t("អ្នកអាចមើលតែគណនីក្នុងសិទ្ធិរបស់អ្នក។","Only accounts within your access are shown.")}</p></div></>}
  {tab==="roles"&&<div className="access-role-grid">{roles.map(r=><section className="access-role-card transition-shadow hover:shadow-sm" key={r}><div className="access-role-card-top"><span className={`access-role-icon ${r.toLowerCase()}`}><ShieldCheck size={24}/></span><span className="access-label">{t("តួនាទីស្តង់ដារ","Standard role")}</span></div><h2>{roleName(r)}</h2><p>{r==="Owner"?t("គ្រប់គ្រងគណនី សាខា និងការកំណត់អាជីវកម្ម។","Manage accounts, sites, and business configuration."):r==="Supervisor"?t("ត្រួតពិនិត្យប្រាក់ និងចាត់បុគ្គលិកនៅសាខាដែលគ្រប់គ្រង។","Oversee cash and assign staff at managed sites."):t("ទទួលការបញ្ជាទិញ និងគ្រប់គ្រងវេននៅសាខាដែលបានចាត់តាំង។","Take orders and manage shifts at assigned sites.")}</p><div className="access-role-summary"><span>{visible.filter(u=>u.role===r).length} {t("គណនីដែលអាចមើល","visible accounts")}</span><strong>{permissionDefinitions.filter(p=>hasPermission(state.grants[r],r,p.id)).length} {t("សិទ្ធិ","permissions")}</strong></div><ul>{permissionDefinitions.filter(p=>hasPermission(state.grants[r],r,p.id)).slice(0,4).map(p=><li key={p.id}><Check size={15}/>{t(p.km,p.en)}</li>)}</ul><button className="access-btn secondary" onClick={()=>{setEditRole(r);setError("");}}><ShieldCheck size={16}/>{t("មើលសិទ្ធិ","Review permissions")}<ArrowUpRight size={16}/></button></section>)}</div>}
  {tab==="permissions"&&<><div className="access-rule-note"><LockKeyhole size={20}/><p>{t("ត្រូវអនុញ្ញាតទាំងម៉ូឌុល និងសកម្មភាព។ ការសងប្រាក់ និងការរំលងកម្រិតត្រូវហាមគ្រប់តួនាទី។","Both module access and action permission are required. Refunds and discount overrides remain forbidden for every role.")}</p></div><div className="access-permission-groups grid gap-6">{moduleDefinitions.map(m=><section className="access-permission-module" key={m.id}><h2>{t(m.km,m.en)}</h2><div className="access-permission-matrix"><div className="access-matrix-row access-matrix-head"><span>{t("សិទ្ធិ","Permission")}</span>{roles.map(r=><span key={r}>{roleName(r)}</span>)}</div>{[m,...permissionDefinitions.filter(p=>p.group===m.group&&p.id!==m.id),...(m.group==="POS"?permissionDefinitions.filter(p=>p.group==="Never"):[])].map(p=><div className={`access-matrix-row ${p.id===m.id?"access-module-row":""}`} key={p.id}><div><strong>{p.id===m.id?t("ចូលប្រើម៉ូឌុល","Module access"):t(p.km,p.en)}</strong><small>{p.id===m.id?t("អនុញ្ញាត / បដិសេធ","Allow / Deny"):p.group==="Never"?t("ហាមជានិច្ច","Always forbidden"):t("សកម្មភាព","Action")}</small></div>{roles.map(r=>{const allowed=hasPermission(state.grants[r],r,p.id);return <span key={r} className={allowed?"allowed":"denied"} aria-label={`${r}: ${allowed?"allowed":"denied"}`}>{allowed?<Check size={18}/>:<X size={17}/>}</span>;})}</div>)}</div>{!permissionDefinitions.some(p=>p.group===m.group&&p.id!==m.id)&&<p className="access-helper">{t("សកម្មភាពលម្អិតនឹងបន្ថែមពេលបង្កើតម៉ូឌុលនេះ។","Action permissions will be added when this module is built.")}</p>}</section>)}</div></>}
  {tab==="activity"&&owner&&<div className="access-activity">{state.events.length?[...state.events].reverse().map(e=><div key={e.id}><span className="access-avatar"><History size={18}/></span><div><strong>{e.targetName}</strong><p>{e.action} · {e.actorName}</p><small>{e.detail}</small></div><time>{new Intl.DateTimeFormat(lang==="km"?"km-KH":"en-GB",{timeZone:"Asia/Phnom_Penh",dateStyle:"short",timeStyle:"short"}).format(new Date(e.time))}</time></div>):<div className="access-empty"><History size={32}/><h2>{t("មិនទាន់មានការផ្លាស់ប្ដូរ","No changes yet")}</h2><p>{t("ការផ្លាស់ប្ដូរគណនី និងសិទ្ធិនឹងបង្ហាញនៅទីនេះ។","Account and permission changes will appear here.")}</p></div>}</div>}
  </main><nav className="access-bottom-nav">{nav.filter(n=>n.id!=="activity"||owner).map(n=><button className={tab===n.id?"active":""} key={n.id} onClick={()=>setTab(n.id)}><n.icon size={21}/><span>{n.label}</span></button>)}</nav></div>
  {editing&&<UserEditor account={editing} creating={creating} state={state} actor={actor} live={mode==="live"} busy={busy} error={error} onClose={()=>{setEditing(null);setError("");}} onSave={async (account,pin)=>{const all=can(state,actor,"users.manage");const success=await mutate(all?(creating?"user.create":"user.update"):"sites.assign",all?{...account,...(pin?{pin}:{})}:{id:account.id,sites:account.sites},s=>all?saveAccount(s,actor.id,account,creating):assignSites(s,actor.id,account.id,account.sites));if(success)setEditing(null);}}/>}
  {editRole&&<RoleEditor role={editRole} state={state} editable={can(state,actor,"roles.manage")&&editRole!=="Owner"} busy={busy} error={error} onClose={()=>{setEditRole(null);setError("");}} onSave={async permissions=>{if(await mutate("permissions.update",{role:editRole,permissions},s=>saveGrants(s,actor.id,editRole,permissions)))setEditRole(null);}}/>}
  {resetUser&&<PinReset user={resetUser} busy={busy} error={error} onClose={()=>{setResetUser(null);setError("");}} onSave={async pin=>{if(await mutate("pin.reset",{id:resetUser.id,pin},s=>s))setResetUser(null);}}/>}
  {toast&&<div className="access-toast" role="status"><Check size={18}/>{toast}</div>}
 </div>;
}
function AuthForm({mode,busy,error,onSubmit}:{mode:Mode;busy:boolean;error:string;onSubmit:(payload:Record<string,unknown>)=>Promise<void>}){
 const {t}=useLanguage();const [name,setName]=useState(""),[username,setUsername]=useState(""),[pin,setPin]=useState(""),[confirmation,setConfirmation]=useState(""),[code,setCode]=useState(""),[current,setCurrent]=useState("");
 const setup=mode==="setup",change=mode==="change-pin";const valid=/^[0-9]{6}$/.test(pin)&&(!setup&&!change||pin===confirmation)&&(!setup||(name.trim()&&/^[a-f0-9]{64}$/.test(code)))&&(!change||/^[0-9]{6}$/.test(current));
 return <form className="access-form" onSubmit={e=>{e.preventDefault();if(valid&&!busy)void onSubmit({...(!change?{username}:{}),pin,...(setup?{name,setup_code:code}:{}),...(change?{current_pin:current}:{})});}}><h1>{setup?t("បង្កើតគណនីម្ចាស់","Set up the first Owner"):change?t("ប្ដូរ PIN របស់អ្នក","Choose your own PIN"):t("សូមស្វាគមន៍","Welcome back")}</h1><p>{setup?t("ប្រើកូដបង្កើតម្ចាស់មួយដង ដើម្បីការពារគណនីដំបូង។","Use your one-time setup code to protect the first Owner account."):change?t("អ្នកត្រូវប្ដូរ PIN បណ្ដោះអាសន្ន មុនបន្ត។","Change your temporary PIN before continuing."):t("ចូលគណនីផ្ទាល់ខ្លួន ដោយឈ្មោះអ្នកប្រើ និង PIN។","Sign in with your individual username and PIN.")}</p>{setup&&<><label>{t("កូដបង្កើតម្ចាស់","One-time setup code")}<input value={code} type="password" autoComplete="off" onChange={e=>setCode(e.target.value.trim())}/></label><label>{t("ឈ្មោះពេញ","Full name")}<input maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label></>}{!change&&<label>{t("ឈ្មោះអ្នកប្រើ","Username")}<input autoComplete="username" autoCapitalize="none" autoCorrect="off" value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} required/></label>}{change&&<label>{t("PIN បច្ចុប្បន្ន","Current PIN")}<input type="password" inputMode="numeric" maxLength={6} value={current} onChange={e=>setCurrent(e.target.value.replace(/\D/g,""))}/></label>}<label>{change?t("PIN ថ្មី 6 ខ្ទង់","New 6-digit PIN"):t("លេខ PIN 6 ខ្ទង់","6-digit PIN")}<input type="password" autoComplete={setup||change?"new-password":"current-password"} inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))}/></label>{(setup||change)&&<label>{t("បញ្ជាក់ PIN","Confirm PIN")}<input type="password" autoComplete="new-password" inputMode="numeric" maxLength={6} value={confirmation} onChange={e=>setConfirmation(e.target.value.replace(/\D/g,""))}/></label>}{error&&<div className="access-error" role="alert">{error}</div>}<button className="access-btn" disabled={!valid||busy}>{busy?t("កំពុងដំណើរការ…","Working…"):setup?t("បង្កើតម្ចាស់","Create Owner"):change?t("រក្សាទុក PIN ថ្មី","Save new PIN"):t("ចូលគណនី","Sign in")}</button></form>;
}
function UserEditor({account,creating,state,actor,live,busy,error,onClose,onSave}:{account:Account;creating:boolean;state:AccessState;actor:Account;live:boolean;busy:boolean;error:string;onClose:()=>void;onSave:(account:Account,pin:string)=>Promise<void>}){
 const {t}=useLanguage();const [draft,setDraft]=useState({...account,sites:[...account.sites]}),[pin,setPin]=useState(""),[confirm,setConfirm]=useState("");const all=can(state,actor,"users.manage"),duplicate=state.users.some(u=>u.id!==draft.id&&u.username.toLowerCase()===draft.username.trim().toLowerCase()),lastOwner=account.active&&account.role==="Owner"&&state.users.filter(u=>u.role==="Owner"&&u.active).length===1;
 const update=(data:Partial<Account>)=>setDraft(old=>({...old,...data}));const usernameValid=/^[a-z0-9][a-z0-9_.-]{2,31}$/.test(draft.username.trim().toLowerCase());const valid=(!all||draft.name.trim()&&usernameValid&&!duplicate)&&(!live||!creating||/^[0-9]{6}$/.test(pin)&&pin===confirm);
 return <Modal title={creating?t("បន្ថែមអ្នកប្រើ","Add user"):all?t("កែគណនី","Edit account"):t("ចាត់បុគ្គលិកទៅសាខា","Assign staff to sites")} onClose={()=>{if(!busy)onClose();}}><form className="access-form" onSubmit={e=>{e.preventDefault();if(valid&&!busy)void onSave(draft,pin);}}>{all&&<><label>{t("ឈ្មោះពេញ","Full name")}<input maxLength={100} value={draft.name} onChange={e=>update({name:e.target.value})} required/></label><label>{t("ឈ្មោះអ្នកប្រើ","Username")}<input aria-label={t("ឈ្មោះអ្នកប្រើ","Username")} autoCapitalize="none" autoCorrect="off" autoComplete="off" maxLength={32} value={draft.username} onChange={e=>update({username:e.target.value.toLowerCase()})} aria-invalid={duplicate}/><small>{t("3–32 តួអក្សរ · a–z, 0–9, _ . -","3–32 characters · a–z, 0–9, _ . -")}</small></label>{duplicate&&<div role="alert" className="access-error">{t("ឈ្មោះអ្នកប្រើនេះមានរួចហើយ","This username is already used.")}</div>}<label>{t("តួនាទី","Role")}<SelectField aria-label={t("តួនាទី","Role")} value={draft.role} disabled={lastOwner} onChange={e=>update({role:e.target.value as Role})}>{roles.map(r=><option key={r}>{r}</option>)}</SelectField></label></>}{!all&&<div className="access-editor-person"><UserRound size={22}/><div><strong>{account.name}</strong><small>@{account.username} · {account.role}</small></div></div>}
 <fieldset><legend>{t("សាខាដែលបានចាត់តាំង","Assigned sites")}</legend>{draft.role==="Owner"?<div className="access-rule-note"><Store size={18}/>{t("ម្ចាស់អាចប្រើគ្រប់សាខា","Owners have access to all sites.")}</div>:state.sites.map(site=>{const editable=all||actor.sites.includes(site.id)&&site.active;return <label className={`access-site-choice ${draft.sites.includes(site.id)?"selected":""}`} key={site.id}><CheckField checked={draft.sites.includes(site.id)} disabled={!editable} onChange={e=>update({sites:e.target.checked?[...draft.sites,site.id]:draft.sites.filter(id=>id!==site.id)})}/><Store size={18}/><span>{site.name}{!editable&&<small>{t("នៅក្រៅសាខារបស់អ្នក · រក្សាដដែល","Outside your scope · Preserved")}</small>}</span>{draft.sites.includes(site.id)&&<Check size={17}/>}</label>;})}</fieldset>
 {all&&<label className="access-checkbox"><CheckField checked={draft.active} disabled={lastOwner} onChange={e=>update({active:e.target.checked})}/>{t("គណនីដំណើរការ","Account active")}</label>}{lastOwner&&<p className="access-helper"><LockKeyhole size={16}/>{t("ម្ចាស់ចុងក្រោយត្រូវបានការពារ។ បន្ថែមម្ចាស់ថ្មីមុនផ្លាស់ប្ដូរ។","The last active Owner is protected. Add another Owner before changing this account.")}</p>}
 {creating&&live&&<><label>{t("PIN បណ្ដោះអាសន្ន 6 ខ្ទង់","Temporary 6-digit PIN")}<input type="password" inputMode="numeric" autoComplete="new-password" value={pin} maxLength={6} onChange={e=>setPin(e.target.value.replace(/\D/g,""))}/></label><label>{t("បញ្ជាក់ PIN","Confirm PIN")}<input type="password" inputMode="numeric" autoComplete="new-password" value={confirm} maxLength={6} onChange={e=>setConfirm(e.target.value.replace(/\D/g,""))}/></label><small>{t("បុគ្គលិកត្រូវប្ដូរ PIN នៅពេលចូលដំបូង។","The person must change this PIN on first sign-in.")}</small></>}{!live&&<p className="access-helper">{t("សាកល្បងតែព័ត៌មានគណនី · មិនកំណត់ PIN ពិត","Profile preview only · Real PIN setup requires the backend")}</p>}{error&&<div className="access-error" role="alert">{error}</div>}<button className="access-btn" disabled={!valid||busy}>{busy?t("កំពុងរក្សាទុក…","Saving…"):t("រក្សាទុក","Save changes")}</button></form></Modal>;
}
function RoleEditor({role,state,editable,busy,error,onClose,onSave}:{role:Role;state:AccessState;editable:boolean;busy:boolean;error:string;onClose:()=>void;onSave:(permissions:Permission[])=>Promise<void>}){
 const {t}=useLanguage();const [grants,setGrants]=useState([...state.grants[role]]);
 return <Modal title={`${role} · ${t("សិទ្ធិ","Permissions")}`} onClose={()=>{if(!busy)onClose();}}><div className="access-rule-note"><ShieldCheck size={19}/>{role==="Owner"?t("សិទ្ធិម្ចាស់ត្រូវបានការពារ។","Owner permissions are protected."):t("បដិសេធម៉ូឌុលនឹងបិទសកម្មភាពទាំងអស់។ ការកំណត់សកម្មភាពរក្សាទុកដដែល។","Denying a module blocks all its actions. Action settings are preserved.")}</div><div className="access-grants">{moduleDefinitions.map(m=>{const access=grants.includes(m.id);const actions=[...permissionDefinitions.filter(p=>p.group===m.group&&p.id!==m.id),...(m.group==="POS"?permissionDefinitions.filter(p=>p.group==="Never"):[])];return <fieldset className="access-grant-module" key={m.id}><legend>{t(m.km,m.en)}</legend><label className="access-module-toggle"><CheckField aria-label={`Access ${m.en} module`} checked={access} disabled={!editable||!ceilings[role].includes(m.id)||busy} onChange={e=>setGrants(old=>e.target.checked?[...old,m.id]:old.filter(id=>id!==m.id))}/><span>{t("ចូលប្រើម៉ូឌុល","Module access")}<small>{access?t("អនុញ្ញាត","Allowed"):t("បដិសេធ","Denied")}</small></span></label><div className="access-module-actions">{actions.map(p=>{const allowed=ceilings[role].includes(p.id);return <label key={p.id} className={!allowed||!access?"locked":""}><CheckField aria-label={t(p.km,p.en)} checked={grants.includes(p.id)} disabled={!editable||!allowed||!access||busy} onChange={e=>setGrants(old=>e.target.checked?[...old,p.id]:old.filter(id=>id!==p.id))}/><span>{t(p.km,p.en)}<small>{!allowed?t("មិនអនុញ្ញាតសម្រាប់តួនាទីនេះ","Forbidden for this role"):!access?t("ត្រូវបានបិទដោយម៉ូឌុល","Blocked by module access"):t("សកម្មភាព","Action")}</small></span>{!allowed&&<LockKeyhole size={15}/>}</label>;})}{!actions.length&&<p className="access-helper">{t("សកម្មភាពលម្អិតនឹងបន្ថែមពេលបង្កើតម៉ូឌុលនេះ។","Action permissions will be added when this module is built.")}</p>}</div></fieldset>;})}</div>{error&&<div className="access-error" role="alert">{error}</div>}{editable&&<button className="access-btn" onClick={()=>void onSave(grants)} disabled={busy}>{t("រក្សាទុកសិទ្ធិ","Save permissions")}</button>}</Modal>;

}
function PinReset({user,busy,error,onClose,onSave}:{user:Account;busy:boolean;error:string;onClose:()=>void;onSave:(pin:string)=>Promise<void>}){const {t}=useLanguage();const[pin,setPin]=useState(""),[confirm,setConfirm]=useState("");return <Modal title={t("កំណត់ PIN ឡើងវិញ","Reset PIN")} onClose={()=>{if(!busy)onClose();}}><form className="access-form" onSubmit={e=>{e.preventDefault();if(/^[0-9]{6}$/.test(pin)&&pin===confirm&&!busy)void onSave(pin);}}><p>{user.name} · @{user.username}</p><div className="access-rule-note"><LockKeyhole size={19}/>{t("បិទគ្រប់សម័យចូលប្រើ។ បុគ្គលិកត្រូវប្ដូរ PIN បណ្ដោះអាសន្ន។","All sessions will be revoked. The person must change the temporary PIN.")}</div><label>{t("PIN បណ្ដោះអាសន្នថ្មី","New temporary PIN")}<input type="password" autoComplete="new-password" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))}/></label><label>{t("បញ្ជាក់ PIN","Confirm PIN")}<input type="password" autoComplete="new-password" inputMode="numeric" maxLength={6} value={confirm} onChange={e=>setConfirm(e.target.value.replace(/\D/g,""))}/></label>{error&&<div className="access-error" role="alert">{error}</div>}<button className="access-btn" disabled={busy||!/^[0-9]{6}$/.test(pin)||pin!==confirm}>{t("កំណត់ PIN និងបិទសម័យចូលប្រើ","Reset PIN and revoke sessions")}</button></form></Modal>;}
