import { useEffect, useId, useState, type CSSProperties, type ReactNode } from "react";
import { Users, ShieldCheck, KeyRound, Search, Plus, Pencil, ChevronRight, Check, X, Store, LogOut, RefreshCw, LockKeyhole, History, Copy, UserPlus, ArrowUpRight, AlertCircle, UserRound, WifiOff, Crown, ChevronDown, ShoppingBag, Clock, Boxes, BadgePercent, Gift, CircleX, QrCode, ArrowRightLeft, Banknote, MapPin, Utensils, SlidersHorizontal } from "lucide-react";
import { useLanguage, PageHeading, EmptyState, AppDialog as Modal, SelectField, CheckField, SwitchField, AppTitleBar, type SyncStatus } from "@onebite/ui";
import { roles as builtInRoles, roleIds, roleDisplayName, createRole, permissionAvailable, ownerRequiredPermissions, type CustomRole, moduleDefinitions, hasPermission, permissionDefinitions, ceilings, initialAccessState, can, saveAccount, assignSites, saveGrants, visibleAccounts, AccessError, type Account, type Role, type Permission, type AccessState } from "@onebite/core/access";
import { accessApi, configured, readSession, setSession, ApiError, type Snapshot } from "./access-api";
import { saveRequest } from "./save-request";
import icon from "../../../resources/brand/one-bite-icon-orange.svg";
import logo from "../../../resources/brand/one-bite-logo-orange.svg";
type Tab = "users" | "roles" | "permissions" | "activity";
type Mode = "connecting" | "unavailable" | "login" | "setup" | "change-pin" | "live" | "preview";
const previewKey="onebite-admin-access-preview-v1";
const fresh=(): Snapshot=>({...initialAccessState(),revision:0});
function previewState(): Snapshot {try{const raw=localStorage.getItem(previewKey);if(raw){const parsed=JSON.parse(raw);if(parsed.version===1&&Array.isArray(parsed.users)&&Array.isArray(parsed.sites)&&parsed.grants&&roleIds(parsed).every(r=>Array.isArray(parsed.grants[r]))&&parsed.users.every((u:Account)=>roleIds(parsed).includes(u.role)&&Array.isArray(u.sites))&&Array.isArray(parsed.events))return parsed.permissionSchema===2?parsed:{...parsed,permissionSchema:2,grants:Object.fromEntries(builtInRoles.map(r=>[r,[...parsed.grants[r],...moduleDefinitions.filter(m=>ceilings[r].includes(m.id)).map(m=>m.id)]]))};}}catch{}return fresh();}
export function AccessApp(){
 const {t,lang,setLang}=useLanguage();
 const [mode,setMode]=useState<Mode>("connecting"),[state,setState]=useState<Snapshot>(fresh),[actorId,setActorId]=useState("owner"),[session,setToken]=useState(readSession),[tab,setTab]=useState<Tab>("users");
 const [error,setError]=useState(""),[busy,setBusy]=useState(false),[toast,setToast]=useState(""),[search,setSearch]=useState(""),[roleFilter,setRoleFilter]=useState("all"),[statusFilter,setStatusFilter]=useState("active");
 const [editing,setEditing]=useState<Account|null>(null),[creating,setCreating]=useState(false),[editRole,setEditRole]=useState<Role|null>(null),[resetUser,setResetUser]=useState<Account|null>(null),[viewingId,setViewingId]=useState<string|null>(null),[assigning,setAssigning]=useState<Account|null>(null);
 const [syncStatus,setSyncStatus]=useState<SyncStatus>("idle"),[pendingCount,setPendingCount]=useState(0);
 const [dark,setDark]=useState(()=>localStorage.getItem("onebite-theme")==="dark");
 useEffect(()=>{document.documentElement.dataset.theme=dark?"dark":"light";localStorage.setItem("onebite-theme",dark?"dark":"light");},[dark]);
 const [errorCode,setErrorCode]=useState(""),[editorVersion,setEditorVersion]=useState(0);
 const roles=roleIds(state);
 const [newRole,setNewRole]=useState<CustomRole|null>(null);
 const actor=state.users.find(u=>u.id===actorId&&u.active);
 const roleName=(role:Role)=>role==="Owner"?t("ម្ចាស់","Owner"):role==="Supervisor"?t("អ្នកត្រួតពិនិត្យ","Supervisor"):role==="Cashier"?t("អ្នកគិតលុយ","Cashier"):roleDisplayName(state,role);
 const errorText=(code:string)=>({duplicate_role:t("ឈ្មោះតួនាទីនេះមានរួចហើយ","This role name is already used."),invalid_description:t("ការពិពណ៌នាត្រូវមានមិនលើស 160 តួអក្សរ","Description must contain at most 160 characters."),forbidden:t("អ្នកមិនមានសិទ្ធិធ្វើសកម្មភាពនេះ","You do not have permission for this action."),invalid_role:t("សូមជ្រើសរើសតួនាទីត្រឹមត្រូវ","Select a valid role."),invalid_name:t("សូមបញ្ចូលឈ្មោះពី 1 ដល់ 100 តួអក្សរ","Name must contain 1–100 characters."),invalid_username:t("ឈ្មោះអ្នកប្រើត្រូវមាន 3–32 តួអក្សរ ជាអក្សរឡាតាំងតូច លេខ ឬ _ . -","Username must be 3–32 lowercase letters, digits, _, . or -."),duplicate_username:t("ឈ្មោះអ្នកប្រើនេះមានរួចហើយ","This username is already used."),invalid_site:t("សាខាដែលបានជ្រើសមិនត្រឹមត្រូវ","Invalid site assignment."),site_required:t("គណនីដំណើរការត្រូវមានសាខាមួយយ៉ាងតិច","An active staff account needs at least one active site."),last_owner:t("ត្រូវរក្សាម្ចាស់ដែលដំណើរការមួយយ៉ាងតិច","At least one active Owner must remain."),immutable_grant:t("សិទ្ធិរបស់ម្ចាស់ត្រូវបានការពារសម្រាប់គ្រប់គ្រងគណនី","Owner account and role administration must stay enabled."),permission_ceiling:t("មិនអាចផ្ដល់សិទ្ធិលើសកម្រិតតួនាទី","This permission is not available yet or is forbidden by business rules."),invalid_credentials:t("ឈ្មោះអ្នកប្រើ ឬ PIN មិនត្រឹមត្រូវ","Incorrect username or PIN."),login_throttled:t("សូមរង់ចាំ រួចព្យាយាមម្តងទៀត។ បើចូលខុសច្រើន ត្រូវរង់ចាំ 15 នាទី។","Please wait before retrying. Repeated failures lock the account for 15 minutes."),invalid_setup:t("កូដបង្កើតម្ចាស់មិនត្រឹមត្រូវ ឬត្រូវបានប្រើរួច","Owner setup code is invalid or already used."),invalid_pin:t("ប្រើលេខ PIN ថ្មី 6 ខ្ទង់","Use a new six-digit PIN."),invalid_account:t("សូមពិនិត្យឈ្មោះ ឈ្មោះអ្នកប្រើ តួនាទី និង PIN","Check the name, username, role, and PIN."),stale_revision:t("ទិន្នន័យបានផ្លាស់ប្ដូរ។ ធ្វើបច្ចុប្បន្នភាព រួចពិនិត្យមុនរក្សាទុក។","Data changed since this editor opened. Refresh and review before saving."),unauthorized:t("សម័យចូលប្រើបានផុតកំណត់។ សូមចូលម្តងទៀត។","Your session expired or was revoked. Sign in again."),network_failed:t("មិនអាចភ្ជាប់ទៅ Supabase។ ពិនិត្យអ៊ីនធឺណិត និងសិទ្ធិបណ្ដាញ។","Cannot reach Supabase. Check your internet connection and network access."),request_timeout:t("សំណើបានហួសពេល។ សូមព្យាយាមម្តងទៀត។","The request timed out. Please retry."),not_connected:t("មិនទាន់បានភ្ជាប់សេវាគណនី","The account service is not connected yet.")}[code]||t("មិនអាចបញ្ចប់សំណើ។ សូមព្យាយាមម្តងទៀត។","Could not complete the request. Please try again."));
 function report(e:unknown){const code=e instanceof AccessError||e instanceof ApiError?e.code:"request_failed";setErrorCode(code);setError(errorText(code));if(code==="unauthorized"){setSession("");setToken("");setMode("login");}}
 function receive(reply:Awaited<ReturnType<typeof accessApi>>){setSyncStatus("complete");if(reply.state)setState(reply.state);if(reply.actor)setActorId(reply.actor.id);if(reply.session){setToken(reply.session);setSession(reply.session);}setMode(reply.mustChangePin?"change-pin":"live");}
 async function connect(){setMode("connecting");setError("");try{if(!configured){setMode("unavailable");return;}const token=readSession();if(token){try{receive(await accessApi("me",{},token));return;}catch{setSession("");setToken("");}}const status=await accessApi("bootstrap.status");setMode(status.ownerCreated?"login":"setup");}catch(e){report(e);setMode("unavailable");}}
 useEffect(()=>{void connect();},[]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(""),3500);return()=>clearTimeout(timer);},[toast]);
 function preview(){setState(previewState());setActorId("owner");setMode("preview");setSyncStatus("idle");setError("");setTab("users");}
 async function mutate(action:string,payload:Record<string,unknown>,local:(s:AccessState)=>AccessState){setBusy(true);setSyncStatus("syncing");setPendingCount(mode==="live"?1:0);setError("");try{if(mode==="preview"){const next={...local(state),revision:state.revision+1};localStorage.setItem(previewKey,JSON.stringify({...next,permissionSchema:2}));setState(next);if(!next.users.some(u=>u.id===actorId&&u.active)){setActorId(next.users.find(u=>u.role==="Owner"&&u.active)!.id);}}else{const reply=await saveRequest(action,payload,state,session);if(reply.state)setState(reply.state);if(!reply.state||(payload.id===actorId&&(action==="pin.reset"||(action==="user.update"&&payload.role!==actor?.role)))){setSession("");setToken("");setMode("login");}else if(!reply.state.users.some(u=>u.id===actorId&&u.active)){setSession("");setToken("");setMode("login");}}setSyncStatus(mode==="preview"?"idle":"complete");setToast(mode==="preview"?t("បានរក្សាទុកក្នុងសាកល្បង","Saved in local preview"):t("បានរក្សាទុក","Saved"));return true;}catch(e){setSyncStatus("failed");report(e);return false;}finally{setPendingCount(0);setBusy(false);}}
 async function refresh(){setBusy(true);setSyncStatus("syncing");setError("");try{if(mode==="preview")setState(previewState());else receive(await accessApi("me",{},session));setSyncStatus(mode==="preview"?"idle":"complete");}catch(e){setSyncStatus("failed");report(e);}finally{setBusy(false);}}
 async function reloadEditor(){setBusy(true);setError("");try{const reply=await accessApi("me",{},session);receive(reply);if(editing&&!creating){const latest=reply.state?.users.find(user=>user.id===editing.id);setEditing(latest||null);}if(assigning){setAssigning(reply.state?.users.find(user=>user.id===assigning.id)||null);}setEditorVersion(value=>value+1);setErrorCode("");setToast(t("សូមពិនិត្យទិន្នន័យថ្មី មុនរក្សាទុក។","Review the latest data before saving."));}catch(e){report(e);}finally{setBusy(false);}}
 async function logout(){setBusy(true);try{if(mode==="live")await accessApi("logout",{},session);}catch{}finally{setSession("");setToken("");setMode("login");setBusy(false);setError("");}}
 const nav=[{id:"users" as Tab,icon:Users,label:t("អ្នកប្រើ","Users")},{id:"roles" as Tab,icon:ShieldCheck,label:t("តួនាទី","Roles")},{id:"permissions" as Tab,icon:KeyRound,label:t("សិទ្ធិ","Permissions")},{id:"activity" as Tab,icon:History,label:t("ប្រវត្តិ","Activity")}];
 if(!["live","preview"].includes(mode))return <div className="access-auth"><div className="auth-card"><img src={logo} alt="OneBite"/><span className="access-eyebrow">ONEBITE ADMIN</span>{mode==="connecting"?<><h1>{t("កំពុងភ្ជាប់","Connecting…")}</h1><p>{t("កំពុងពិនិត្យសេវាគណនី","Checking the account service.")}</p></>:mode==="unavailable"?<><h1>{t("សេវាគណនីមិនទាន់រួចរាល់","Account service is not ready")}</h1><p>{t("សូមភ្ជាប់សេវា Supabase មុនប្រើគណនីពិត។ អ្នកអាចពិនិត្យ UI ដោយទិន្នន័យសាកល្បង។","Connect the Supabase account service before using real accounts. You can review the UI with sample data.")}</p>{error&&<div role="alert" className="access-error">{error}</div>}<button className="access-btn" onClick={()=>void connect()}><RefreshCw size={18}/>{t("ព្យាយាមភ្ជាប់ម្តងទៀត","Retry connection")}</button><button className="access-btn secondary" onClick={preview}>{t("បើកសាកល្បងក្នុងឧបករណ៍","Open local preview")}</button></>:<AuthForm mode={mode} busy={busy} error={error} onSubmit={async payload=>{setBusy(true);setError("");try{receive(await accessApi(mode==="setup"?"bootstrap":mode==="change-pin"?"pin.change":"login",payload,session));}catch(e){report(e);}finally{setBusy(false);}}}/>}<button className="access-text" onClick={()=>setLang(lang==="km"?"en":"km")}>{lang==="km"?"English":"ខ្មែរ"}</button>{(mode==="login"||mode==="setup")&&<button className="access-text" onClick={preview}>{t("មើលទិន្នន័យសាកល្បង","Review sample data")}</button>}</div></div>;
 if(!actor)return <div className="access-auth"><button className="access-btn" onClick={()=>void logout()}>{t("ចូលម្តងទៀត","Sign in again")}</button></div>;
 if(!can(state,actor,"admin.access"))return <div className="access-auth"><div className="auth-card"><img src={logo} alt="OneBite"/><h1>{t("មិនអនុញ្ញាតចូលរដ្ឋបាល","Admin access denied")}</h1><p>{t("តួនាទីរបស់អ្នកមិនអាចប្រើម៉ូឌុលនេះបានទេ។","Your role cannot access this module.")}</p>{mode==="preview"&&<button className="access-btn secondary" onClick={()=>setActorId(state.users.find(u=>u.active&&u.role==="Owner")!.id)}>{t("ត្រឡប់ទៅម្ចាស់សាកល្បង","Return to preview Owner")}</button>}<button className="access-btn" onClick={()=>void logout()}>{t("ចាកចេញ","Sign out")}</button></div></div>;
 const policyReady=mode==="preview"||Array.isArray(state.customRoles);
 const manageRoles=can(state,actor,"roles.manage");
 const owner=can(state,actor,"users.manage"),canAssign=can(state,actor,"staff.assign");
 function createUser(){if(!owner)return;setCreating(true);setViewingId(null);setEditing({id:crypto.randomUUID(),name:"",username:"",role:"Cashier",sites:[],active:true});setError("");}
 function clearUserFilters(){setSearch("");setRoleFilter("all");setStatusFilter("active");}
 const userCreateAction=owner?{label:t("បង្កើតអ្នកប្រើថ្មី","Create new user"),onClick:createUser,icon:<UserPlus size={18}/>} : undefined;
 const userFiltersActive=!!search.trim()||roleFilter!=="all"||statusFilter!=="active";
 const visible=visibleAccounts(state,actor),filtered=visible.filter(u=>`${u.name} ${u.username}`.toLowerCase().includes(search.trim().toLowerCase())&&(roleFilter==="all"||u.role===roleFilter)&&(statusFilter==="all"||u.active===(statusFilter==="active")));
 const recovery=error&&errorCode==="stale_revision"?<button type="button" className="access-btn secondary" disabled={busy} onClick={()=>void reloadEditor()}><RefreshCw size={16}/>{t("ផ្ទុកថ្មី · បោះបង់ការកែប្រែនេះ","Reload latest · Discard this draft")}</button>:null;
 const details=visible.find(u=>u.id===viewingId);
 const nameOrder=new Intl.Collator(lang==="km"?"km-KH":"en",{sensitivity:"base",numeric:true});
 return <div className="access-app">
  <aside className="access-sidebar"><div className="access-brand"><img src={logo} alt="OneBite"/><span>ADMIN</span></div><p className="access-nav-label">{t("គ្រប់គ្រងគណនី","ACCOUNT MANAGEMENT")}</p><nav>{nav.filter(n=>n.id!=="activity"||owner).map(n=><button key={n.id} className={tab===n.id?"active":""} onClick={()=>{setTab(n.id);setError("");}}><n.icon size={20}/>{n.label}{tab===n.id&&<span className="access-nav-dot"/>}</button>)}</nav><div className="access-sidebar-foot"><div className="access-person"><span className="access-avatar">{actor.name[0]}</span><div><strong>{actor.name}</strong><small>{roleName(actor.role)}</small></div></div><button className="access-text" onClick={()=>void logout()}><LogOut size={16}/>{t("ចាកចេញ","Sign out")}</button></div></aside>
  <div className="access-workspace"><AppTitleBar icon={icon} title="OneBite - Admin" name={actor.name} username={actor.username} syncStatus={syncStatus} pendingCount={pendingCount} disabled={busy} dark={dark} onSync={()=>void refresh()} onProfile={()=>setViewingId(actor.id)} onLanguage={()=>setLang(lang==="km"?"en":"km")} onTheme={()=>setDark(value=>!value)} onSignOut={()=>void logout()}/>
  {mode==="preview"&&<div className="access-preview-bar"><span><AlertCircle size={16}/>{t("សាកល្បងក្នុងឧបករណ៍ · មិនមែនគណនីពិត","Local preview · These are not real accounts")}</span><label>{t("មើលជា","View as")}<SelectField aria-label="Preview identity" value={actorId} onChange={e=>{setActorId(e.target.value);setTab("users");setEditing(null);setAssigning(null);setEditRole(null);setNewRole(null);setResetUser(null);setViewingId(null);setError("");}}>{state.users.filter(u=>u.active).map(u=><option key={u.id} value={u.id}>{u.name} · {u.role}</option>)}</SelectField></label></div>}
  <main className={`access-main ${tab==="users"?"access-users-page":""}`}><PageHeading
    title={tab==="users"?t("អ្នកប្រើ","Users"):tab==="roles"?t("តួនាទី","Roles"):tab==="permissions"?t("សិទ្ធិក្នុងការប្រើប្រាស់","Permissions"):t("ប្រវត្តិការផ្លាស់ប្ដូរ","Activity log")}
    subtitle={tab==="users"?t("គ្រប់គ្រងក្រុម និងគណនីអ្នកប្រើរបស់អ្នក។","Manage your team and account access."):tab==="roles"?t("ពិនិត្យតួនាទី និងម៉ូឌុលដែលអាចប្រើបាន។","Review each role and its allowed modules."):tab==="permissions"?t("គ្រប់គ្រងការចូលប្រើម៉ូឌុល និងសកម្មភាពតាមតួនាទី។","Control module access and actions for each role."):t("តាមដានការផ្លាស់ប្ដូរគណនី តួនាទី និងសិទ្ធិ។","Track account, role, and permission changes.")}
    action={tab==="users"&&owner?<button type="button" className="access-btn access-create-user" aria-label={t("បង្កើតអ្នកប្រើថ្មី","Create new user")} title={t("បង្កើតអ្នកប្រើថ្មី","Create new user")} onClick={createUser}><Plus size={22}/></button>:tab==="roles"&&manageRoles?<button type="button" className="access-btn access-create-user" disabled={!policyReady} aria-label={t("បង្កើតតួនាទីថ្មី","Create new role")} title={t("បង្កើតតួនាទីថ្មី","Create new role")} onClick={()=>{setNewRole({id:`role_${crypto.randomUUID()}`,name:"",description:""});setError("");}}><Plus size={22}/></button>:undefined}
  />
  {error&&<div className="access-error" role="alert"><AlertCircle size={18}/>{error}<button className="access-text" onClick={()=>setError("")}>{t("បិទ","Dismiss")}</button></div>}
  {tab==="users"&&<><div className="access-directory-tools"><label className="access-search"><Search size={18}/><input aria-label={t("ស្វែងរកអ្នកប្រើ","Search users")} placeholder={t("ស្វែងរកឈ្មោះ ឬឈ្មោះអ្នកប្រើ","Search name or username…")} value={search} onChange={e=>setSearch(e.target.value)}/></label><SelectField aria-label={t("តម្រងស្ថានភាព","Filter status")} value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="active">{t("ដំណើរការតែប៉ុណ្ណោះ","Active only")}</option><option value="inactive">{t("ផ្អាកតែប៉ុណ្ណោះ","Inactive only")}</option><option value="all">{t("ទាំងអស់","All")}</option></SelectField></div>
   <div className="access-role-selector" role="group" aria-label={t("តម្រងតួនាទី","Filter role")}>{["all",...roles].map(r=><button key={r} type="button" aria-pressed={roleFilter===r} onClick={()=>setRoleFilter(r)}>{r==="all"?t("គ្រប់តួនាទី","All roles"):roleName(r as Role)}</button>)}</div>
   <div className="access-user-groups">{roles.map(r=>{const people=filtered.filter(u=>u.role===r).sort((a,b)=>nameOrder.compare(a.name,b.name)||nameOrder.compare(a.username,b.username));if(!people.length)return null;return <section className="access-user-group" key={r} aria-label={roleName(r)}><div className="access-group-heading"><h2>{roleName(r)}</h2><span>{people.length}</span></div><div className="access-user-list">{people.map(u=><button type="button" className="access-user-row" key={u.id} aria-label={`${t("មើលព័ត៌មាន","View")} ${u.name} (@${u.username})`} onClick={()=>{setViewingId(u.id);setError("");}}><span className="access-person"><span className={`access-avatar ${u.role.toLowerCase()}`}>{u.name[0]}</span><span><strong>{u.name}</strong><small>@{u.username}</small></span></span><span className={`access-status ${u.active?"active":"inactive"}`}><i/>{u.active?t("ដំណើរការ","Active"):t("ផ្អាក","Inactive")}</span><ChevronRight size={18} className="access-user-chevron"/></button>)}</div></section>;})}{!filtered.length&&<EmptyState className="access-empty" icon={<Users size={30}/>} title={userFiltersActive?t("រកមិនឃើញអ្នកប្រើ","No matching users"):t("ចាប់ផ្ដើមបង្កើតក្រុមរបស់អ្នក","Build your OneBite team")} body={userFiltersActive?t("សូមសម្អាតតម្រងដើម្បីមើលអ្នកប្រើផ្សេងទៀត។","Clear your filters to see other team members."):owner?t("បង្កើតគណនីដំបូង ដើម្បីឱ្យក្រុមរបស់អ្នកចាប់ផ្ដើមការងារ។","Create the first staff account to get your team started."):t("អ្នកប្រើដែលអ្នកអាចមើលបាននឹងបង្ហាញនៅទីនេះ។","Team members you can access will appear here.")} action={userCreateAction} secondaryAction={userFiltersActive?{label:t("សម្អាតតម្រង","Clear filters"),onClick:clearUserFilters}:undefined}/>}</div></>}
  {tab==="roles"&&<div className="access-role-list">{roles.map(role=><RoleRow key={role} role={role} state={state} onReview={()=>{setEditRole(role);setError("");}}/>)}</div>}
  {tab==="permissions"&&<><div className="access-rule-note"><LockKeyhole size={20}/><p>{t("ត្រូវអនុញ្ញាតទាំងម៉ូឌុល និងសកម្មភាព។ ការសងប្រាក់ និងការរំលងកម្រិតត្រូវហាមគ្រប់តួនាទី។","Module access and action permission are both required. Greyed-out permissions are unavailable. Refunds and discount overrides remain forbidden.")}</p></div><div className="access-permission-groups grid gap-6">{moduleDefinitions.map(m=><section className="access-permission-module" key={m.id}><h2>{t(m.km,m.en)}</h2><div className="access-permission-matrix" style={{"--role-count":roles.length} as CSSProperties}><div className="access-matrix-row access-matrix-head"><span>{t("សិទ្ធិ","Permission")}</span>{roles.map(r=><span key={r}>{roleName(r)}</span>)}</div>{[m,...permissionDefinitions.filter(p=>p.group===m.group&&p.id!==m.id),...(m.group==="POS"?permissionDefinitions.filter(p=>p.group==="Never"):[])].map(p=><div className={`access-matrix-row ${p.id===m.id?"access-module-row":""}`} key={p.id}><div><strong>{p.id===m.id?t("ចូលប្រើម៉ូឌុល","Module access"):t(p.km,p.en)}</strong><small>{p.id===m.id?t("អនុញ្ញាត / បដិសេធ","Allow / Deny"):p.group==="Never"?t("ហាមជានិច្ច","Always forbidden"):t("សកម្មភាព","Action")}</small></div>{roles.map(r=>{const allowed=hasPermission(state.grants[r],r,p.id);return <span key={r} className={allowed?"allowed":"denied"} aria-label={`${roleName(r)}: ${allowed?"allowed":"denied"}`}>{allowed?<Check size={18}/>:<X size={17}/>}</span>;})}</div>)}</div>{!permissionDefinitions.some(p=>p.group===m.group&&p.id!==m.id)&&<p className="access-helper">{t("សកម្មភាពលម្អិតនឹងបន្ថែមពេលបង្កើតម៉ូឌុលនេះ។","Action permissions will be added when this module is built.")}</p>}</section>)}</div></>}
  {tab==="activity"&&owner&&<div className="access-activity">{state.events.length?[...state.events].reverse().map(e=><div key={e.id}><span className="access-avatar"><History size={18}/></span><div><strong>{e.targetName}</strong><p>{e.action} · {e.actorName}</p><small>{e.detail}</small></div><time>{new Intl.DateTimeFormat(lang==="km"?"km-KH":"en-GB",{timeZone:"Asia/Phnom_Penh",dateStyle:"short",timeStyle:"short"}).format(new Date(e.time))}</time></div>):<EmptyState className="access-empty" icon={<History size={30}/>} title={t("មិនទាន់មានការផ្លាស់ប្ដូរ","No changes yet")} body={t("ការផ្លាស់ប្ដូរគណនី និងសិទ្ធិនឹងបង្ហាញនៅទីនេះ។ ចាប់ផ្ដើមដោយបន្ថែមសមាជិកក្រុម។","Account and permission changes will appear here. Start by adding a team member.")} action={userCreateAction}/>}</div>}
  </main><nav className="access-bottom-nav">{nav.filter(n=>n.id!=="activity"||owner).map(n=><button className={tab===n.id?"active":""} key={n.id} onClick={()=>setTab(n.id)}><n.icon size={21}/><span>{n.label}</span></button>)}</nav></div>
  {details&&<Modal title={t("ព័ត៌មានអ្នកប្រើ","User details")} onClose={()=>setViewingId(null)}><div className="access-user-detail"><div className="access-detail-identity"><span className={`access-avatar ${details.role.toLowerCase()}`}>{details.name[0]}</span><h3>{details.name}</h3><p>@{details.username}</p></div><dl><div><dt>{t("តួនាទី","Role")}</dt><dd><span className={`access-role ${details.role.toLowerCase()}`}>{roleName(details.role)}</span></dd></div><div><dt>{t("ស្ថានភាព","Status")}</dt><dd><span className={`access-status ${details.active?"active":"inactive"}`}><i/>{details.active?t("ដំណើរការ","Active"):t("ផ្អាក","Inactive")}</span></dd></div><div><dt>{t("សាខាដែលបានចាត់តាំង","Assigned sites")}</dt><dd>{details.role==="Owner"?t("គ្រប់សាខា","All sites"):details.sites.length?details.sites.map(id=>state.sites.find(site=>site.id===id)?.name).filter(Boolean).join(", "):t("គ្មានសាខា","No sites")}</dd></div></dl><div className="access-detail-actions">{owner&&(details.role!=="Owner"||actor.role==="Owner")&&<button className="access-btn" onClick={()=>{setViewingId(null);setCreating(false);setEditing(details);setError("");}}><Pencil size={17}/>{t("កែប្រែ","Edit")}</button>}{canAssign&&details.role!=="Owner"&&(actor.role==="Owner"||details.role!=="Owner"&&details.sites.some(id=>actor.sites.includes(id)))&&<button className="access-btn secondary" onClick={()=>{setViewingId(null);setAssigning(details);setError("");}}><Store size={17}/>{t("ចាត់តាំងសាខា","Assign sites")}</button>}{owner&&(details.role!=="Owner"||actor.role==="Owner")&&<button className="access-btn secondary" disabled={mode==="preview"} onClick={()=>{setViewingId(null);setResetUser(details);setError("");}}><KeyRound size={17}/>{t("កំណត់ PIN ឡើងវិញ","Reset PIN")}</button>}</div></div></Modal>}
  {editing&&<UserEditor key={editorVersion} recovery={recovery} account={editing} creating={creating} state={state} actor={actor} live={mode==="live"} busy={busy} error={error} onClose={()=>{setEditing(null);setError("");}} onSave={async (account,pin)=>{const success=await mutate(creating?"user.create":"user.update",{...account,...(pin?{pin}:{})},s=>saveAccount(s,actor.id,account,creating));if(success)setEditing(null);}}/>}
  {assigning&&<SiteAssignment key={editorVersion} account={assigning} state={state} actor={actor} busy={busy} error={error} recovery={recovery} onClose={()=>{if(!busy){setAssigning(null);setError("");}}} onSave={async sites=>{if(await mutate("sites.assign",{id:assigning.id,sites},s=>assignSites(s,actor.id,assigning.id,sites)))setAssigning(null);}}/>}
  {editRole&&<RoleEditor key={editorVersion} recovery={recovery} role={editRole} state={state} legacy={!policyReady} editable={manageRoles&&(editRole!=="Owner"||actor.role==="Owner"&&policyReady)} busy={busy} error={error} onClose={()=>{setEditRole(null);setError("");}} onSave={async permissions=>{if(await mutate("permissions.update",{role:editRole,permissions},s=>saveGrants(s,actor.id,editRole,permissions)))setEditRole(null);}}/>}
  {newRole&&<RoleEditor key={newRole.id} role={newRole.id} creating state={state} editable={manageRoles} busy={busy} error={error} onClose={()=>{setNewRole(null);setError("");}} onSave={async (permissions,name,description)=>{const draft={...newRole,name:name||"",description:description||""};if(await mutate("role.create",{...draft,permissions},s=>createRole(s,actor.id,draft,permissions)))setNewRole(null);}}/>}
  {resetUser&&<PinReset key={editorVersion} recovery={recovery} user={resetUser} busy={busy} error={error} onClose={()=>{setResetUser(null);setViewingId(null);setError("");}} onSave={async pin=>{if(await mutate("pin.reset",{id:resetUser.id,pin},s=>s))setResetUser(null);}}/>}
  {toast&&<div className="access-toast" role="status"><Check size={18}/>{toast}</div>}
 </div>;
}
function AuthForm({mode,busy,error,onSubmit}:{mode:Mode;busy:boolean;error:string;onSubmit:(payload:Record<string,unknown>)=>Promise<void>}){
 const {t}=useLanguage();const [name,setName]=useState(""),[username,setUsername]=useState(""),[pin,setPin]=useState(""),[confirmation,setConfirmation]=useState(""),[code,setCode]=useState(""),[current,setCurrent]=useState("");
 const setup=mode==="setup",change=mode==="change-pin";const valid=/^[0-9]{6}$/.test(pin)&&(!setup&&!change||pin===confirmation)&&(!setup||(name.trim()&&/^[a-f0-9]{64}$/.test(code)))&&(!change||/^[0-9]{6}$/.test(current));
 return <form className="access-form" onSubmit={e=>{e.preventDefault();if(valid&&!busy)void onSubmit({...(!change?{username}:{}),pin,...(setup?{name,setup_code:code}:{}),...(change?{current_pin:current}:{})});}}><h1>{setup?t("បង្កើតគណនីម្ចាស់","Set up the first Owner"):change?t("ប្ដូរ PIN របស់អ្នក","Choose your own PIN"):t("សូមស្វាគមន៍","Welcome back")}</h1><p>{setup?t("ប្រើកូដបង្កើតម្ចាស់មួយដង ដើម្បីការពារគណនីដំបូង។","Use your one-time setup code to protect the first Owner account."):change?t("អ្នកត្រូវប្ដូរ PIN បណ្ដោះអាសន្ន មុនបន្ត។","Change your temporary PIN before continuing."):t("ចូលគណនីផ្ទាល់ខ្លួន ដោយឈ្មោះអ្នកប្រើ និង PIN។","Sign in with your individual username and PIN.")}</p>{setup&&<><label>{t("កូដបង្កើតម្ចាស់","One-time setup code")}<input value={code} type="password" autoComplete="off" onChange={e=>setCode(e.target.value.trim())}/></label><label>{t("ឈ្មោះពេញ","Full name")}<input maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label></>}{!change&&<label>{t("ឈ្មោះអ្នកប្រើ","Username")}<input autoComplete="username" autoCapitalize="none" autoCorrect="off" value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} required/></label>}{change&&<label>{t("PIN បច្ចុប្បន្ន","Current PIN")}<input type="password" inputMode="numeric" maxLength={6} value={current} onChange={e=>setCurrent(e.target.value.replace(/\D/g,""))}/></label>}<label>{change?t("PIN ថ្មី 6 ខ្ទង់","New 6-digit PIN"):t("លេខ PIN 6 ខ្ទង់","6-digit PIN")}<input type="password" autoComplete={setup||change?"new-password":"current-password"} inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))}/></label>{(setup||change)&&<label>{t("បញ្ជាក់ PIN","Confirm PIN")}<input type="password" autoComplete="new-password" inputMode="numeric" maxLength={6} value={confirmation} onChange={e=>setConfirmation(e.target.value.replace(/\D/g,""))}/></label>}{error&&<div className="access-error" role="alert">{error}</div>}<button className="access-btn" disabled={!valid||busy}>{busy?t("កំពុងដំណើរការ…","Working…"):setup?t("បង្កើតម្ចាស់","Create Owner"):change?t("រក្សាទុក PIN ថ្មី","Save new PIN"):t("ចូលគណនី","Sign in")}</button></form>;
}
function generateTemporaryPin(previous = ""): string {
 const range=1_000_000, limit=Math.floor(0x1_0000_0000/range)*range;
 let pin: string;
 do { let value: number; do {value=crypto.getRandomValues(new Uint32Array(1))[0];} while(value>=limit);pin=String(value%range).padStart(6,"0"); } while(pin===previous);
 return pin;
}
function UserEditor({account,creating,state,actor,live,busy,error,recovery,onClose,onSave}:{account:Account;creating:boolean;state:AccessState;actor:Account;live:boolean;busy:boolean;error:string;recovery?:ReactNode;onClose:()=>void;onSave:(account:Account,pin:string)=>Promise<void>}){
 const roles=roleIds(state);
 const {t}=useLanguage();const [draft,setDraft]=useState({...account,sites:[...account.sites]}),[pin,setPin]=useState(()=>creating?generateTemporaryPin():""),[selectedRole,setSelectedRole]=useState<Role|"">(creating?"":account.role),[copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false);const all=can(state,actor,"users.manage"),duplicate=state.users.some(u=>u.id!==draft.id&&u.username.toLowerCase()===draft.username.trim().toLowerCase()),lastOwner=account.active&&account.role==="Owner"&&state.users.filter(u=>u.role==="Owner"&&u.active).length===1;
 const update=(data:Partial<Account>)=>setDraft(old=>({...old,...data}));const usernameValid=/^[a-z0-9][a-z0-9_.-]{2,31}$/.test(draft.username.trim().toLowerCase());const valid=(!all||draft.name.trim()&&usernameValid&&!duplicate)&&(!creating||selectedRole!==""&&/^[0-9]{6}$/.test(pin));
 async function copyPin(){setCopyError(false);try{await navigator.clipboard.writeText(pin);setCopied(true);}catch{setCopied(false);setCopyError(true);}}
 return <Modal title={creating?t("បង្កើតអ្នកប្រើថ្មី","Create new user"):all?t("កែគណនី","Edit account"):t("ចាត់បុគ្គលិកទៅសាខា","Assign staff to sites")} onClose={()=>{if(!busy)onClose();}} footer={creating?<button type="submit" form="access-user-editor" className="access-btn" disabled={!valid||busy}><UserPlus size={18}/>{busy?t("កំពុងបង្កើត…","Creating…"):t("បង្កើតអ្នកប្រើ","Create User")}</button>:undefined}><form id="access-user-editor" className="access-form" onSubmit={e=>{e.preventDefault();if(valid&&!busy)void onSave(creating?{...draft,role:selectedRole as Role,active:true,sites:[]}:draft,pin);}}>{all&&<><label>{t("ឈ្មោះពេញ","Full name")}<input maxLength={100} value={draft.name} onChange={e=>update({name:e.target.value})} required/></label><label>{t("ឈ្មោះអ្នកប្រើ","Username")}<input aria-label={t("ឈ្មោះអ្នកប្រើ","Username")} autoCapitalize="none" autoCorrect="off" autoComplete="off" maxLength={32} value={draft.username} onChange={e=>update({username:e.target.value.toLowerCase()})} aria-invalid={duplicate}/><small>{t("3–32 តួអក្សរ · a–z, 0–9, _ . -","3–32 characters · a–z, 0–9, _ . -")}</small></label>{duplicate&&<div role="alert" className="access-error">{t("ឈ្មោះអ្នកប្រើនេះមានរួចហើយ","This username is already used.")}</div>}<label>{t("តួនាទី","Role")}<SelectField aria-label={t("តួនាទី","Role")} value={selectedRole} placeholder={t("ជ្រើសរើសតួនាទី","Select a role")} disabled={lastOwner||busy} onChange={e=>{setSelectedRole(e.target.value as Role);update({role:e.target.value as Role});}}>{roles.filter(r=>r!=="Owner"||!creating&&actor.role==="Owner").map(r=><option key={r} value={r}>{roleDisplayName(state,r)}</option>)}</SelectField></label></>}{!all&&<div className="access-editor-person"><UserRound size={22}/><div><strong>{account.name}</strong><small>@{account.username} · {account.role}</small></div></div>}

 {all&&!creating&&<label className="access-checkbox"><CheckField checked={draft.active} disabled={lastOwner} onChange={e=>update({active:e.target.checked})}/>{t("គណនីដំណើរការ","Account active")}</label>}{lastOwner&&<p className="access-helper"><LockKeyhole size={16}/>{t("ម្ចាស់ចុងក្រោយត្រូវបានការពារ។ បន្ថែមម្ចាស់ថ្មីមុនផ្លាស់ប្ដូរ។","The last active Owner is protected. Add another Owner before changing this account.")}</p>}
 {creating&&<div className="access-generated-pin"><label htmlFor="new-user-pin">{t("PIN បណ្ដោះអាសន្ន 6 ខ្ទង់","Temporary 6-digit PIN")}</label><div className="access-pin-value"><input id="new-user-pin" type="text" inputMode="numeric" autoComplete="off" readOnly value={pin} onFocus={e=>e.target.select()}/><button type="button" className="access-icon" aria-label={t("បង្កើត PIN ថ្មី","Regenerate PIN")} title={t("បង្កើត PIN ថ្មី","Regenerate PIN")} disabled={busy} onClick={()=>{setPin(generateTemporaryPin(pin));setCopied(false);setCopyError(false);}}><RefreshCw size={18}/></button><button type="button" className="access-icon" aria-label={t("ចម្លង PIN","Copy PIN")} disabled={busy} onClick={()=>void copyPin()}>{copied?<Check size={18}/>:<Copy size={18}/>}</button></div>{copied&&<small role="status">{t("បានចម្លង PIN","PIN copied")}</small>}{copyError&&<small role="alert">{t("មិនអាចចម្លងបាន។ សូមជ្រើស PIN និងចម្លងដោយដៃ។","Could not copy. Select the PIN and copy it manually.")}</small>}<small>{t("បុគ្គលិកត្រូវប្ដូរ PIN នៅពេលចូលដំបូង។","The person must change this PIN on first sign-in.")}</small></div>}{!live&&<p className="access-helper">{t("សាកល្បងតែព័ត៌មានគណនី · មិនកំណត់ PIN ពិត","Profile preview only · Real PIN setup requires the backend")}</p>}{error&&<div className="access-error" role="alert">{error}{recovery}</div>}{!creating&&<button className="access-btn" disabled={!valid||busy}>{busy?t("កំពុងរក្សាទុក…","Saving…"):t("រក្សាទុក","Save changes")}</button>}</form></Modal>;
}
function SiteAssignment({account,state,actor,busy,error,recovery,onClose,onSave}:{account:Account;state:AccessState;actor:Account;busy:boolean;error:string;recovery?:ReactNode;onClose:()=>void;onSave:(sites:number[])=>Promise<void>}){
 const {t}=useLanguage();const [sites,setSites]=useState([...account.sites]);
 const valid=!account.active||sites.some(id=>state.sites.some(site=>site.id===id&&site.active));
 return <Modal title={t("ចាត់តាំងសាខា","Assign sites")} onClose={onClose} footer={<button className="access-btn" disabled={!valid||busy} onClick={()=>void onSave(sites)}><Store size={18}/>{busy?t("កំពុងរក្សាទុក…","Saving…"):t("រក្សាទុកការចាត់តាំង","Save assignment")}</button>}><div className="access-form"><div className="access-editor-person"><UserRound size={22}/><div><strong>{account.name}</strong><small>@{account.username} · {account.role}</small></div></div><fieldset><legend>{t("សាខាដែលបានចាត់តាំង","Assigned sites")}</legend>{state.sites.map(site=>{const editable=actor.role==="Owner"||actor.sites.includes(site.id)&&site.active;return <label className={`access-site-choice ${sites.includes(site.id)?"selected":""}`} key={site.id}><CheckField checked={sites.includes(site.id)} disabled={!editable||busy} onChange={e=>setSites(old=>e.target.checked?[...old,site.id]:old.filter(id=>id!==site.id))}/><Store size={18}/><span>{site.name}{!editable&&<small>{t("នៅក្រៅសាខារបស់អ្នក · រក្សាដដែល","Outside your scope · Preserved")}</small>}</span>{sites.includes(site.id)&&<Check size={17}/>}</label>;})}</fieldset>{!valid&&<p className="access-helper">{t("គណនីដំណើរការត្រូវមានសាខាមួយយ៉ាងតិច","An active staff account needs at least one active site.")}</p>}{error&&<div className="access-error" role="alert">{error}{recovery}</div>}</div></Modal>;
}
function RoleRow({role,state,onReview}:{role:Role;state:AccessState;onReview:()=>void}){
 const {t}=useLanguage();const [expanded,setExpanded]=useState(false);const id=useId();
 const name=role==="Owner"?t("ម្ចាស់","Owner"):role==="Supervisor"?t("អ្នកត្រួតពិនិត្យ","Supervisor"):role==="Cashier"?t("អ្នកគិតលុយ","Cashier"):roleDisplayName(state,role);
 const description=state.customRoles?.find(r=>r.id===role)?.description || (role==="Owner"?t("គ្រប់គ្រងអាជីវកម្ម និងសិទ្ធិប្រើប្រាស់","Manage the business and access."):role==="Supervisor"?t("ត្រួតពិនិត្យសាខា និងបុគ្គលិក","Oversee sites and staff."):role==="Cashier"?t("ទទួលការបញ្ជាទិញ និងគ្រប់គ្រងវេន","Take orders and manage shifts."):t("សិទ្ធិផ្ទាល់ខ្លួនសម្រាប់ក្រុមរបស់អ្នក","Custom access for your team."));
 const Icon=role==="Owner"?Crown:role==="Supervisor"?ShieldCheck:Users;
 const allowed=moduleDefinitions.filter(module=>hasPermission(state.grants[role]||[],role,module.id));
 return <section className="access-role-row" data-role={role} aria-labelledby={`${id}-name`}>
  <h2 aria-label={name}><button type="button" className="access-role-trigger" aria-expanded={expanded} aria-controls={`${id}-panel`} aria-labelledby={`${id}-name`} aria-describedby={`${id}-description`} onClick={()=>setExpanded(value=>!value)}>
   <span className={`access-role-icon ${role.toLowerCase()}`}><Icon size={22}/></span><span className="access-role-identity"><span id={`${id}-name`} className="access-role-name">{name}</span><span id={`${id}-description`} className="access-role-description">{description}</span></span><ChevronDown size={18} className="access-role-expand"/>
  </button></h2>
  <div id={`${id}-panel`} className="access-role-panel" hidden={!expanded}>
   <p className="access-role-modules-label">{t("ម៉ូឌុលដែលអនុញ្ញាត","Allowed modules")}</p>
   {allowed.length?<ul className="access-role-modules">{allowed.map(module=>{const ModuleIcon=module.id==="pos.access"?ShoppingBag:module.id==="attendance.access"?Clock:module.id==="inventory.access"?Boxes:ShieldCheck;return <li key={module.id}><ModuleIcon size={16}/>{t(module.km,module.en)}</li>;})}</ul>:<p className="access-helper">{t("មិនមានម៉ូឌុលដែលអនុញ្ញាត","No modules allowed")}</p>}
   <button className="access-btn secondary access-role-review" onClick={onReview}><ShieldCheck size={17}/>{t("មើលសិទ្ធិ","Review permissions")}<ArrowUpRight size={16}/></button>
  </div>
 </section>;
}
const permissionRowDetails:Partial<Record<Permission,{en:string;km:string;icon:typeof Users}>>={
 "orders.create":{en:"Receive orders",km:"ទទួលការបញ្ជាទិញ",icon:ShoppingBag},
 "orders.discount":{en:"Discounts",km:"បញ្ចុះតម្លៃ",icon:BadgePercent},
 "orders.complimentary":{en:"Complimentary items",km:"មុខម្ហូបឥតគិតថ្លៃ",icon:Gift},
 "orders.cancel_unpaid":{en:"Cancel unpaid invoices",km:"បោះបង់វិក្កយបត្រមិនទាន់បង់",icon:CircleX},
 "orders.qr_reference":{en:"QR references",km:"រូបយោង QR",icon:QrCode},
 "shifts.manage":{en:"Shifts & cash handover",km:"វេន និងផ្ទេរប្រាក់",icon:ArrowRightLeft},
 "cash.withdraw":{en:"Cash withdrawals",km:"ដកប្រាក់",icon:Banknote},
 "staff.assign":{en:"Assign staff to sites",km:"ចាត់បុគ្គលិកទៅសាខា",icon:Users},
 "users.manage":{en:"User accounts",km:"គណនីបុគ្គលិក",icon:UserRound},
 "roles.manage":{en:"Roles & permissions",km:"តួនាទី និងសិទ្ធិ",icon:ShieldCheck},
 "sites.manage":{en:"Sites",km:"សាខា",icon:MapPin},
 "catalog.manage":{en:"Items & prices",km:"មុខម្ហូប និងតម្លៃ",icon:Utensils},
 "rules.manage":{en:"Promotions & exchange rate",km:"កម្មវិធីបញ្ចុះតម្លៃ និងអត្រាប្ដូរប្រាក់",icon:SlidersHorizontal},
 "orders.override":{en:"Override discount limits",km:"រំលងកម្រិតបញ្ចុះតម្លៃ",icon:LockKeyhole},
 "orders.refund":{en:"Refund paid invoices",km:"សងប្រាក់វិក្កយបត្របង់រួច",icon:LockKeyhole},
};
function RoleEditor({role,creating=false,legacy=false,state,editable,busy,error,recovery,onClose,onSave}:{role:Role;creating?:boolean;legacy?:boolean;state:AccessState;editable:boolean;busy:boolean;error:string;recovery?:ReactNode;onClose:()=>void;onSave:(permissions:Permission[],name?:string,description?:string)=>Promise<void>}){
 const {t}=useLanguage();const [grants,setGrants]=useState([...(state.grants[role]||[])]);
 const [name,setName]=useState(""),[description,setDescription]=useState("");
 const duplicate=creating&&roleIds(state).some(id=>roleDisplayName(state,id).toLowerCase()===name.trim().toLowerCase());
 const valid=!creating||!!name.trim()&&!duplicate;
 const toggle=(permission:Permission,checked:boolean)=>setGrants(old=>checked?[...old,permission]:old.filter(id=>id!==permission));
 return <Modal title={creating?t("បង្កើតតួនាទីថ្មី","Create new role"):`${roleDisplayName(state,role)} · ${t("សិទ្ធិ","Permissions")}`} onClose={()=>{if(!busy)onClose();}} footer={editable?<button className="access-btn" onClick={()=>void onSave(grants,name.trim(),description.trim())} disabled={busy||!valid}><Check size={18}/>{busy?t("កំពុងរក្សាទុក…","Saving…"):creating?t("បង្កើតតួនាទី","Create Role"):t("រក្សាទុកសិទ្ធិ","Save permissions")}</button>:undefined}>
  {creating&&<div className="access-form access-new-role-fields"><label>{t("ឈ្មោះតួនាទី","Role name")}<input value={name} maxLength={60} required onChange={e=>setName(e.target.value)} aria-invalid={duplicate}/></label><label>{t("ការពិពណ៌នាខ្លី","Short description")}<input value={description} maxLength={160} onChange={e=>setDescription(e.target.value)}/></label>{duplicate&&<p role="alert" className="access-error">{t("ឈ្មោះតួនាទីនេះមានរួចហើយ","This role name is already used.")}</p>}</div>}
  {role==="Owner"&&<p className="access-helper access-policy-hint"><LockKeyhole size={16}/>{t("សិទ្ធិម្ចាស់ត្រូវបានការពារ។","Account and role administration stay enabled so Owners can manage access.")}</p>}
  <div className="access-policy-sections">{moduleDefinitions.map(module=>{
   const available=permissionAvailable(module.id)&&(!legacy||!!ceilings[role]?.includes(module.id)),required=role==="Owner"&&ownerRequiredPermissions.includes(module.id);
   const access=available&&grants.includes(module.id);
   const actions=[...permissionDefinitions.filter(permission=>permission.group===module.group&&permission.id!==module.id),...(module.group==="POS"?permissionDefinitions.filter(permission=>permission.group==="Never"):[])];
   return <section className={`access-policy-section ${available?"":"unavailable"}`} key={module.id} aria-label={t(module.km,module.en)}>
    <header className="access-policy-header"><h3>{t(module.km,module.en)}{!available&&<small>{t("មិនទាន់មាន","Not available yet")}</small>}</h3><label className="access-policy-module-toggle"><span className={access?"allowed":"denied"}>{access?t("អនុញ្ញាត","Allowed"):t("បដិសេធ","Denied")}</span><SwitchField aria-label={t(`ចូលប្រើម៉ូឌុល ${module.km}`,`Access ${module.en} module`)} checked={access} disabled={!editable||!available||required||busy} onChange={event=>toggle(module.id,event.target.checked)}/></label></header>
    {access&&actions.length>0&&<ul className="access-policy-actions">{actions.map(permission=>{
     const allowed=permissionAvailable(permission.id)&&(!legacy||!!ceilings[role]?.includes(permission.id)),required=role==="Owner"&&ownerRequiredPermissions.includes(permission.id),details=permissionRowDetails[permission.id],Icon=details?.icon||KeyRound;
     return <li key={permission.id} className={allowed?"":"locked"}><label title={!allowed?t("មិនទាន់មាន ឬហាមតាមច្បាប់អាជីវកម្ម","Not available yet or forbidden by business rules"):undefined}><Icon size={18}/><span>{details?t(details.km,details.en):t(permission.km,permission.en)}</span><SwitchField aria-label={t(permission.km,permission.en)} aria-description={!allowed?t("មិនទាន់មាន ឬហាមតាមច្បាប់អាជីវកម្ម","Not available yet or forbidden by business rules"):undefined} checked={allowed&&grants.includes(permission.id)} disabled={!editable||!allowed||required||busy} onChange={event=>toggle(permission.id,event.target.checked)}/></label></li>;
    })}</ul>}
   </section>;
  })}</div>
  {editable&&<p className="access-helper access-policy-hint">{t("បដិសេធម៉ូឌុលនឹងរក្សាការកំណត់សិទ្ធិដដែល។","Denying a module preserves its permission settings.")}</p>}
  {error&&<div className="access-error" role="alert">{error}{recovery}</div>}
 </Modal>;
}
function PinReset({user,busy,error,recovery,onClose,onSave}:{user:Account;busy:boolean;error:string;recovery?:ReactNode;onClose:()=>void;onSave:(pin:string)=>Promise<void>}){const {t}=useLanguage();const[pin,setPin]=useState(""),[confirm,setConfirm]=useState("");return <Modal title={t("កំណត់ PIN ឡើងវិញ","Reset PIN")} onClose={()=>{if(!busy)onClose();}}><form className="access-form" onSubmit={e=>{e.preventDefault();if(/^[0-9]{6}$/.test(pin)&&pin===confirm&&!busy)void onSave(pin);}}><p>{user.name} · @{user.username}</p><div className="access-rule-note"><LockKeyhole size={19}/>{t("បិទគ្រប់សម័យចូលប្រើ។ បុគ្គលិកត្រូវប្ដូរ PIN បណ្ដោះអាសន្ន។","All sessions will be revoked. The person must change the temporary PIN.")}</div><label>{t("PIN បណ្ដោះអាសន្នថ្មី","New temporary PIN")}<input type="password" autoComplete="new-password" inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))}/></label><label>{t("បញ្ជាក់ PIN","Confirm PIN")}<input type="password" autoComplete="new-password" inputMode="numeric" maxLength={6} value={confirm} onChange={e=>setConfirm(e.target.value.replace(/\D/g,""))}/></label>{error&&<div className="access-error" role="alert">{error}{recovery}</div>}<button className="access-btn" disabled={busy||!/^[0-9]{6}$/.test(pin)||pin!==confirm}>{t("កំណត់ PIN និងបិទសម័យចូលប្រើ","Reset PIN and revoke sessions")}</button></form></Modal>;}
