import {useState} from 'react';
import {ShieldCheck,Copy,KeyRound} from 'lucide-react';
import {useLanguage} from '@onebite/ui';
import {accessApi,type AccessReply} from './access-api';
export function MfaChallenge({session,enrollment,onVerified,onCancel}:{session:string;enrollment:boolean;onVerified:(reply:AccessReply)=>void;onCancel:()=>void}){
 const {t}=useLanguage();const [secret,setSecret]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[verified,setVerified]=useState<AccessReply|null>(null),[copied,setCopied]=useState(false);
 async function enroll(){setBusy(true);setError('');try{const reply=await accessApi('mfa.enroll',{},session);setSecret(reply.secret||'');}catch{setError(t('មិនអាចបង្កើតលេខកូដបាន។ សូមព្យាយាមម្ដងទៀត។','Could not set up the authenticator. Please retry.'));}finally{setBusy(false);}}
 async function verify(){setBusy(true);setError('');try{const reply=await accessApi('mfa.verify',{code:code.trim().toLowerCase()},session);setCode('');if(reply.recoveryCodes?.length)setVerified(reply);else onVerified(reply);}catch{setCode('');setError(t('លេខកូដមិនត្រឹមត្រូវ ឬបានប្រើរួច។ សូមប្រើលេខកូដថ្មី។','Code is incorrect, expired or already used. Try a fresh code; repeated failures require a pause.'));}finally{setBusy(false);}}
 if(verified)return <div className="access-form"><KeyRound size={32}/><h1>{t('រក្សាទុកលេខកូដសង្គ្រោះ','Save your recovery codes')}</h1><p>{t('រក្សាទុកនៅកន្លែងមានសុវត្ថិភាព។ លេខកូដនីមួយៗប្រើបានម្ដង។','Store these securely, separate from this device. Each code works once if you lose your authenticator. They will not be shown again.')}</p><pre className="mfa-recovery">{verified.recoveryCodes!.join('\n')}</pre><button type="button" className="d-btn d-btn-outline" onClick={async()=>{try{await navigator.clipboard.writeText(verified.recoveryCodes!.join('\n'));setCopied(true);}catch{setError(t('សូមចម្លងលេខកូដដោយខ្លួនឯង។','Select and copy the codes manually.'));}}}><Copy size={18}/>{copied?t('បានចម្លង','Copied'):t('ចម្លងលេខកូដ','Copy codes')}</button>{error&&<p role="alert">{error}</p>}<button className="d-btn d-btn-primary" onClick={()=>onVerified(verified)}>{t('បានរក្សាទុក។ បន្ត','I saved my codes. Continue')}</button></div>;
 return <form className="access-form" onSubmit={e=>{e.preventDefault();void verify();}}><ShieldCheck size={32}/><h1>{enrollment?t('ការពារគណនីរបស់អ្នក','Protect your account'):t('បញ្ជាក់អត្តសញ្ញាណ','Verify your identity')}</h1><p>{enrollment?t('បន្ថែម OneBite ទៅកម្មវិធី Authenticator របស់អ្នក ដោយប្រើលេខសម្ងាត់ខាងក្រោម។','Add OneBite to Google Authenticator, Microsoft Authenticator or another authenticator using the setup key below. Choose a time-based, six-digit code.'):t('បញ្ចូលលេខកូដពីកម្មវិធី Authenticator ឬលេខកូដសង្គ្រោះ។','Enter a fresh authenticator code or one unused recovery code.')}</p>{enrollment&&!secret&&<button type="button" className="d-btn d-btn-primary" disabled={busy} onClick={()=>void enroll()}>{t('បង្កើតលេខសម្ងាត់','Generate setup key')}</button>}{secret&&<label>{t('លេខសម្ងាត់សម្រាប់ដំឡើង','Setup key')}<input className="d-input" readOnly value={secret} autoComplete="off"/><button type="button" className="d-btn d-btn-outline" onClick={()=>void navigator.clipboard.writeText(secret).catch(()=>setError(t('សូមចម្លងដោយខ្លួនឯង។','Select and copy the key manually.')))}><Copy size={18}/>{t('ចម្លង','Copy')}</button></label>}{(!enrollment||secret)&&<><label>{t('លេខកូដបញ្ជាក់','Verification code')}<input className="d-input" type="password" autoComplete="one-time-code" maxLength={16} value={code} onChange={e=>setCode(e.target.value.replace(/\s/g,''))} autoFocus required/></label><button className="d-btn d-btn-primary" disabled={busy||!/^([0-9]{6}|[a-fA-F0-9]{16})$/.test(code)}>{busy?t('កំពុងពិនិត្យ…','Checking…'):t('បញ្ជាក់','Verify')}</button></>}{error&&<div className="d-alert d-alert-error" role="alert">{error}</div>}<button type="button" className="d-btn d-btn-ghost" disabled={busy} onClick={onCancel}>{t('បោះបង់ និងចាកចេញ','Cancel and sign out')}</button></form>;
}
