import { useId, useState, type ReactNode } from 'react';
import { Store, MapPin, Plus, Check, Clock, CalendarDays, Pencil, LocateFixed } from 'lucide-react';
import { useLanguage, EmptyState, AppDialog, SwitchField, CheckField } from '@onebite/ui';
import { normalizeSite, siteDraft, type AccessSite, type SiteDraft } from '@onebite/core/access';

export function SiteDirectory({sites,onCreate,onEdit}:{sites:AccessSite[];onCreate:()=>void;onEdit:(site:AccessSite)=>void}){
 const {t,lang}=useLanguage();const order=new Intl.Collator(lang==='km'?'km-KH':'en',{sensitivity:'base',numeric:true});
 return sites.length?<div className="access-sites-list">{[...sites].sort((a,b)=>order.compare(a.name,b.name)).map(site=><button className="d-card access-site-row" key={site.id} onClick={()=>onEdit(site)} aria-label={`${t('កែប្រែសាខា','Edit site')} ${site.name}`}><span className="access-site-photo"><span className="access-site-photo-placeholder" aria-label={t('មិនទាន់មានរូបថតសាខា','No site photo added')}><Store size={42} strokeWidth={1.3}/></span><span className={`d-badge d-badge-soft access-status ${site.active?'active':'inactive'}`}><i/>{site.active?t('ដំណើរការ','Active'):t('ផ្អាក','Inactive')}</span></span><span className="access-site-copy"><strong>{site.name}</strong><small><MapPin size={15}/>{site.location||t('មិនទាន់មានទីតាំង','Location not added yet')}</small></span></button>)}</div>:<EmptyState icon={<Store size={30}/>} title={t('បង្កើតសាខា OneBite ដំបូង','Give OneBite a place to grow')} body={t('បន្ថែមទីតាំងដំបូង និងព័ត៌មានប្រតិបត្តិការ។','Add your first location and its operating details.')} action={{label:t('បង្កើតសាខាថ្មី','New Site'),icon:<Plus size={18}/>,onClick:onCreate}}/>;
}

export function SiteEditor({site,creating,busy,error,recovery,onClose,onSave}:{site:AccessSite;creating:boolean;busy:boolean;error:string;recovery?:ReactNode;onClose:()=>void;onSave:(site:SiteDraft)=>Promise<void>}){
 const {t}=useLanguage();const [draft,setDraft]=useState(()=>siteDraft(site));const formId=useId();
 const [locating,setLocating]=useState(false),[locationMessage,setLocationMessage]=useState(''),[locationError,setLocationError]=useState(false);
 function useCurrentLocation(){
  setLocationMessage('');setLocationError(false);
  if(!navigator.geolocation){setLocationError(true);setLocationMessage(t('ឧបករណ៍នេះមិនគាំទ្រទីតាំង','Location is not supported on this device.'));return;}
  setLocating(true);
  navigator.geolocation.getCurrentPosition(position=>{setDraft(old=>({...old,latitude:Number(position.coords.latitude.toFixed(6)),longitude:Number(position.coords.longitude.toFixed(6))}));setLocating(false);setLocationMessage(t('បានបញ្ចូលទីតាំងបច្ចុប្បន្ន','Current location added.'));},error=>{setLocating(false);setLocationError(true);setLocationMessage(error.code===1?t('សូមអនុញ្ញាតទីតាំងក្នុងការកំណត់កម្មវិធីរុករក ឬបញ្ចូលដោយដៃ','Location access was denied. Allow it in browser settings or enter coordinates manually.'):error.code===3?t('ការស្វែងរកទីតាំងបានហួសពេល។ សូមព្យាយាមម្ដងទៀត។','Location timed out. Please try again.'):t('មិនអាចរកទីតាំងបាន។ សូមព្យាយាមម្ដងទៀត ឬបញ្ចូលដោយដៃ។','Could not find your location. Try again or enter coordinates manually.'));},{enableHighAccuracy:true,timeout:15000,maximumAge:60000});
 }
 const update=(patch:Partial<SiteDraft>)=>setDraft(old=>({...old,...patch}));
 let valid=true;try{normalizeSite(draft);}catch{valid=false;}
 const days=[t('ចន្ទ','Monday'),t('អង្គារ','Tuesday'),t('ពុធ','Wednesday'),t('ព្រហស្បតិ៍','Thursday'),t('សុក្រ','Friday'),t('សៅរ៍','Saturday'),t('អាទិត្យ','Sunday')];
 const changeHours=(day:number,patch:{opens?:string;closes?:string})=>update({workingHours:draft.workingHours.map(h=>h.day===day?{...h,...patch}:h)});
 return <AppDialog title={creating?t('បង្កើតសាខាថ្មី','New Site'):t('កែប្រែសាខា','Edit site')} onClose={()=>{if(!busy)onClose();}} footer={<button form={formId} type="submit" className="d-btn d-btn-primary access-btn" disabled={busy||locating||!valid}>{creating?<Plus size={18}/>:<Check size={18}/>} {busy?t('កំពុងរក្សាទុក…','Saving…'):creating?t('បង្កើតសាខា','Create Site'):t('រក្សាទុក','Save changes')}</button>}>
  <form id={formId} className="access-form access-site-form" onSubmit={e=>{e.preventDefault();if(valid&&!busy&&!locating)void onSave(draft);}}>
   <section className="access-site-section"><h3><MapPin size={18}/>{t('ព័ត៌មានសាខា','Site information')}</h3>
    <label>{t('ឈ្មោះ','Name')}<input className="d-input" required maxLength={100} value={draft.name} onChange={e=>update({name:e.target.value})}/></label>
    <label>{t('ទីតាំង','Location')}<input className="d-input" required maxLength={500} placeholder={t('អាសយដ្ឋាន ឬទីសម្គាល់','Address or landmark')} value={draft.location} onChange={e=>update({location:e.target.value})}/></label>
    <button type="button" className="d-btn d-btn-outline access-btn secondary" disabled={busy||locating} onClick={useCurrentLocation}><LocateFixed size={18}/>{locating?t('កំពុងរកទីតាំង…','Getting location…'):t('ប្រើទីតាំងបច្ចុប្បន្នរបស់ខ្ញុំ','Use my current location')}</button>
    <p className="access-helper">{t('រយៈទទឹង និងរយៈបណ្ដោយគឺស្រេចចិត្ត។ បញ្ចូលទាំងពីរ ឬទុកទទេទាំងពីរ។','Coordinates are optional. Enter both or leave both blank.')}</p>
    {locationMessage&&<p className={locationError?'access-error':'access-helper'} role={locationError?'alert':'status'}>{locationMessage}</p>}
    <div className="access-site-coordinates"><label>{t('រយៈទទឹង','Latitude')}<input className="d-input" type="number" inputMode="decimal" step="any" min={-90} max={90} value={draft.latitude??''} onChange={e=>update({latitude:e.target.value===''?null:Number(e.target.value)})}/></label><label>{t('រយៈបណ្ដោយ','Longitude')}<input className="d-input" type="number" inputMode="decimal" step="any" min={-180} max={180} value={draft.longitude??''} onChange={e=>update({longitude:e.target.value===''?null:Number(e.target.value)})}/></label></div>
   </section>
   <section className="access-site-section"><h3><Clock size={18}/>{t('ថ្ងៃ និងម៉ោងធ្វើការ','Working days / hours')}<small>{t('ស្រេចចិត្ត','Optional')}</small></h3><p className="access-helper">{t('ជ្រើសថ្ងៃដែលបើក។ ម៉ោងបិទមុនម៉ោងបើកមានន័យថាបិទថ្ងៃបន្ទាប់។','Select operating days. A closing time before opening means the next day.')}</p><div className="access-working-days">{days.map((label,day)=>{const hours=draft.workingHours.find(h=>h.day===day);return <div className={`access-working-day ${hours?'enabled':''}`} key={day}><label className="access-day-toggle"><CheckField checked={!!hours} disabled={busy} onChange={e=>update({workingHours:e.target.checked?[...draft.workingHours,{day,opens:'16:00',closes:'22:00'}]:draft.workingHours.filter(h=>h.day!==day)})}/>{label}</label>{hours?<div className="access-day-times"><input className="d-input" type="time" aria-label={`${label} ${t('បើក','opening')}`} required value={hours.opens} onChange={e=>changeHours(day,{opens:e.target.value})}/><span>–</span><input className="d-input" type="time" aria-label={`${label} ${t('បិទ','closing')}`} required value={hours.closes} onChange={e=>changeHours(day,{closes:e.target.value})}/></div>:<small>{t('មិនបានកំណត់','Not set')}</small>}</div>;})}</div></section>
   <section className="access-site-section"><h3><CalendarDays size={18}/>{t('រយៈពេលប្រតិបត្តិការ','Operating period')}</h3><label>{t('ចាប់ផ្ដើមពី','Running from')}<input className="d-input" type="date" min="1900-01-01" max="9999-12-31" required value={draft.runningFrom} onChange={e=>update({runningFrom:e.target.value})}/></label><label>{t('បិទនៅថ្ងៃ','Shutdown on')}<small>{t('ស្រេចចិត្ត','Optional')}</small><input className="d-input" type="date" min={draft.runningFrom||'1900-01-01'} max="9999-12-31" value={draft.shutdownOn??''} onChange={e=>update({shutdownOn:e.target.value||null})}/></label>{draft.shutdownOn&&draft.shutdownOn<draft.runningFrom&&<p role="alert" className="access-error">{t('ថ្ងៃបិទត្រូវនៅក្រោយថ្ងៃចាប់ផ្ដើម','Shutdown must be on or after the running-from date.')}</p>}
    {!creating&&<label className="access-site-active"><span>{t('ដំណើរការ','Active')}</span><SwitchField checked={draft.active} disabled={busy} onChange={e=>update({active:e.target.checked})}/></label>}
   </section>
   <section className="access-site-section"><h3><Pencil size={18}/>{t('កំណត់សម្គាល់','Remarks')}<small>{t('ស្រេចចិត្ត','Optional')}</small></h3><textarea className="d-textarea" aria-label={t('កំណត់សម្គាល់','Remarks')} rows={3} maxLength={2000} value={draft.remarks} onChange={e=>update({remarks:e.target.value})}/></section>
   {error&&<div className="d-alert d-alert-error access-error" role="alert">{error}{recovery}</div>}
  </form>
 </AppDialog>;
}
