import { test, expect, type Page } from '@playwright/test';
test.beforeEach(async({page},info)=>{if(!info.title.startsWith('Khmer'))await page.addInitScript(()=>localStorage.setItem('onebite-language','en'));});
async function open(page:Page){await page.route('**/functions/v1/admin-access',route=>route.abort());await page.goto('http://127.0.0.1:5174');await page.getByRole('button',{name:'Open local preview'}).click();}
async function choose(page:Page,label:string,value:string){await page.getByLabel(label,{exact:true}).click();await page.locator(`[role="option"][data-value="${value}"]`).click();}
async function viewUser(page:Page,name:string){await page.locator('.access-user-row').filter({hasText:name}).click();await expect(page.getByRole('dialog').getByRole('heading',{name:'User details',exact:true})).toBeVisible();}
async function editUser(page:Page,name:string){await viewUser(page,name);await page.getByRole('dialog').getByRole('button',{name:'Edit',exact:true}).click();}
async function reviewRole(page:Page,role:string){const row=page.locator('.access-role-row').filter({has:page.getByRole('heading',{name:role,exact:true})});const review=row.getByRole('button',{name:'Review permissions',exact:true});if(!await review.isVisible())await row.getByRole('button',{name:role,exact:true}).click();await row.getByRole('button',{name:'Review permissions',exact:true}).click();}
async function tab(page:Page,name:string){
 await expect(page.locator('.access-main')).toBeVisible();
 if(page.viewportSize()!.width>680){await page.locator('.access-sidebar nav').getByRole('button',{name,exact:true}).click();return;}
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));const nav=page.locator('.access-bottom-nav');await expect(nav).not.toHaveClass(/is-scroll-hidden/);await expect(nav).not.toHaveAttribute('inert','');
 if(['App settings','Permissions'].includes(name)){await nav.getByRole('button',{name:'Hub',exact:true}).click();await page.locator('.access-hub-grid').getByRole('button',{name,exact:true}).click();}
 else await nav.getByRole('button',{name:name==='Site'?'Sites':name==='Activity'?'Logs':name,exact:true}).click();
}
test('Owner creates and edits accounts, prevents duplicates, preserves changes and audits them',async({page})=>{
 await open(page);await expect(page.locator('.access-user-row')).toHaveCount(6);
 await page.getByRole('button',{name:'Create new user',exact:true}).click();const dialog=page.getByRole('dialog');
 await dialog.getByLabel('Full name').fill('Test Staff');await dialog.getByLabel('Username',{exact:true}).fill('sokha');
 await expect(dialog.getByRole('alert')).toContainText('already used');await expect(dialog.getByRole('button',{name:'Create User',exact:true})).toBeDisabled();
 await dialog.getByLabel('Username',{exact:true}).fill('test.staff');await choose(page,'Role','Cashier');await dialog.getByRole('button',{name:'Create User',exact:true}).click();
 await expect(page.locator('.access-user-row')).toHaveCount(7);await page.reload();await page.getByRole('button',{name:'Open local preview'}).click();
 await editUser(page,'Test Staff');await dialog.getByLabel('Account active',{exact:true}).uncheck();await dialog.getByRole('button',{name:'Save changes'}).click();
 await expect(page.locator('.access-user-row')).toHaveCount(6);await page.reload();await page.getByRole('button',{name:'Open local preview'}).click();await expect(page.locator('.access-user-row')).toHaveCount(6);await expect(page.locator('.access-user-row').filter({hasText:'Test Staff'})).toHaveCount(0);
 await choose(page,'Filter status','inactive');await expect(page.locator('.access-user-row')).toHaveCount(1);await expect(page.locator('.access-user-row')).toContainText('Test Staff');
 await page.getByRole('textbox',{name:'Search users',exact:true}).fill('no-such-user');await page.locator('.ob-empty-state').getByRole('button',{name:'Clear filters',exact:true}).click();await expect(page.locator('.access-user-row')).toHaveCount(6);await expect(page.locator('.access-user-row').filter({hasText:'Test Staff'})).toHaveCount(0);
 await tab(page,'Activity');await expect(page.locator('.access-activity')).toContainText('Test Staff');await expect(page.locator('.access-activity')).toContainText('Dara');
});
test('Protects the last Owner and keeps unavailable permissions disabled',async({page})=>{
 await open(page);await editUser(page,'Dara');const dialog=page.getByRole('dialog');
 await expect(dialog.getByLabel('Role',{exact:true})).toBeDisabled();await expect(dialog.getByLabel('Account active',{exact:true})).toBeDisabled();await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await tab(page,'Roles');await reviewRole(page,'Cashier');
 await expect(dialog.getByLabel('Manage user accounts')).toBeEnabled();await expect(dialog.getByLabel('Override discount limits')).toBeDisabled();await expect(dialog.getByLabel('Refund or cancel paid invoices')).toBeDisabled();
 await dialog.getByLabel('Apply allowed discounts').uncheck();await dialog.getByRole('button',{name:'Save permissions'}).click();
 await tab(page,'Permissions');await expect(page.locator('.access-matrix-row').filter({hasText:'Apply allowed discounts'}).getByLabel('Cashier: denied')).toBeVisible();
});
test('Supervisor assignments preserve outside sites; Cashier cannot edit accounts',async({page})=>{
 await open(page);await choose(page,'Preview identity','supervisor');
 await expect(page.getByRole('button',{name:'Create new user',exact:true})).toHaveCount(0);await expect(page.locator('.access-user-row')).toHaveCount(4);
 await viewUser(page,'Sreypov');await page.getByRole('dialog').getByRole('button',{name:'Assign sites',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByLabel('Full name')).toHaveCount(0);await expect(dialog.getByRole('heading',{name:'Assign sites',exact:true})).toBeVisible();
 const outside=dialog.locator('.access-site-choice').filter({hasText:'Street corner'}).getByRole('checkbox');await expect(outside).toBeChecked();await expect(outside).toBeDisabled();
 await dialog.getByLabel('Neighborhood',{exact:true}).check();await dialog.getByRole('button',{name:'Save assignment'}).click();await viewUser(page,'Sreypov');await expect(dialog).toContainText('Street corner');await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await choose(page,'Preview identity','sokha');await expect(page.locator('.access-user-row')).toHaveCount(1);await viewUser(page,'Sokha');await expect(page.getByRole('dialog').getByRole('button',{name:'Edit',exact:true})).toHaveCount(0);await expect(page.getByRole('dialog').getByRole('button',{name:'Assign sites',exact:true})).toHaveCount(0);
});
test('Khmer account views fit a phone and permission matrix',async({page})=>{
 await page.addInitScript(()=>localStorage.removeItem('onebite-language'));await page.route('**/functions/v1/admin-access',route=>route.abort());await page.goto('http://127.0.0.1:5174');await page.getByRole('button',{name:'បើកសាកល្បងក្នុងឧបករណ៍',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('lang','km');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'ម៉ឺនុយគណនី'}).click();await page.getByRole('menuitem',{name:'English',exact:true}).click();await tab(page,'Permissions');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('Module denial blocks saved actions and Admin access; re-enabling preserves action settings',async({page})=>{
 await open(page);await tab(page,'Roles');
 await reviewRole(page,'Supervisor');
 const dialog=page.getByRole('dialog');await dialog.getByLabel('Access POS module',{exact:true}).uncheck();
 await expect(dialog.getByLabel('Receive orders',{exact:true})).toHaveCount(0);
 await dialog.getByLabel('Access Admin module',{exact:true}).uncheck();await expect(dialog.getByLabel('Assign existing staff to sites')).toHaveCount(0);
 await dialog.getByRole('button',{name:'Save permissions'}).click();await tab(page,'Permissions');
 const pos=page.locator('.access-permission-module').filter({has:page.getByRole('heading',{name:'POS',exact:true})});
 await expect(pos.locator('.access-matrix-row').filter({hasText:'Receive orders'}).getByLabel('Supervisor: denied')).toBeVisible();
 await choose(page,'Preview identity','supervisor');await expect(page.getByRole('heading',{name:'Admin access denied'})).toBeVisible();
 await page.getByRole('button',{name:'Return to preview Owner'}).click();await tab(page,'Roles');
 await reviewRole(page,'Supervisor');
 await dialog.getByLabel('Access POS module',{exact:true}).check();await expect(dialog.getByLabel('Receive orders',{exact:true})).toBeChecked();await expect(dialog.getByLabel('Receive orders',{exact:true})).toBeEnabled();
 await dialog.getByLabel('Access Admin module',{exact:true}).check();await dialog.getByRole('button',{name:'Save permissions'}).click();
 await choose(page,'Preview identity','supervisor');await expect(page.locator('.access-user-row')).toHaveCount(4);
});
test('Custom menus support keyboard selection, Escape and modal focus restoration',async({page},info)=>{
 await open(page);await page.getByRole('button',{name:'Create new user',exact:true}).click();const dialog=page.getByRole('dialog');
 const role=dialog.getByLabel('Role',{exact:true});await role.focus();await page.keyboard.press('Enter');
 await expect(page.getByRole('listbox')).toBeVisible();await expect(page.getByRole('option',{name:'Cashier',exact:true})).toBeFocused();await page.keyboard.press('End');await expect(page.getByRole('option',{name:'Supervisor',exact:true})).toBeFocused();await page.keyboard.press('Enter');
 await expect(role).toContainText('Supervisor');
 await role.click();await page.keyboard.press('Escape');await expect(page.getByRole('listbox')).toHaveCount(0);await expect(dialog).toBeVisible();
 await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Create new user',exact:true})).toBeFocused();
 await page.screenshot({path:`artifacts/admin-redesign-${info.project.name}.png`,fullPage:true});
 await tab(page,'Permissions');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:`artifacts/admin-permissions-${info.project.name}.png`,fullPage:true});
});

test('New user requires a staff role and offers generated, regenerated and copyable PINs',async({page,context})=>{
 await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:'http://127.0.0.1:5174'});
 await open(page);await page.getByRole('button',{name:'Create new user',exact:true}).click();const dialog=page.getByRole('dialog');
 const pin=dialog.getByLabel('Temporary 6-digit PIN',{exact:true});const first=await pin.inputValue();expect(first).toMatch(/^[0-9]{6}$/);
 const width=page.viewportSize()!.width;await page.setViewportSize({width,height:520});
 const create=dialog.getByRole('button',{name:'Create User',exact:true});const before=await create.boundingBox();expect(before).not.toBeNull();expect(before!.y+before!.height).toBeLessThanOrEqual(520);
 await dialog.locator('.modal-inner').evaluate(element=>{element.scrollTop=element.scrollHeight;});const after=await create.boundingBox();expect(after!.y).toBeCloseTo(before!.y,0);
 const boxes=await Promise.all([pin,dialog.getByRole('button',{name:'Regenerate PIN',exact:true}),dialog.getByRole('button',{name:'Copy PIN',exact:true})].map(locator=>locator.boundingBox()));
 expect(boxes[0]!.y+boxes[0]!.height/2).toBeCloseTo(boxes[1]!.y+boxes[1]!.height/2,0);expect(boxes[1]!.y+boxes[1]!.height/2).toBeCloseTo(boxes[2]!.y+boxes[2]!.height/2,0);

 await expect(dialog.getByLabel('Account active',{exact:true})).toHaveCount(0);await expect(dialog.getByText('Assigned sites',{exact:true})).toHaveCount(0);await expect(dialog.getByLabel('Confirm PIN')).toHaveCount(0);
 await dialog.getByLabel('Full name').fill('Generated PIN Staff');await dialog.getByLabel('Username',{exact:true}).fill('generated.pin.staff');
 await expect(dialog.getByRole('button',{name:'Create User',exact:true})).toBeDisabled();await expect(dialog.getByLabel('Role',{exact:true})).toContainText('Select a role');
 await dialog.getByRole('button',{name:'Regenerate PIN'}).click();const next=await pin.inputValue();expect(next).toMatch(/^[0-9]{6}$/);expect(next).not.toBe(first);
 await dialog.getByRole('button',{name:'Copy PIN',exact:true}).click();await expect(dialog.getByRole('status')).toHaveText('PIN copied');expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(next);
 await dialog.getByLabel('Role',{exact:true}).click();await expect(page.getByRole('option',{name:'Owner',exact:true})).toHaveCount(0);await page.getByRole('option',{name:'Cashier',exact:true}).click();
 await dialog.getByRole('button',{name:'Create User',exact:true}).click();const row=page.locator('.access-user-row').filter({hasText:'Generated PIN Staff'});await expect(row).toContainText('Active');await row.click();await expect(page.getByRole('dialog')).toContainText('No sites');
});

test('Users are grouped and alphabetized; filters combine and user details open before editing',async({page},info)=>{
 await open(page);const groups=page.locator('.access-user-group');await expect(groups).toHaveCount(3);
 const cashiers=page.getByRole('region',{name:'Cashier',exact:true});await expect(cashiers.locator('.access-person strong')).toHaveText(['Chantha','Pisey','Sokha','Sreypov']);
 const create=page.getByRole('button',{name:'Create new user',exact:true});await expect(create.locator('.access-new-label')).toHaveText('New User');if(info.project.name==='desktop')await expect(create.locator('.access-new-label')).toBeVisible();else await expect(create.locator('.access-new-label')).toBeHidden();
 const roles=page.getByRole('group',{name:'Filter role',exact:true});await roles.getByRole('button',{name:'Supervisor',exact:true}).click();await expect(page.locator('.access-user-row')).toHaveCount(1);await expect(groups).toHaveCount(1);
 await page.getByRole('textbox',{name:'Search users',exact:true}).fill('sokha');await expect(page.getByRole('heading',{name:'No matching users'})).toBeVisible();
 await roles.getByRole('button',{name:'All roles',exact:true}).click();await expect(page.locator('.access-user-row')).toHaveCount(1);
 const row=page.locator('.access-user-row');await row.focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog');await expect(dialog.getByRole('heading',{name:'User details',exact:true})).toBeVisible();await expect(dialog).toContainText('@sokha');await expect(dialog).toContainText('Riverside');
 await dialog.getByRole('button',{name:'Edit',exact:true}).click();await dialog.getByLabel('Account active',{exact:true}).uncheck();await dialog.getByRole('button',{name:'Save changes'}).click();
 await choose(page,'Filter status','active');await expect(page.getByRole('heading',{name:'No matching users'})).toBeVisible();
 await choose(page,'Filter status','inactive');await expect(page.locator('.access-user-row')).toHaveCount(1);await expect(page.locator('.access-user-row')).toContainText('Inactive');
 await page.getByRole('textbox',{name:'Search users',exact:true}).fill('');await choose(page,'Filter status','all');await expect(page.locator('.access-user-row')).toHaveCount(6);
});

test('Title bar profile actions, theme persistence and menu keyboard dismissal',async({page},info)=>{
 await open(page);await expect(page.locator('.ob-app-identity strong')).toHaveText('OneBite - Admin');await expect(page.locator('.ob-app-identity span')).toHaveCount(0);
 if(info.project.name==='desktop'){await expect(page.locator('.access-brand>span')).toBeHidden();await expect(page.locator('.access-brand img')).toBeVisible();await expect(page.locator('.access-sidebar-foot')).toContainText('App version 0.1.0');await expect(page.locator('.access-sidebar-foot .access-person')).toHaveCount(0);await expect(page.locator('.access-sidebar-foot button')).toHaveCount(0);await expect(page.locator('.ob-app-identity>img')).toBeHidden();}else{await expect(page.locator('.ob-app-identity>img')).toBeVisible();}
 const sync=page.locator('.ob-sync');await expect(sync).toHaveCSS('border-top-width','0px');const center=await sync.locator('.ob-sync-count').boundingBox(),ring=await sync.locator('.ob-sync-ring').boundingBox();expect(center&&ring&&Math.abs(center.x+center.width/2-ring.x-ring.width/2)<1&&Math.abs(center.y+center.height/2-ring.y-ring.height/2)<1).toBe(true);
 await page.getByRole('button',{name:'Profile menu',exact:true}).click();await page.getByRole('menuitem',{name:'My profile',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('@dara');await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Profile menu',exact:true}).click();await page.getByRole('menuitem',{name:'Dark mode',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await page.screenshot({path:`artifacts/admin-titlebar-dark-${info.project.name}.png`,fullPage:true});
 await page.reload();await page.getByRole('button',{name:'Open local preview'}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 const badge=page.getByRole('button',{name:'Profile menu',exact:true});await badge.click();await page.keyboard.press('Escape');await expect(page.getByRole('menu')).toHaveCount(0);await expect(badge).toBeFocused();
 await badge.click();await page.getByRole('menuitem',{name:'Light mode',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');
 await badge.click();await page.getByRole('menuitem',{name:'ខ្មែរ',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('lang','km');
 await page.getByRole('button',{name:'ម៉ឺនុយគណនី',exact:true}).click();await page.getByRole('menuitem',{name:'English',exact:true}).click();
 await badge.click();await page.getByRole('menuitem',{name:'Sign out',exact:true}).click();await expect(page.getByRole('heading',{name:'Welcome back',exact:true})).toBeVisible();
});

test('Live sync tracks in-flight changes, failures and successful refresh',async({page})=>{
 const {initialAccessState}=await import('../packages/core/src/access');const snapshot={...initialAccessState(),revision:0};
 await page.addInitScript(()=>sessionStorage.setItem('onebite-admin-session','a'.repeat(64)));
 let release:()=>void=()=>{},fail=false,hold=false;
 await page.route('**/functions/v1/admin-access',async route=>{
  const {action}=route.request().postDataJSON();if(hold)await new Promise<void>(resolve=>{release=resolve;});
  await route.fulfill({status:fail?503:200,json:fail?{error:'network_failed'}:{state:snapshot,actor:snapshot.users.find(u=>u.id==='owner'),ok:true}});
 });
 await page.goto('http://127.0.0.1:5174');const sync=page.locator('.ob-sync');await expect(sync).toHaveAttribute('data-state','complete');await expect(sync.locator('.ob-sync-center')).toBeVisible();
 hold=true;await sync.click();await expect(sync).toHaveAttribute('data-state','syncing');await expect(sync).toBeDisabled();await expect(sync.locator('.ob-sync-count')).toHaveText('0');release();await expect(sync).toHaveAttribute('data-state','complete');
 await page.getByRole('button',{name:'Create new user',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Full name').fill('Sync Tester');await dialog.getByLabel('Username',{exact:true}).fill('sync.tester');await choose(page,'Role','Cashier');
 fail=true;await dialog.getByRole('button',{name:'Create User',exact:true}).click();await expect(sync.locator('.ob-sync-count')).toHaveText('1');await expect(sync).toHaveAttribute('data-state','syncing');release();await expect(sync).toHaveAttribute('data-state','failed');await expect(sync.locator('.ob-sync-count')).toHaveCount(0);await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog.getByLabel('Username',{exact:true})).toHaveValue('sync.tester');
 await page.keyboard.press('Escape');fail=false;hold=false;await sync.click();await expect(sync).toHaveAttribute('data-state','complete');
});

for(const conflict of [false,true])test(`Stale user save ${conflict?'preserves draft and reloads a changed record':'refreshes unrelated changes and retries once'}`,async({page})=>{
 const {initialAccessState}=await import('../packages/core/src/access');const original={...initialAccessState(),revision:1};const latest=structuredClone(original);latest.revision=2;if(conflict)latest.users.find(user=>user.id==='owner')!.name='New server name';else latest.users.find(user=>user.id==='sokha')!.name='Changed elsewhere';
 let reads=0;const writes:Array<Record<string,unknown>>=[];
 await page.addInitScript(()=>sessionStorage.setItem('onebite-admin-session','a'.repeat(64)));
 await page.route('**/functions/v1/admin-access',async route=>{
  const {action,payload}=route.request().postDataJSON();if(action==='bootstrap.status'){await route.fulfill({json:{ownerCreated:true}});return;}if(action==='me'){const state=++reads===1?original:latest;await route.fulfill({json:{state,actor:state.users.find(user=>user.id==='owner')}});return;}
  writes.push(payload);if(writes.length===1){await route.fulfill({status:409,json:{error:'stale_revision'}});return;}
  const updated=structuredClone(latest);Object.assign(updated.users.find(user=>user.id==='owner')!,payload);updated.revision=3;await route.fulfill({json:{state:updated,ok:true}});
 });
 await page.goto('http://127.0.0.1:5174');await editUser(page,'Dara');const dialog=page.getByRole('dialog');await dialog.getByLabel('Full name').fill('My draft');await dialog.getByRole('button',{name:'Save changes',exact:true}).click();
 if(conflict){await expect(dialog.getByRole('alert')).toContainText('Data changed');await expect(dialog.getByLabel('Full name')).toHaveValue('My draft');expect(writes).toHaveLength(1);await dialog.getByRole('button',{name:'Reload latest · Discard this draft',exact:true}).click();await expect(dialog.getByLabel('Full name')).toHaveValue('New server name');await dialog.getByLabel('Full name').fill('Reviewed draft');await dialog.getByRole('button',{name:'Save changes',exact:true}).click();}
 await expect(dialog).toHaveCount(0);expect(writes).toHaveLength(2);expect(writes.map(write=>write.revision)).toEqual([1,2]);await expect(page.locator('.access-user-row').filter({hasText:conflict?'Reviewed draft':'My draft'})).toBeVisible();await expect(page.locator('.ob-sync')).toHaveAttribute('data-state','complete');
});

test('Owner edits profiles separately from site assignments and preserves existing sites',async({page})=>{
 await open(page);await editUser(page,'Sokha');const dialog=page.getByRole('dialog');await expect(dialog.getByText('Assigned sites',{exact:true})).toHaveCount(0);await expect(dialog.locator('.access-site-choice')).toHaveCount(0);await dialog.getByLabel('Full name').fill('Sokha Updated');await dialog.getByRole('button',{name:'Save changes',exact:true}).click();
 await viewUser(page,'Sokha Updated');await expect(dialog).toContainText('Riverside');await dialog.getByRole('button',{name:'Assign sites',exact:true}).click();await expect(dialog.getByRole('heading',{name:'Assign sites',exact:true})).toBeVisible();await expect(dialog.getByLabel('Riverside',{exact:true})).toBeChecked();await dialog.getByLabel('Riverside',{exact:true}).uncheck();await expect(dialog.getByRole('button',{name:'Save assignment',exact:true})).toBeDisabled();await dialog.getByLabel('Neighborhood',{exact:true}).check();await dialog.getByRole('button',{name:'Save assignment',exact:true}).click();
 await page.reload();await page.getByRole('button',{name:'Open local preview'}).click();await viewUser(page,'Sokha Updated');await expect(dialog).toContainText('Neighborhood');await expect(dialog).not.toContainText('Riverside');await dialog.getByRole('button',{name:'Close',exact:true}).click();await viewUser(page,'Dara');await expect(dialog.getByRole('button',{name:'Assign sites',exact:true})).toHaveCount(0);
});

test('Role rows collapse by default and show only allowed modules when expanded',async({page},info)=>{
 await open(page);await tab(page,'Roles');const rows=page.locator('.access-role-row');await expect(rows).toHaveCount(3);
 if(info.project.name==='desktop'){
  await expect(page.getByRole('button',{name:'Review permissions',exact:true})).toHaveCount(3);const first=await rows.nth(0).boundingBox(),second=await rows.nth(1).boundingBox();expect(second!.x).toBeGreaterThan(first!.x);expect(second!.y).toBe(first!.y);await reviewRole(page,'Cashier');const dialog=page.getByRole('dialog');await dialog.getByLabel('Access POS module',{exact:true}).uncheck();await dialog.getByRole('button',{name:'Save permissions'}).click();await expect(rows.nth(0).locator('.access-role-modules li')).toHaveText(['Admin']);await page.screenshot({path:`artifacts/admin-roles-${info.project.name}.png`,fullPage:true});await page.getByRole('button',{name:'Profile menu',exact:true}).click();await page.getByRole('menuitem',{name:'Dark mode',exact:true}).click();await page.screenshot({path:`artifacts/admin-roles-dark-${info.project.name}.png`,fullPage:true});return;
 }
 await expect(page.getByRole('button',{name:'Review permissions',exact:true})).toHaveCount(0);
 const cashier=rows.filter({has:page.getByRole('heading',{name:'Cashier',exact:true})});const toggle=cashier.getByRole('button',{name:'Cashier',exact:true});await expect(toggle).toHaveAttribute('aria-expanded','false');await toggle.focus();await page.keyboard.press('Space');await expect(toggle).toHaveAttribute('aria-expanded','true');await expect(cashier.locator('.access-role-modules li')).toHaveText(['POS','Admin']);await expect(cashier.getByRole('button',{name:'Review permissions',exact:true})).toBeVisible();
 await cashier.getByRole('button',{name:'Review permissions',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Access POS module',{exact:true}).uncheck();await dialog.getByRole('button',{name:'Save permissions'}).click();await expect(cashier.locator('.access-role-modules li')).toHaveText(['Admin']);
 await toggle.click();await expect(toggle).toHaveAttribute('aria-expanded','false');await expect(cashier.getByRole('button',{name:'Review permissions',exact:true})).toHaveCount(0);await rows.filter({has:page.getByRole('heading',{name:'Owner',exact:true})}).getByRole('button',{name:'Owner',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/admin-roles-${info.project.name}.png`,fullPage:true});
 await page.getByRole('button',{name:'Profile menu',exact:true}).click();await page.getByRole('menuitem',{name:'Dark mode',exact:true}).click();await page.screenshot({path:`artifacts/admin-roles-dark-${info.project.name}.png`,fullPage:true});
});

test('Permission sections use switches, hide denied actions and keep save visible',async({page},info)=>{
 await open(page);await tab(page,'Roles');await reviewRole(page,'Supervisor');const dialog=page.getByRole('dialog');const pos=dialog.getByRole('region',{name:'POS',exact:true});const module=pos.getByRole('switch',{name:'Access POS module',exact:true});await expect(module).toBeChecked();await expect(pos.getByText('Allowed',{exact:true})).toBeVisible();await expect(pos.locator('.access-policy-actions li')).toHaveCount(9);
 const discount=pos.getByRole('switch',{name:'Apply allowed discounts',exact:true});await discount.focus();await page.keyboard.press('Space');await expect(discount).not.toBeChecked();await module.uncheck();await expect(pos.getByText('Denied',{exact:true})).toBeVisible();await expect(pos.locator('.access-policy-actions')).toHaveCount(0);await module.check();await expect(discount).not.toBeChecked();await expect(pos.getByRole('switch',{name:'Override discount limits',exact:true})).toBeDisabled();await expect(pos.getByRole('switch',{name:'Refund or cancel paid invoices',exact:true})).toBeDisabled();
 await page.screenshot({path:`artifacts/admin-permission-editor-${info.project.name}.png`,fullPage:true,animations:'disabled'});const viewport=page.viewportSize()!;await page.setViewportSize({...viewport,height:520});const save=dialog.getByRole('button',{name:'Save permissions',exact:true});const before=await save.boundingBox(),titleBefore=await dialog.locator('.modal-heading').boundingBox();await dialog.locator('.modal-inner').evaluate(element=>{element.scrollTop=element.scrollHeight;});const after=await save.boundingBox(),titleAfter=await dialog.locator('.modal-heading').boundingBox();expect(before&&after&&Math.abs(before.y-after.y)<1&&after.y+after.height<=520).toBe(true);expect(titleBefore&&titleAfter&&Math.abs(titleBefore.y-titleAfter.y)<1&&titleAfter.y>=0).toBe(true);await save.click();
 await reviewRole(page,'Supervisor');await expect(dialog.getByRole('switch',{name:'Apply allowed discounts',exact:true})).not.toBeChecked();await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.setViewportSize(viewport);await page.getByRole('button',{name:'Profile menu',exact:true}).click();await page.getByRole('menuitem',{name:'Dark mode',exact:true}).click();await reviewRole(page,'Supervisor');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/admin-permission-editor-dark-${info.project.name}.png`,fullPage:true,animations:'disabled'});
});

test('empty directories offer creation only with permission and clear filters without changing data',async({page},info)=>{
 await open(page);await tab(page,'Activity');await page.locator('.ob-empty-state').getByRole('button',{name:'Create new user',exact:true}).click();await expect(page.getByRole('dialog').getByLabel('Role',{exact:true})).toContainText('Select a role');await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();await tab(page,'Users');await page.getByRole('textbox',{name:'Search users',exact:true}).fill('no-such-team-member');
 const empty=page.locator('.ob-empty-state');await expect(empty.getByRole('heading',{name:'No matching users'})).toBeVisible();
 await empty.getByRole('button',{name:'Create new user',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('heading',{name:'Create new user',exact:true})).toBeVisible();await expect(dialog.getByLabel('Full name')).toHaveValue('');await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await empty.getByRole('button',{name:'Clear filters',exact:true}).click();await expect(page.locator('.access-user-row')).toHaveCount(6);
 await choose(page,'Preview identity','supervisor');await page.getByRole('textbox',{name:'Search users',exact:true}).fill('no-such-team-member');await expect(empty).toBeVisible();await expect(empty.getByRole('button',{name:'Create new user',exact:true})).toHaveCount(0);await empty.getByRole('button',{name:'Clear filters',exact:true}).click();await expect(page.locator('.access-user-row')).toHaveCount(4);
 await choose(page,'Preview identity','owner');await page.getByRole('textbox',{name:'Search users',exact:true}).fill('no-such-team-member');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/admin-empty-state-${info.project.name}.png`,fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'Profile menu',exact:true}).click();await page.getByRole('menuitem',{name:'Dark mode',exact:true}).click();await expect(empty.getByRole('button',{name:'Create new user',exact:true})).toBeVisible();await page.screenshot({path:`artifacts/admin-empty-state-dark-${info.project.name}.png`,fullPage:true,animations:'disabled'});
});


test('Admin pages share a title and subtitle header with the user action on the right',async({page},info)=>{
 await open(page);const header=page.locator('.ob-page-heading');await expect(header.getByRole('heading',{level:1})).toHaveText('Users');await expect(header.locator('p')).toHaveText('Manage your team and account access.');const create=header.getByRole('button',{name:'Create new user',exact:true});await expect(create).toBeVisible();await expect(create).toHaveCSS('background-color','rgb(245, 121, 33)');const titleBox=await header.locator('.ob-page-heading-copy').boundingBox(),actionBox=await create.boundingBox();expect(actionBox!.x).toBeGreaterThan(titleBox!.x+titleBox!.width);await expect(page.getByLabel('Filter status',{exact:true})).toContainText('Active');await page.screenshot({path:`artifacts/admin-page-header-${info.project.name}.png`,fullPage:true,animations:'disabled'});
 for(const [name,title,subtitle] of [['Roles','Roles','Review each role and its allowed modules.'],['Permissions','Permissions','Control module access and actions for each role.'],['Activity','Activity log','Track account, role, and permission changes.']]){await tab(page,name);await expect(header.getByRole('heading',{level:1})).toHaveText(title);await expect(header.locator('p')).toHaveText(subtitle);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
 await choose(page,'Preview identity','supervisor');await expect(header.getByRole('button',{name:'Create new user',exact:true})).toHaveCount(0);await expect(header.locator('p')).toHaveText('Manage your team and account access.');
});

test('Owner creates a custom role, configures permissions and assigns it to a user',async({page},info)=>{
 await open(page);await tab(page,'Roles');await expect(page.locator('.ob-page-heading h1')).toHaveText('Roles');const create=page.locator('.ob-page-heading').getByRole('button',{name:'Create new role',exact:true});await expect(create.locator('.access-new-label')).toHaveText('New Role');if(info.project.name==='desktop')await expect(create.locator('.access-new-label')).toBeVisible();else await expect(create.locator('.access-new-label')).toBeHidden();await create.click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('button',{name:'Create Role',exact:true})).toBeDisabled();await dialog.getByLabel('Role name',{exact:true}).fill('Cashier');await expect(dialog.getByRole('alert')).toContainText('already used');await dialog.getByLabel('Role name',{exact:true}).fill('Shift Lead');await dialog.getByLabel('Short description',{exact:true}).fill('Support the team at the site.');
 await expect(dialog.getByRole('switch',{name:'Access Inventory module',exact:true})).toBeDisabled();await expect(dialog.getByRole('switch',{name:'Access Attendance module',exact:true})).toBeDisabled();await dialog.getByRole('switch',{name:'Access Admin module',exact:true}).check();await dialog.getByRole('switch',{name:'Manage user accounts',exact:true}).check();await expect(dialog.getByRole('switch',{name:'Manage sites',exact:true})).toBeEnabled();await dialog.getByRole('button',{name:'Create Role',exact:true}).click();await expect(page.locator('.access-role-row')).toHaveCount(4);await reviewRole(page,'Shift Lead');await expect(dialog.getByRole('switch',{name:'Manage user accounts',exact:true})).toBeChecked();await dialog.getByRole('button',{name:'Close',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Open local preview'}).click();await editUser(page,'Sokha');await page.getByLabel('Role',{exact:true}).click();await page.getByRole('option',{name:'Shift Lead',exact:true}).click();await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('region',{name:'Shift Lead',exact:true})).toContainText('Sokha');
 await tab(page,'Permissions');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await tab(page,'Roles');await reviewRole(page,'Owner');await expect(dialog.getByRole('switch',{name:'Access Admin module',exact:true})).toBeDisabled();await expect(dialog.getByRole('switch',{name:'Manage role permissions',exact:true})).toBeDisabled();await dialog.getByRole('switch',{name:'Apply allowed discounts',exact:true}).uncheck();await page.screenshot({path:`artifacts/admin-owner-permissions-${info.project.name}.png`,fullPage:true,animations:'disabled'});await dialog.getByRole('button',{name:'Save permissions',exact:true}).click();await reviewRole(page,'Owner');await expect(dialog.getByRole('switch',{name:'Apply allowed discounts',exact:true})).not.toBeChecked();await dialog.getByRole('button',{name:'Close',exact:true}).click();await choose(page,'Preview identity','supervisor');await tab(page,'Roles');await expect(page.getByRole('button',{name:'Create new role',exact:true})).toHaveCount(0);
});

test('Role creation waits for a current backend snapshot and unlocks after sync',async({page})=>{
 const {initialAccessState}=await import('../packages/core/src/access');const state={...initialAccessState(),revision:0};let modern=false;await page.addInitScript(()=>sessionStorage.setItem('onebite-admin-session','a'.repeat(64)));await page.route('**/functions/v1/admin-access',r=>r.fulfill({json:{actor:state.users[0],state:modern?{...state,customRoles:[]}:state}}));await page.goto('http://127.0.0.1:5174');await tab(page,'Roles');await expect(page.getByRole('button',{name:'Create new role',exact:true})).toBeDisabled();await reviewRole(page,'Cashier');await expect(page.getByRole('dialog').getByRole('switch',{name:'Manage user accounts',exact:true})).toBeDisabled();await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();modern=true;await page.locator('.ob-sync').click();await expect(page.getByRole('button',{name:'Create new role',exact:true})).toBeEnabled();await reviewRole(page,'Cashier');await expect(page.getByRole('dialog').getByRole('switch',{name:'Manage user accounts',exact:true})).toBeEnabled();
});

test('Site creation, operating schedule, editing and deactivation persist without changing staff assignments',async({page},info)=>{
 await open(page);await tab(page,'Site');const header=page.locator('.ob-page-heading');await expect(header.locator('h1')).toHaveText('Site');await expect(header.locator('p')).toHaveText('Manage locations and operating details.');await expect(page.locator('.access-site-row')).toHaveCount(3);
 await header.getByRole('button',{name:'New Site',exact:true}).click();const dialog=page.getByRole('dialog');await expect(dialog.getByRole('switch',{name:'Active',exact:true})).toHaveCount(0);await expect(dialog.getByRole('button',{name:'Working days & hours',exact:true})).toHaveAttribute('aria-expanded','false');await expect(dialog.getByRole('button',{name:'Operating period',exact:true})).toHaveAttribute('aria-expanded','false');await dialog.getByRole('button',{name:'Operating period',exact:true}).click();await expect(dialog.getByLabel('Running from',{exact:true})).toHaveValue(await page.evaluate(()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Phnom_Penh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())));await expect(dialog.getByRole('button',{name:'Create Site',exact:true})).toBeDisabled();
 await dialog.getByLabel('Name',{exact:true}).fill('Central Market');await dialog.getByLabel('Location',{exact:true}).fill('Near Central Market, Phnom Penh');await dialog.getByLabel('Latitude',{exact:true}).fill('91');await dialog.getByLabel('Longitude',{exact:true}).fill('104.92');await expect(dialog.getByRole('button',{name:'Create Site',exact:true})).toBeDisabled();await dialog.getByLabel('Latitude',{exact:true}).fill('11.56');
 await dialog.getByRole('button',{name:'Working days & hours',exact:true}).click();await dialog.getByLabel('Monday',{exact:true}).check();await dialog.getByLabel('Monday opening',{exact:true}).fill('16:30');await dialog.getByLabel('Monday closing',{exact:true}).fill('22:30');await dialog.getByLabel('Remarks',{exact:true}).fill('Collect stock before opening.');await dialog.getByRole('button',{name:'Working days & hours',exact:true}).click();await dialog.getByRole('button',{name:'Operating period',exact:true}).click();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/admin-new-site-${info.project.name}.png`,fullPage:true});await dialog.getByRole('button',{name:'Create Site',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.locator('.access-site-row')).toHaveCount(4);
 await page.reload();await page.getByRole('button',{name:'Open local preview',exact:true}).click();await tab(page,'Site');await page.getByRole('button',{name:'Edit site Central Market',exact:true}).click();await expect(dialog.getByLabel('Location',{exact:true})).toHaveValue('Near Central Market, Phnom Penh');await dialog.getByRole('button',{name:'Working days & hours',exact:true}).click();await expect(dialog.getByLabel('Monday opening',{exact:true})).toHaveValue('16:30');await dialog.getByRole('button',{name:'Operating period',exact:true}).click();await expect(dialog.getByLabel('Remarks',{exact:true})).toHaveValue('Collect stock before opening.');await expect(dialog.getByRole('switch',{name:'Active',exact:true})).toBeChecked();await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('button',{name:'Edit site Riverside',exact:true}).click();await dialog.getByLabel('Location',{exact:true}).fill('Riverside walkway');await dialog.getByLabel('Latitude',{exact:true}).fill('11.57');await dialog.getByLabel('Longitude',{exact:true}).fill('104.93');await dialog.getByRole('button',{name:'Operating period',exact:true}).click();await dialog.getByLabel('Running from',{exact:true}).fill('2026-10-09');await dialog.getByLabel(/^Shutdown on/).fill('2026-10-08');await expect(dialog.getByRole('button',{name:'Save changes',exact:true})).toBeDisabled();await dialog.getByLabel(/^Shutdown on/).fill('2026-11-09');await dialog.getByRole('switch',{name:'Active',exact:true}).uncheck();await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await expect(page.getByRole('button',{name:'Edit site Riverside',exact:true})).toContainText('Inactive');
 await tab(page,'Users');await viewUser(page,'Sokha');await expect(dialog).toContainText('Riverside');await dialog.getByRole('button',{name:'Close',exact:true}).click();await tab(page,'Activity');await expect(page.locator('.access-activity')).toContainText('site.created');await expect(page.locator('.access-activity')).toContainText('site.updated');
});

test('Site management follows module and action grants and has a prominent empty-state action',async({page})=>{
 const {initialAccessState}=await import('../packages/core/src/access');const state=initialAccessState();state.sites=[];await page.addInitScript(s=>localStorage.setItem('onebite-admin-access-preview-v1',JSON.stringify({...s,revision:0,permissionSchema:2})),state);await open(page);await tab(page,'Site');await expect(page.locator('.ob-empty-state')).toContainText('Give OneBite a place to grow');await page.locator('.ob-empty-state').getByRole('button',{name:'New Site',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
 await choose(page,'Preview identity','supervisor');await expect(page.getByRole('button',{name:'Site',exact:true}).filter({visible:true}).and(page.locator('button:enabled'))).toHaveCount(0);await choose(page,'Preview identity','owner');await tab(page,'Roles');await reviewRole(page,'Supervisor');const dialog=page.getByRole('dialog');await dialog.getByRole('switch',{name:'Manage sites',exact:true}).check();await dialog.getByRole('button',{name:'Save permissions',exact:true}).click();await choose(page,'Preview identity','supervisor');await tab(page,'Site');await expect(page.locator('.ob-page-heading').getByRole('button',{name:'New Site',exact:true})).toBeVisible();
});


test('Sites allow no coordinates and current location fills both fields with a useful denied-access message',async({page,context})=>{
 await context.grantPermissions(['geolocation'],{origin:'http://127.0.0.1:5174'});await context.setGeolocation({latitude:11.5564,longitude:104.9282});await open(page);await tab(page,'Site');await page.locator('.ob-page-heading').getByRole('button',{name:'New Site',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Name',{exact:true}).fill('Optional Coordinates');await dialog.getByLabel('Location',{exact:true}).fill('Phnom Penh');const save=dialog.getByRole('button',{name:'Create Site',exact:true});await expect(save).toBeEnabled();await dialog.getByRole('button',{name:'Use my current location',exact:true}).click();await expect(dialog.getByLabel('Latitude',{exact:true})).toHaveValue('11.5564');await expect(dialog.getByLabel('Longitude',{exact:true})).toHaveValue('104.9282');await expect(dialog.getByRole('status')).toHaveText('Current location added.');
 await dialog.getByLabel('Latitude',{exact:true}).fill('');await expect(save).toBeDisabled();await dialog.getByLabel('Longitude',{exact:true}).fill('');await expect(save).toBeEnabled();await page.evaluate(()=>Object.defineProperty(navigator,'geolocation',{configurable:true,value:{getCurrentPosition:(_success:unknown,failure:(error:{code:number})=>void)=>failure({code:1})}}));await dialog.getByRole('button',{name:'Use my current location',exact:true}).click();await expect(dialog.getByRole('alert')).toContainText('Location access was denied');await expect(save).toBeEnabled();await save.click();await page.getByRole('button',{name:'Edit site Optional Coordinates',exact:true}).click();await expect(dialog.getByLabel('Latitude',{exact:true})).toHaveValue('');await expect(dialog.getByLabel('Longitude',{exact:true})).toHaveValue('');
});

test('Site schedules save shared hours for all days and allow individual day changes',async({page},info)=>{
 await open(page);await tab(page,'Site');await page.locator('.ob-page-heading').getByRole('button',{name:'New Site',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Name',{exact:true}).fill('Daily Hours');await dialog.getByLabel('Location',{exact:true}).fill('Phnom Penh');await dialog.getByRole('button',{name:'Working days & hours',exact:true}).click();await dialog.getByRole('button',{name:'Same hours every day',exact:true}).click();await expect(dialog.getByRole('button',{name:'Same hours every day',exact:true})).toHaveCSS('color','rgb(255, 255, 255)');await dialog.getByLabel('Opening',{exact:true}).fill('18:00');await dialog.getByLabel('Closing',{exact:true}).fill('01:00');await dialog.getByRole('button',{name:'Create Site',exact:true}).click();await expect(dialog).toHaveCount(0);
 await page.reload();await page.getByRole('button',{name:'Open local preview',exact:true}).click();await tab(page,'Site');await page.getByRole('button',{name:'Edit site Daily Hours',exact:true}).click();await dialog.getByRole('button',{name:'Working days & hours',exact:true}).click();await expect(dialog.getByRole('button',{name:'Same hours every day',exact:true})).toHaveAttribute('aria-pressed','true');await expect(dialog.getByLabel('Opening',{exact:true})).toHaveValue('18:00');await expect(dialog.getByLabel('Closing',{exact:true})).toHaveValue('01:00');await page.screenshot({path:`artifacts/admin-shared-hours-${info.project.name}.png`,fullPage:true});
 await dialog.getByRole('button',{name:'Different hours by day',exact:true}).click();for(const day of ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']){await expect(dialog.getByLabel(day,{exact:true})).toBeChecked();await expect(dialog.getByLabel(`${day} opening`,{exact:true})).toHaveValue('18:00');await expect(dialog.getByLabel(`${day} closing`,{exact:true})).toHaveValue('01:00');}
 await dialog.getByLabel('Sunday',{exact:true}).uncheck();await dialog.getByLabel('Saturday opening',{exact:true}).fill('17:00');await dialog.getByLabel('Saturday closing',{exact:true}).fill('23:00');await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('button',{name:'Edit site Daily Hours',exact:true}).click();await dialog.getByRole('button',{name:'Working days & hours',exact:true}).click();await expect(dialog.getByRole('button',{name:'Different hours by day',exact:true})).toHaveAttribute('aria-pressed','true');await expect(dialog.getByLabel('Sunday',{exact:true})).not.toBeChecked();await expect(dialog.getByLabel('Monday opening',{exact:true})).toHaveValue('18:00');await expect(dialog.getByLabel('Saturday opening',{exact:true})).toHaveValue('17:00');await expect(dialog.getByLabel('Saturday closing',{exact:true})).toHaveValue('23:00');
 await dialog.getByRole('button',{name:'Same hours every day',exact:true}).click();await dialog.getByLabel('Closing',{exact:true}).fill('18:00');await expect(dialog.getByRole('button',{name:'Save changes',exact:true})).toBeDisabled();await dialog.getByLabel('Closing',{exact:true}).fill('22:00');await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await page.getByRole('button',{name:'Edit site Daily Hours',exact:true}).click();await dialog.getByRole('button',{name:'Working days & hours',exact:true}).click();await expect(dialog.getByRole('button',{name:'Same hours every day',exact:true})).toHaveAttribute('aria-pressed','true');await expect(dialog.getByLabel('Closing',{exact:true})).toHaveValue('22:00');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('Site photos can be added, replaced and removed with persisted card previews',async({page})=>{
 await open(page);await tab(page,'Site');const png=Buffer.from(await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=80;canvas.height=50;canvas.getContext('2d')!.fillRect(0,0,80,50);return canvas.toDataURL('image/png').split(',')[1];}),'base64');await page.locator('.ob-page-heading').getByRole('button',{name:'New Site',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.getByLabel('Name',{exact:true}).fill('Photo Site');await dialog.getByLabel('Location',{exact:true}).fill('Phnom Penh');const input=dialog.getByLabel('Choose site photo',{exact:true});await input.setInputFiles({name:'site.png',mimeType:'image/png',buffer:png});await expect(dialog.getByRole('button',{name:'Replace photo',exact:true})).toBeEnabled();await expect(dialog.getByRole('img',{name:'Site photo',exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Create Site',exact:true}).click();const card=page.getByRole('button',{name:'Edit site Photo Site',exact:true});await expect(card.getByRole('img',{name:'Photo Site',exact:true})).toHaveAttribute('src',/^data:image\/jpeg;base64,/);
 await page.reload();await page.getByRole('button',{name:'Open local preview',exact:true}).click();await tab(page,'Site');await card.click();await expect(dialog.getByRole('img',{name:'Site photo',exact:true})).toBeVisible();const original=await dialog.getByRole('img',{name:'Site photo',exact:true}).getAttribute('src');await input.setInputFiles({name:'bad.png',mimeType:'image/png',buffer:Buffer.from('not an image')});await expect(dialog.getByRole('alert')).toContainText('Choose a JPG, PNG or WebP');await expect(dialog.getByRole('img',{name:'Site photo',exact:true})).toHaveAttribute('src',original!);await expect(dialog.getByRole('button',{name:'Save changes',exact:true})).toBeEnabled();await input.setInputFiles({name:'replacement.png',mimeType:'image/png',buffer:png});await expect(dialog.getByRole('alert')).toHaveCount(0);await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await card.click();await dialog.getByRole('button',{name:'Remove photo',exact:true}).click();await expect(dialog.getByRole('img',{name:'Site photo',exact:true})).toHaveCount(0);await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await expect(card.getByRole('img')).toHaveCount(0);await card.click();await expect(dialog.getByRole('button',{name:'Upload photo',exact:true})).toBeVisible();
});

test('Live site photo failures preserve the current photo and retry saves the uploaded path',async({page})=>{
 const {initialAccessState,saveSite}=await import('../packages/core/src/access');const oldPath='11111111-1111-4111-8111-111111111111/22222222-2222-4222-8222-222222222222.jpg',newPath='11111111-1111-4111-8111-111111111111/33333333-3333-4333-8333-333333333333.jpg';let state={...initialAccessState(),revision:0};state.sites[0]={...state.sites[0],location:'Phnom Penh',photoPath:oldPath};let fail=true;await page.addInitScript(()=>sessionStorage.setItem('onebite-admin-session','a'.repeat(64)));
 await page.route('**/storage/v1/object/public/site-photos/**',r=>r.fulfill({status:404}));await page.route('**/functions/v1/admin-access',async route=>{const {action,payload}=route.request().postDataJSON();if(action==='site.photo.upload'){expect(route.request().headers().authorization).toBe('Bearer '+'a'.repeat(64));expect(payload.image).toMatch(/^\/9j/);return route.fulfill(fail?{status:502,json:{error:'photo_upload_failed'}}:{json:{photoPath:newPath}});}if(action==='site.update'){expect(payload.photoPath).toBe(newPath);state={...saveSite(state,'owner',payload),revision:state.revision+1};}return route.fulfill({json:{actor:state.users[0],state}});});
 await page.goto('http://127.0.0.1:5174');await tab(page,'Site');await page.getByRole('button',{name:'Edit site Riverside',exact:true}).click();const dialog=page.getByRole('dialog');const png=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=40;c.height=40;return c.toDataURL('image/png').split(',')[1];}),'base64');const photo={name:'live.png',mimeType:'image/png',buffer:png};await dialog.getByLabel('Choose site photo',{exact:true}).setInputFiles(photo);await expect(dialog.getByRole('alert')).toContainText('Could not upload the photo');await expect(dialog.getByRole('img',{name:'Site photo',exact:true})).toHaveAttribute('src',new RegExp(oldPath));fail=false;await dialog.getByLabel('Choose site photo',{exact:true}).setInputFiles(photo);await expect(dialog.getByRole('img',{name:'Site photo',exact:true})).toHaveAttribute('src',new RegExp(newPath));await expect(dialog.getByRole('alert')).toHaveCount(0);await dialog.getByRole('button',{name:'Save changes',exact:true}).click();await expect(dialog).toHaveCount(0);await expect(page.getByRole('button',{name:'Edit site Riverside',exact:true}).getByRole('img')).toHaveAttribute('src',new RegExp(newPath));
});

test('App settings save validated geofence rules and preferences, with delegated permission controls',async({page},info)=>{
 await open(page);await tab(page,'App settings');await expect(page.locator('.ob-page-heading h1')).toHaveText('App settings');for(const section of ['Geofence','Preferences','Exchange rate']){const toggle=page.getByRole('button',{name:section,exact:true});await expect(toggle).toHaveAttribute('aria-expanded','false');await toggle.click();}const geofence=page.getByRole('button',{name:'Geofence',exact:true});await geofence.focus();await page.keyboard.press('Enter');await expect(geofence).toHaveAttribute('aria-expanded','false');await expect(page.getByLabel('Distance from site (m)',{exact:true})).toBeHidden();await page.keyboard.press('Enter');const radius=page.getByLabel('Distance from site (m)',{exact:true}),accuracy=page.getByLabel('Maximum GPS uncertainty (m)',{exact:true}),rate=page.getByLabel('KHR for USD 1',{exact:true}),save=page.getByRole('button',{name:'Save settings',exact:true});await expect(radius).toHaveValue('100');await expect(accuracy).toHaveValue('50');await expect(rate).toHaveValue('4000');await expect(save).toBeDisabled();await radius.fill('0');await expect(save).toBeDisabled();await radius.fill('150');await accuracy.fill('25');await rate.fill('4100');await choose(page,'Default theme','dark');await choose(page,'Default currency','USD');await choose(page,'Default payment method','qr');for(const section of ['Geofence','Preferences','Exchange rate'])await page.getByRole('button',{name:section,exact:true}).click();await save.click();await expect(save).toBeDisabled();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.reload();await page.getByRole('button',{name:'Open local preview',exact:true}).click();await tab(page,'App settings');for(const section of ['Geofence','Preferences','Exchange rate'])await page.getByRole('button',{name:section,exact:true}).click();await expect(radius).toHaveValue('150');await expect(accuracy).toHaveValue('25');await expect(rate).toHaveValue('4100');await expect(page.getByLabel('Default currency',{exact:true})).toHaveText('USD · US dollar');await expect(page.getByLabel('Default payment method',{exact:true})).toHaveText('QR Payment');await page.screenshot({path:`artifacts/admin-app-settings-${info.project.name}.png`,fullPage:true});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.getByRole('button',{name:'Profile menu',exact:true}).click();await page.getByRole('menuitem',{name:'Light mode',exact:true}).click();await page.reload();await page.getByRole('button',{name:'Open local preview',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','light');await choose(page,'Preview identity','supervisor');await expect(page.getByRole('button',{name:'App settings',exact:true})).toHaveCount(0);await choose(page,'Preview identity','owner');await tab(page,'Roles');await reviewRole(page,'Supervisor');await page.getByRole('dialog').getByRole('switch',{name:'Manage app settings',exact:true}).check();await page.getByRole('dialog').getByRole('button',{name:'Save permissions',exact:true}).click();await choose(page,'Preview identity','supervisor');await tab(page,'App settings');await page.getByRole('button',{name:'Geofence',exact:true}).click();await accuracy.fill('30');await save.click();await expect(save).toBeDisabled();await tab(page,'Users');
});

test('Hub links all allowed Admin menus and mobile navigation has five items with Hub last',async({page},info)=>{
 await open(page);if(info.project.name==='phone'){const nav=page.locator('.access-bottom-nav');await expect(nav.getByRole('button')).toHaveText(['Sites','Users','Roles','Logs','Hub']);await expect(nav.getByRole('button').last()).toHaveText('Hub');const widths=await nav.getByRole('button').evaluateAll(buttons=>buttons.map(button=>button.getBoundingClientRect().width));expect(Math.max(...widths)-Math.min(...widths)).toBeLessThan(1);await page.evaluate(()=>window.scrollTo(0,300));await expect(nav).toHaveAttribute('inert','');await expect(nav).toHaveAttribute('aria-hidden','true');await page.evaluate(()=>window.scrollTo(0,200));await expect(nav).not.toHaveAttribute('inert','');await expect(nav).toHaveAttribute('aria-hidden','false');await page.evaluate(()=>window.scrollTo(0,0));await nav.getByRole('button',{name:'Hub',exact:true}).click();}else{await page.getByRole('button',{name:'Profile menu',exact:true}).click();await page.getByRole('menuitem',{name:'Hub',exact:true}).click();}
 await expect(page.locator('.access-hub-card')).toHaveCount(6);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.screenshot({path:`artifacts/admin-hub-${info.project.name}.png`,fullPage:true});await page.locator('.access-hub-card').filter({hasText:'App settings'}).click();await expect(page.locator('.ob-page-heading h1')).toHaveText('App settings');
 await choose(page,'Preview identity','sokha');await page.getByRole('button',{name:'Profile menu',exact:true}).click();await page.getByRole('menuitem',{name:'Hub',exact:true}).click();await expect(page.locator('.access-hub-card')).toHaveCount(3);await expect(page.locator('.access-hub-grid')).not.toContainText('App settings');
});

test('Activity history scrolls in pages, groups Cambodia dates and filters the full history with retry',async({page},info)=>{
 const {initialAccessState}=await import('../packages/core/src/access');const snapshot={...initialAccessState(),revision:0};const events=Array.from({length:245},(_,i)=>({id:`log-${String(i).padStart(3,'0')}`,time:new Date(Date.UTC(2026,9,9,18)-i*3600000).toISOString(),actorId:'owner',actorName:'Dara',action:'user.updated',targetName:`Log ${i}`,detail:`Detail ${i}`}));const requests:Record<string,unknown>[]=[];let failNext=false;
 await page.addInitScript(()=>sessionStorage.setItem('onebite-admin-session','a'.repeat(64)));
 await page.route('**/functions/v1/admin-access',async route=>{const {action,payload}=route.request().postDataJSON();if(action==='bootstrap.status'){await route.fulfill({json:{ownerCreated:true}});return;}if(action!=='activity.list'){await route.fulfill({json:{state:snapshot,actor:snapshot.users[0]}});return;}
  requests.push(payload);if(failNext){failNext=false;await route.fulfill({status:503,json:{error:'network_failed'}});return;}
  const day=(time:string)=>new Date(new Date(time).getTime()+7*3600000).toISOString().slice(0,10);const filtered=events.filter(e=>(!payload.start||day(e.time)>=payload.start)&&(!payload.end||day(e.time)<=payload.end));const offset=payload.cursor?filtered.findIndex(e=>e.id===payload.cursor.id)+1:0;const rows=filtered.slice(offset,offset+30);await route.fulfill({json:{events:rows,nextCursor:offset+30<filtered.length?{id:rows.at(-1)!.id,time:rows.at(-1)!.time}:null}});
 });
 await page.goto('http://127.0.0.1:5174');await tab(page,'Activity');await expect(page.locator('.access-activity-row')).toHaveCount(30);await expect(page.locator('.access-activity-group').first().getByRole('heading')).toContainText('10 October 2026');
 failNext=true;await page.locator('.access-activity-load').scrollIntoViewIfNeeded();await expect(page.locator('.access-activity-load').getByRole('alert')).toContainText('Could not load logs');await page.locator('.access-activity-load').getByRole('button',{name:'Retry',exact:true}).click();await expect(page.locator('.access-activity-row')).toHaveCount(60);expect(requests[1].cursor).toEqual(requests[2].cursor);
 await page.getByLabel('From date',{exact:true}).fill('2026-09-29');await page.getByLabel('To date',{exact:true}).fill('2026-09-30');await page.getByRole('button',{name:'Show logs',exact:true}).click();await expect(page.locator('.access-activity-row')).toHaveCount(27);await expect(page.locator('.access-activity')).toContainText('Log 244');await expect(page.locator('.access-activity')).not.toContainText('Log 0');await expect(page.locator('.access-activity-group')).toHaveCount(2);await expect(page.locator('.access-activity')).toContainText('All logs shown');
 await page.getByLabel('From date',{exact:true}).fill('2020-01-01');await page.getByLabel('To date',{exact:true}).fill('2020-01-02');await page.getByRole('button',{name:'Show logs',exact:true}).click();await expect(page.locator('.access-activity')).toContainText('No logs in this date range');await page.getByRole('button',{name:'Clear dates',exact:true}).click();await expect(page.locator('.access-activity-row')).toHaveCount(30);await page.screenshot({path:`artifacts/admin-activity-${info.project.name}.png`,fullPage:true});
});
