import {useState} from "react";
import {useLanguage,PinInput,InlineError} from "@onebite/ui";
import {validStaffPin} from "@onebite/core/access";
export function AuthForm({mode,busy,error,onSubmit}:{mode:"setup"|"change-pin"|"login";busy:boolean;error:string;onSubmit:(payload:Record<string,unknown>)=>Promise<void>}){
 const {t}=useLanguage();const [name,setName]=useState(""),[username,setUsername]=useState(""),[pin,setPin]=useState(""),[confirmation,setConfirmation]=useState(""),[code,setCode]=useState(""),[current,setCurrent]=useState("");
 const [activePin,setActivePin]=useState<"current"|"new"|"confirmation">(mode==="change-pin"?"current":"new");
 const setup=mode==="setup",change=mode==="change-pin";const valid=(setup||change?validStaffPin(pin):/^[0-9]{6}$/.test(pin))&&(!setup&&!change||pin===confirmation)&&(!setup||(name.trim()&&/^[a-f0-9]{64}$/.test(code)))&&(!change||/^[0-9]{6}$/.test(current));
 return <form className="access-form" onSubmit={e=>{e.preventDefault();if(valid&&!busy)void onSubmit({...(!change?{username}:{}),pin,...(setup?{name,setup_code:code}:{}),...(change?{current_pin:current}:{})});}}><h1>{setup?t("បង្កើតគណនីម្ចាស់","Set up the first Owner"):change?t("ប្ដូរ PIN របស់អ្នក","Choose your own PIN"):t("សូមស្វាគមន៍","Welcome back")}</h1><p>{setup?t("ប្រើកូដបង្កើតម្ចាស់មួយដង ដើម្បីការពារគណនីដំបូង។","Use your one-time setup code to protect the first Owner account."):change?t("អ្នកត្រូវប្ដូរ PIN បណ្ដោះអាសន្ន មុនបន្ត។","Change your temporary PIN before continuing."):t("ចូលគណនីផ្ទាល់ខ្លួន ដោយឈ្មោះអ្នកប្រើ និង PIN។","Sign in with your individual username and PIN.")}</p>{setup&&<><label>{t("កូដបង្កើតម្ចាស់","One-time setup code")}<input className="d-input" value={code} type="password" autoComplete="off" onChange={e=>setCode(e.target.value.trim())}/></label><label>{t("ឈ្មោះពេញ","Full name")}<input className="d-input" maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label></>}{!change&&<label>{t("ឈ្មោះអ្នកប្រើ","Username")}<input className="d-input" autoComplete="username" autoCapitalize="none" autoCorrect="off" value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} required/></label>}{change&&<PinInput label={t("PIN បច្ចុប្បន្ន","Current PIN")} value={current} onChange={setCurrent} active={activePin==="current"} onActivate={()=>setActivePin("current")} disabled={busy}/>}<PinInput label={change?t("PIN ថ្មី 6 ខ្ទង់","New 6-digit PIN"):t("លេខ PIN 6 ខ្ទង់","6-digit PIN")} value={pin} onChange={setPin} autoComplete={setup||change?"new-password":"current-password"} active={activePin==="new"} onActivate={()=>setActivePin("new")} disabled={busy}/>{(setup||change)&&<PinInput label={t("បញ្ជាក់ PIN","Confirm PIN")} value={confirmation} onChange={setConfirmation} autoComplete="new-password" active={activePin==="confirmation"} onActivate={()=>setActivePin("confirmation")} disabled={busy}/>}<InlineError message={error}/><button className="d-btn d-btn-primary access-btn" disabled={!valid||busy}>{busy?t("កំពុងដំណើរការ…","Working…"):setup?t("បង្កើតម្ចាស់","Create Owner"):change?t("រក្សាទុក PIN ថ្មី","Save new PIN"):t("ចូលគណនី","Sign in")}</button></form>;
}
