const icons = await fetch('icons.json').then(r=>r.json());
let lang = 'km';
const I = name => icons[name] || '';
const T = (km,en) => lang === 'km' ? km : en;
const amount = n => `៛ ${n.toLocaleString('en-US')}`;
const button = (label,style='',icon='',attrs='') => `<button class="btn ${style}" ${attrs}>${icon?I(icon):''}${label}</button>`;
const badge = (label,tone='',icon='') => `<span class="badge ${tone}">${icon?I(icon):''}${label}</span>`;
const field = (label,value='',extra='',hint='') => `<label class="field ${extra.includes('data-discount')?'discount-field':''}"><span class="field-label">${label}</span><input value="${value}" ${extra}>${hint?`<span class="hint">${hint}</span>`:''}</label>`;
const choice = (label,name,checked=false,price='',checkbox=false,icon='') => `<label class="choice ${checkbox?'check':''}">${icon?I(icon):''}<input type="${checkbox?'checkbox':'radio'}" name="${name}" ${checked?'checked':''}><span class="choice-dot">${I('Check')}</span><span>${label}</span>${price?`<span class="price">${price}</span>`:''}</label>`;
const quantity = (value=2,name='box') => `<div class="quantity" data-quantity="${name}"><button data-step="-1" aria-label="${T('បន្ថយចំនួន','Decrease quantity')}" ${value===1?'disabled':''}>${I('Minus')}</button><output>${value}</output><button data-step="1" aria-label="${T('បន្ថែមចំនួន','Increase quantity')}">${I('Plus')}</button></div>`;
const banner = (title,desc,tone='warning',icon='WifiOff') => `<div class="banner ${tone}">${I(icon)}<div><strong>${title}</strong><p>${desc}</p></div></div>`;
const row = (name,detail,value,icon='Users') => `<div class="data-row"><span class="avatar">${I(icon)}</span><div><strong>${name}</strong><p>${detail}</p></div><span class="row-value">${value}</span></div>`;
const food = type => `<div class="food-illustration"><svg viewBox="0 0 150 70" aria-hidden="true">${type==='tea'?'<path d="M54 8h43l-5 53H59z" fill="#e9c57e" stroke="#b58341" stroke-width="2"/><path d="M79 2l-6 47" stroke="#436040" stroke-width="4"/><circle cx="95" cy="25" r="12" fill="#f4d55d" stroke="#bda151" stroke-width="2"/><path d="M85 25h20m-10-10v20" stroke="#fff0a9" stroke-width="2"/>':type==='balls'?'<ellipse cx="75" cy="56" rx="53" ry="8" fill="#e8d9c0"/><g fill="#bd814b" stroke="#915c31" stroke-width="2"><circle cx="45" cy="39" r="16"/><circle cx="75" cy="25" r="16"/><circle cx="104" cy="39" r="16"/><circle cx="75" cy="48" r="16"/></g><path d="M38 32l8-4m22-9l8-3m23 14l8-3" stroke="#e5b987" stroke-width="3"/>':'<ellipse cx="75" cy="54" rx="56" ry="9" fill="#e8d9c0"/><g fill="#edc58b" stroke="#bd884b" stroke-width="2"><path d="M18 43q17-45 34 0q-16 12-34 0z"/><path d="M53 43q17-45 34 0q-16 12-34 0z"/><path d="M88 43q17-45 34 0q-16 12-34 0z"/></g><path d="M31 29v12m7-16v16m27-12v12m7-16v16m27-12v12m7-16v16" stroke="#bd884b" stroke-width="2"/>'}</svg></div>`;
const product = (name,detail,price,type) => `<button class="product" data-toast="${T('បានជ្រើសមុខម្ហូប · សាកល្បង UI','Item selected · UI demo')}">${food(type)}<span class="product-name">${name}</span><span class="product-meta">${detail}</span><span class="product-price">${amount(price)}<span class="add-square">${I('Plus')}</span></span></button>`;
const total = () => `<div class="total-card"><div class="total-row"><span>${T('មុខម្ហូប','Items')}</span><span>${amount(14000)}</span></div><div class="total-row"><span>${T('បញ្ចុះតម្លៃ','Discount')}</span><span>៛ 0</span></div><div class="total-row"><span>${T('បង្គត់','Rounding')}</span><span>៛ 0</span></div><div class="total-main"><span>${T('សរុបត្រូវបង់','Total due')}</span><strong>${amount(14000)}</strong></div><div class="currency-helper">≈ $3.50 · 1 USD = ៛ 4,000</div></div>`;
const miniNav = (admin=false) => `<nav class="mini-nav" aria-label="${admin?'Admin':'POS'} navigation specimen">${(admin?['LayoutGrid','Store','Users','Settings2']:['ShoppingBag','Clock3','ReceiptText','Wallet']).map((icon,n)=>`<button ${n===0?'aria-current="page"':''} data-nav>${I(icon)}<span>${admin?[T('សង្ខេប','Overview'),T('សាខា','Sites'),T('បុគ្គលិក','Team'),T('កំណត់','Settings')][n]:[T('លក់','Sell'),T('ទុកសិន','Held'),T('វិក្កយបត្រ','Invoices'),T('វេន','Shift')][n]}</span></button>`).join('')}</nav>`;
const specs = () => [
{id:'foundations',name:'Foundations',icon:'Palette',desc:'The original brand, translated into a working UI.',cards:[
['Brand palette','FND / 01',`<div class="swatches">${[['Orange','#F57921'],['Ink','#1A1A1A'],['White','#FFFFFF'],['Canvas','#FFF9F4'],['Soft orange','#FFF3E8'],['Text orange','#A94800'],['Muted','#66615C'],['Border','#E7DDD4']].map(([name,color])=>`<div class="swatch"><div style="background:${color}"></div><strong>${name}</strong><code>${color}</code></div>`).join('')}</div>`,'Exact logo orange · Semantic UI colors','wide'],
['Google Sans','FND / 02',`<div class="type-spec"><p class="type-display">${T('សូមស្វាគមន៍','Welcome to OneBite')}</p><p class="type-body">${T('ជ្រើសរើសមុខម្ហូប','Choose something delicious.')}</p><p class="type-display">៛ 15,000</p><p class="type-caption">Body 16/28 · Labels 14/24<br>Google Sans · Khmer + Latin</p></div>`,'Official locally loaded font · Weights 400–700'],
['Spacing & shape','FND / 03',`<div class="token-pills">${[4,8,12,16,24,32].map(v=>`<span class="token-pill">${v}px</span>`).join('')}</div><div class="radius-examples"><div style="border-radius:12px">12</div><div style="border-radius:16px">16</div><div style="border-radius:24px">24</div></div><span class="hint">48px ${T('ទំហំប៉ះអប្បបរមា','minimum touch target')}</span>`,'4px grid · Inputs 12 · Cards 16 · Sheets 24']
]},
{id:'actions',name:'Buttons & actions',icon:'ArrowUpRight',desc:'One clear action. A consistent response.',cards:[
['Primary & secondary','BTN / 01',button(T('បង់ប្រាក់','Pay'),'','ArrowUpRight','data-demo="payment"')+button(T('ទុកកន្ត្រកនេះសិន','Hold this cart'),'secondary','Clock3','data-toast="UI demo · Cart held"')+button(T('បោះបង់','Cancel'),'quiet','','data-demo="cancel"'),'Dark labels on exact brand orange · 6.33:1 contrast'],
['Interaction states','BTN / 02',`<span class="demo-label">Pressed</span>${button(T('បង់ប្រាក់','Pay'),'pressed','Check','data-toast="UI demo · Pressed state"')}<span class="demo-label">Disabled</span>${button(T('បង់ប្រាក់','Pay'),'','','disabled')}<span class="demo-label">Loading</span>${button(T('កំពុងរក្សាទុក','Saving'),'loading','LoaderCircle','aria-busy="true" disabled')}`,'Default · Pressed · Disabled · Loading'],
['Icons & destructive action','BTN / 03',`<div class="pair"><button class="icon-button" aria-label="Add" data-toast="UI demo · Add">${I('Plus')}</button><button class="icon-button" aria-label="Close" data-toast="UI demo · Close">${I('X')}</button><button class="icon-button" aria-label="More" data-toast="UI demo · More">${I('MoreHorizontal')}</button></div>${button(T('បោះបង់វិក្កយបត្រ','Cancel invoice'),'danger','X','data-demo="cancel"')}<span class="hint">${T('តែវិក្កយបត្រមិនទាន់បង់','Unpaid invoices only')}</span>`,'48px icon targets · Reason required for cancellation']
]},
{id:'inputs',name:'Inputs & selection',icon:'SlidersHorizontal',desc:'Clear labels, visible selection, helpful limits.',cards:[
['Account & money inputs','INP / 01',field(T('ឈ្មោះអ្នកប្រើ','Username'),'sokha','autocomplete="off"')+`<div class="field"><span class="field-label">${T('លេខ PIN','6-digit PIN')}</span><div class="pin-row" aria-label="Six masked PIN digits">${'<span>•</span>'.repeat(6)}</div></div>`+field(T('ចំនួនទឹកប្រាក់','Amount'),'20,000','inputmode="decimal"',T('កត់ត្រាសរុបស្មើជារៀល','Record the equivalent KHR total')),'Labelled fields · Individual accounts'],
['Discount limit','INP / 02',field(T('បញ្ចុះតម្លៃលើមុខម្ហូប · %','Item discount · %'),'10','type="number" min="0" max="15" step="0.5" data-discount',T('អតិបរមា 15% · មិនអាចរំលង','Maximum 15% · No override'))+`<span class="hint error" data-discount-error hidden>${T('លើសកម្រិតអនុញ្ញាត 15%','Exceeds the 15% limit')}</span>`+button(T('អនុវត្ត','Apply'),'','','data-apply-discount')+`<span class="hint">${T('ចំនួនថេរអនុវត្តក្នុងមួយឯកតា','Fixed discounts apply per sold unit')}</span>`,'Try 16% to see the hard-limit error'],
['Preferences','INP / 03',`<div class="switch-line"><span>${T('អនុញ្ញាតបង់ប្រាក់ចែក','Allow split payments')}</span><button class="switch" role="switch" aria-label="Allow split payments" aria-checked="true"><span></span></button></div><div class="segmented" role="tablist" aria-label="Language specimen"><button role="tab" aria-selected="true" data-segment>ខ្មែរ</button><button role="tab" aria-selected="false" data-segment>English</button></div>${field(T('សាខា','Site'),'Site 01 · ទួលទំពូង','readonly')}`,'Owner setting specimen · Language and site controls'],
['Required sauce','SEL / 01',`<div class="choices">${choice(T('ដើម · លំនាំដើម','Original · Default'),'sauce',true,T('ឥតគិតថ្លៃ','Included'))}${choice(T('ម្ទេស','Chilly'),'sauce',false,T('ឥតគិតថ្លៃ','Included'))}${choice(T('ស៊ីឈួន','Sichuan'),'sauce',false,'+៛ 500')}</div><span class="hint">${T('ត្រូវជ្រើស · ម្ចាស់កំណត់មុខម្ហូបដែលអនុញ្ញាត','Required · Owner sets item eligibility')}</span>`,'Mock prices · One required base sauce'],
['Extra sauce','SEL / 02',`<div class="choices">${choice(T('ដើម','Original'),'extra-original',false,'+៛ 500',true)}${choice(T('ម្ទេស','Chilly'),'extra-chilly',false,'+៛ 500',true)}${choice(T('ស៊ីឈួន','Sichuan'),'extra-sichuan',true,'+៛ 1,000',true)}</div>`,'Independent extra selections · Mock per-sauce prices'],
['Quantity stepper','SEL / 03',`<div class="pair" style="justify-content:center">${quantity()}</div><div class="unit-note" data-unit-note>2 × 5 = 10 ${T('គ្រាប់','dumplings')}</div><span class="hint">${T('ចំនួនប្រអប់ និងឯកតាគោល ត្រូវបានបង្ហាញច្បាស់','Sold boxes and base units stay distinct')}</span>`,'Minimum 1 · Touch controls are 48px']
]},
{id:'ordering',name:'Ordering & cart',icon:'ShoppingBag',desc:'Food choices that are quick to scan and easy to customize.',cards:[
['Dumpling menu card','PRD / 01',product(T('គាវចៀន','Fried dumplings'),T('ប្រអប់តូច · 5 គ្រាប់','Small box · 5 dumplings'),5000,'dumplings'),'Menu tile · Mock site price'],
['Meatball menu card','PRD / 02',product(T('ប្រហិតចៀន','Fried meatballs'),T('ប្រអប់ធំ · 20 គ្រាប់','Large box · 20 meatballs'),9000,'balls'),'Menu tile · Mock site price'],
['Tea menu card','PRD / 03',product(T('តែក្រូចឆ្មា','Lemon tea'),T('ទំហំតែមួយ','One size'),4000,'tea'),'Menu tile · Mock site price'],
['Cart line','CRT / 01',`<div class="cart-line"><div class="line-top"><span>${T('គាវចៀន · ប្រអប់តូច','Dumplings · Small')}</span><strong data-line-price>៛ 10,000</strong></div><div class="line-detail">${T('ទឹកជ្រលក់ដើម','Original sauce')}</div><div class="line-bottom">${quantity(2,'line')}<button class="small-button" data-toast="UI demo · Item discount">10% ${I('ChevronDown')}</button></div></div><span class="hint">${T('តម្លៃរួមទឹកជ្រលក់ និងបន្ថែម','Discounts include sauce and extras')}</span>`,'Quantity × unit price · Item discount affordance'],
['Complimentary line','CRT / 02',`<div class="cart-line"><div class="line-top"><span>${T('គាវចៀន · ប្រអប់តូច','Dumplings · Small')}</span><strong>៛ 0</strong></div><div class="line-detail">${T('ស៊ីឈួន + ទឹកជ្រលក់បន្ថែម','Sichuan + extra sauce')} · × 1</div>${badge(T('ឥតគិតថ្លៃ · 5 គ្រាប់','Complimentary · 5 units'),'brand','Gift')}</div><span class="hint">${T('បើឥតគិតថ្លៃ គ្រប់បន្ថែមក៏ឥតគិតថ្លៃ','Sauce and extras are also free')}</span>`,'Consumes base-unit allowance · Final item amount zero'],
['Blank cart','CRT / 03',`<div class="empty"><div class="empty-icon">${I('ShoppingBag')}</div><h4>${T('កន្ត្រកទំនេរ','Your cart is empty')}</h4><p>${T('ជ្រើសរើសមុខម្ហូប ដើម្បីចាប់ផ្ដើម','Choose an item to start an order.')}</p></div>`,'Every fresh cart starts empty']
]},
{id:'payment',name:'Payment & totals',icon:'Wallet',desc:'Amounts take priority. Every completion is explicit.',cards:[
['Receipt total','PAY / 01',total()+button(T('បង់ប្រាក់ · ៛ 14,000','Pay · ៛ 14,000'),'','ArrowUpRight','data-demo="payment"'),'Final total rounded to KHR 100 · Sample rate 4,000'],
['Cash & QR choices','PAY / 02',`<div class="choices">${choice(T('ប្រាក់សុទ្ធ','Cash'),'payment',true,'',false,'Banknote')}${choice('QR Payment','payment',false,'',false,'QrCode')}</div><div class="hint">ABA Bank · Bakong KHQR<br>${T('បុគ្គលិកកត់ត្រាបានទទួល','Receipt manually recorded by staff')}</div>`,'No automatic bank verification'],
['Photo & free completion','PAY / 03',`<button class="photo-tile" data-toast="UI demo · Optional QR reference photo">${I('Camera')}${T('រូបថតយោង · មិនចាំបាច់','Reference photo · Optional')}</button>${button(T('បញ្ចប់ការបញ្ជាទិញឥតគិតថ្លៃ','Complete free order'),'secondary','Gift','data-toast="UI demo · Free order complete"')}<span class="hint">${T('សរុប ៛ 0 · គ្មានវិធីបង់ប្រាក់','Zero total · No payment method')}</span>`,'Optional attachment · Free orders need no tender']
]},
{id:'status',name:'Status & guardrails',icon:'ShieldCheck',desc:'Show what is happening and what needs attention.',cards:[
['Status badges','STS / 01',`<div class="stage-row" style="display:flex;gap:8px;flex-wrap:wrap">${badge(T('បានភ្ជាប់','Online'),'success','Wifi')}${badge(T('បានបង់','Paid'),'success','Check')}${badge(T('មិនទាន់បង់','Unpaid'),'warning','Clock3')}${badge(T('ឥតគិតថ្លៃ','Free'),'brand','Gift')}${badge(T('បានចាក់សោ','Locked'),'','LockKeyhole')}${badge(T('ខ្វះ ៛ 500','Short ៛ 500'),'danger','CircleAlert')}</div>`,'Color + words + icons · No color-only status'],
['Offline states','STS / 02',banner(T('Offline · នៅសល់ 18 ម៉ោង','Offline · 18 hours left'),T('4 វិក្កយបត្ររង់ចាំផ្ញើ','4 saved invoices waiting to sync'))+banner(T('លើសកម្រិត 24 ម៉ោង','24-hour limit reached'),T('ភ្ជាប់ និងធ្វើសមកាលកម្ម ដើម្បីបន្តលក់','Reconnect and fully sync to resume ordering'),'danger','LockKeyhole'),'Preserve queued data · Handover and withdrawals require online'],
['Complimentary allowance','STS / 03',`<div class="allowance"><div class="allowance-top"><h4>${T('ចំនួនអនុញ្ញាត · គាវ','Dumpling allowance')}</h4>${I('Gift')}</div><strong>15 <small style="font-size:12px;font-weight:400">${T('គ្រាប់នៅសល់','units left')}</small></strong><div class="progress"><span></span></div><div class="pair">${quantity(2,'free')}</div><p data-free-note>2 × 5 = 10 ${T('គ្រាប់','units')}</p></div>${button(T('ផ្ដល់ឥតគិតថ្លៃ','Make complimentary'),'secondary','','data-free-action')}`,'Try 4 boxes: 20 units exceeds the 15-unit remainder']
]},
{id:'navigation',name:'Navigation & data',icon:'LayoutGrid',desc:'A familiar home across separately installable apps.',cards:[
['POS navigation','NAV / 01',miniNav()+row(T('កន្ត្រក #H03','Held cart #H03'),'10:42 · 2 '+T('មុខ','items'),'14k','Clock3'),'Sell · Held · Invoices · Shift'],
['Admin navigation','NAV / 02',miniNav(true)+row(T('សុខា','Sokha'),T('អ្នកគិតលុយ · សាខា 01','Cashier · Site 01'),'›','Users'),'Overview · Sites · Team · Settings'],
['Site & sales metric','NAV / 03',`<div class="metric"><p>${T('ការលក់ថ្ងៃនេះ','Today’s sales')}</p><strong>៛ 165,000</strong><span>18 ${T('វិក្កយបត្រ','invoices')} · ${T('សាខា 01','Site 01')}</span></div>`+row(T('សាខា 01','Site 01'),T('វេនរួម · សុខា + ដារ៉ា','Shared shift · Sokha + Dara'),'✓','Store'),'Sample operational values']
]},
{id:'confirmations',name:'Confirmation & feedback',icon:'CircleCheck',desc:'Cash responsibility stays visible between people.',cards:[
['Two-person cash handover','CFM / 01',`<div class="confirm-card"><h4>${T('ផ្ទេរវេន','Shift handover')}</h4><div class="total-row"><span>${T('ប្រាក់ជាក់ស្ដែង','Actual cash')}</span><strong>៛ 109,500</strong></div>${badge(T('ខ្វះ ៛ 500','Shortage ៛ 500'),'warning','CircleAlert')}<div class="actor"><span>${T('អ្នកផ្ទេរ · សុខា','Outgoing · Sokha')}</span>${badge(T('បានបញ្ជាក់','Confirmed'),'success','Check')}</div><div class="actor"><span>${T('អ្នកទទួល · ស្រីនាង','Incoming · Sreynang')}</span>${badge(T('រង់ចាំ','Pending'),'warning','Clock3')}</div></div>${button(T('មើលការបញ្ជាក់','Preview confirmation'),'secondary','','data-demo="handover"')}`,'Expected 110,000 · Both confirm actual 109,500'],
['Withdrawal & paid lock','CFM / 02',row(T('ដកប្រាក់ ៛ 20,000','Withdraw ៛ 20,000'),T('អ្នករក្សា + អ្នកត្រួតពិនិត្យ / ម្ចាស់','Holder + Supervisor / Owner'),'2','Wallet')+banner(T('វិក្កយបត្របានបង់ត្រូវបានចាក់សោ','Paid invoice is locked'),T('មិនអាចបោះបង់ ឬសងប្រាក់វិញ','No cancellation or refund'),'warning','LockKeyhole'),'Two distinct actors confirm withdrawals'],
['Saved & loading feedback','CFM / 03',banner(T('បានរក្សាទុក','Saved on this device'),T('រង់ចាំផ្ញើពេលបានភ្ជាប់','Waiting to sync when online'),'success','CircleCheck')+`<div class="skeleton card" aria-label="Loading card specimen"></div><div class="skeleton short"></div>`+button(T('មើលសារជោគជ័យ','Preview success message'),'quiet','','data-toast="UI demo · Saved on this device"'),'Durable-save feedback specimen · Reduced-motion support']
]}
];
function render(){
 const sections=specs();
 document.documentElement.lang=lang;
 document.querySelector('#language').textContent=lang==='km'?'English':'ខ្មែរ';
 document.querySelector('#search-icon').innerHTML=I('Search');
 document.querySelector('#sidebar-nav').innerHTML=sections.map((s,i)=>`<a class="nav-link ${i===0?'active':''}" href="#${s.id}">${I(s.icon)}<span>${s.name}</span></a>`).join('');
 document.querySelector('#gallery').innerHTML=sections.map((s,i)=>`<section class="collection" id="${s.id}"><div class="section-heading"><div class="section-title"><span class="section-number">0${i+1}</span><h2>${s.name}</h2></div><p>${s.desc}</p></div><div class="grid">${s.cards.map(([title,id,body,caption,size=''])=>`<article class="specimen ${size}" data-search="${(title+' '+caption+' '+s.name).toLowerCase()}"><header class="specimen-header"><h3>${title}</h3><span>${id}</span></header><div class="stage">${body}</div><div class="specimen-caption">${caption}</div></article>`).join('')}</div></section>`).join('');
 document.querySelectorAll('.btn.loading svg').forEach(n=>n.classList.add('spin'));
 filter();
}
function filter(){const q=document.querySelector('#search').value.trim().toLowerCase();let count=0;document.querySelectorAll('.specimen').forEach(n=>{n.hidden=Boolean(q&&!n.dataset.search.includes(q)&&!n.textContent.toLowerCase().includes(q));if(!n.hidden)count++;});document.querySelectorAll('.collection').forEach(n=>n.hidden=!n.querySelector('.specimen:not([hidden])'));document.querySelector('#component-count').textContent=`${count} components`;}
let toastTimer;
function toast(message){const n=document.querySelector('#toast');n.innerHTML=I('CircleCheck')+`<span></span>`;n.querySelector('span').textContent=message;n.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>n.classList.remove('visible'),3000);}
function openDemo(type){const dialog=document.querySelector('#demo-dialog');let body,title;
 if(type==='payment'){title=T('បញ្ជាក់ការទូទាត់','Confirm payment');body=total()+choice(T('ប្រាក់សុទ្ធ','Cash'),'demo-payment',true,'',false,'Banknote')+choice('QR Payment','demo-payment',false,'',false,'QrCode')+button(T('បញ្ជាក់បានទទួល','Confirm received'),'','Check','data-finish-demo');}
 if(type==='cancel'){title=T('បោះបង់វិក្កយបត្រ','Cancel unpaid invoice');body=badge(T('មិនទាន់បង់ · #OB-01040','Unpaid · #OB-01040'),'warning','Clock3')+field(T('មូលហេតុ · ត្រូវបញ្ចូល','Reason · Required'),'','data-cancel-reason',T('ស្ដារចំនួនឥតគិតថ្លៃដែលបានរក្សា','Reserved complimentary units are restored'))+button(T('បញ្ជាក់ការបោះបង់','Confirm cancellation'),'danger','X','data-confirm-cancel disabled');}
 if(type==='handover'){title=T('បញ្ជាក់ប្រាក់ជាក់ស្ដែង','Confirm actual cash');body=field(T('ប្រាក់ជាក់ស្ដែង','Actual KHR-equivalent cash'),'109,500','readonly')+banner(T('ខ្វះ ៛ 500','Shortage ៛ 500'),T('ធៀបនឹងសមតុល្យ ៛ 110,000','Compared with expected ៛ 110,000'),'warning','CircleAlert')+`<div class="actor"><span>Sokha · ${T('អ្នកផ្ទេរ','Outgoing')}</span><button class="small-button" data-actor="outgoing">${T('បញ្ជាក់','Confirm')}</button></div><div class="actor"><span>Sreynang · ${T('អ្នកទទួល','Incoming')}</span><button class="small-button" data-actor="incoming">${T('បញ្ជាក់','Confirm')}</button></div>`+button(T('ផ្ទេរវេន','Transfer shift'),'','','data-transfer disabled');}
 document.querySelector('#dialog-content').innerHTML=`<div class="dialog-inner"><div class="dialog-header"><h3>${title}</h3><button class="icon-button" aria-label="Close dialog" data-close>${I('X')}</button></div><p class="dialog-note">${T('សាកល្បង UI តែប៉ុណ្ណោះ · មិនកត់ត្រាប្រតិបត្តិការពិត','UI specimen only · No real transaction is recorded')}</p>${body}</div>`;
 dialog.showModal();
}
document.addEventListener('click',event=>{
 const b=event.target.closest('button');if(!b||b.disabled)return;
 if(b.id==='language'){lang=lang==='km'?'en':'km';render();}
 if(b.id==='phone-mode'){const active=document.body.classList.toggle('phone-review');b.setAttribute('aria-pressed',String(active));b.innerHTML=I(active?'Monitor':'Smartphone')+(active?'Desktop view':'Phone view');}
 if(b.dataset.toast)toast(b.dataset.toast);
 if(b.dataset.demo)openDemo(b.dataset.demo);
 if(b.hasAttribute('data-close'))document.querySelector('#demo-dialog').close();
 if(b.hasAttribute('data-finish-demo')){document.querySelector('#demo-dialog').close();toast(T('ការបញ្ជាក់ UI រួចរាល់','UI confirmation complete'));}
 if(b.classList.contains('switch'))b.setAttribute('aria-checked',b.getAttribute('aria-checked')==='true'?'false':'true');
 if(b.hasAttribute('data-segment')){b.parentElement.querySelectorAll('button').forEach(n=>n.setAttribute('aria-selected',String(n===b)));}
 if(b.hasAttribute('data-nav')){b.parentElement.querySelectorAll('button').forEach(n=>n.removeAttribute('aria-current'));b.setAttribute('aria-current','page');}
 if(b.dataset.step){const q=b.closest('[data-quantity]');const output=q.querySelector('output');const value=Math.max(1,Math.min(99,Number(output.value)+Number(b.dataset.step)));output.value=value;output.textContent=value;q.querySelector('[data-step="-1"]').disabled=value<=1;const card=q.closest('.specimen');if(q.dataset.quantity==='box')card.querySelector('[data-unit-note]').textContent=`${value} × 5 = ${value*5} ${T('គ្រាប់','dumplings')}`;if(q.dataset.quantity==='line')card.querySelector('[data-line-price]').textContent=amount(value*5000);if(q.dataset.quantity==='free'){const allowed=value*5<=15;card.querySelector('[data-free-note]').textContent=`${value} × 5 = ${value*5} ${T('គ្រាប់','units')}${allowed?'':T(' · នៅសល់មិនគ្រប់',' · Insufficient allowance')}`;card.querySelector('[data-free-note]').style.color=allowed?'':'var(--danger)';card.querySelector('[data-free-action]').disabled=!allowed;}}
 if(b.hasAttribute('data-apply-discount'))toast(T('បានអនុវត្ត · សាកល្បង UI','Discount applied · UI demo'));
 if(b.hasAttribute('data-free-action'))toast(T('បានជ្រើសឥតគិតថ្លៃ · សាកល្បង UI','Complimentary selected · UI demo'));
 if(b.dataset.actor){b.dataset.confirmed='true';b.textContent=T('បានបញ្ជាក់','Confirmed');b.disabled=true;const ready=[...document.querySelectorAll('[data-actor]')].every(n=>n.dataset.confirmed==='true');document.querySelector('[data-transfer]').disabled=!ready;}
 if(b.hasAttribute('data-transfer')||b.hasAttribute('data-confirm-cancel')){document.querySelector('#demo-dialog').close();toast(T('ការបញ្ជាក់ UI រួចរាល់','UI confirmation complete'));}
});
document.addEventListener('input',event=>{const n=event.target;if(n.id==='search')filter();if(n.hasAttribute('data-discount')){const value=Number(n.value);const valid=n.value.trim()!==''&&Number.isFinite(value)&&value>=0&&value<=15;const card=n.closest('.specimen');n.setAttribute('aria-invalid',String(!valid));n.closest('.field').classList.toggle('error',!valid);card.querySelector('[data-discount-error]').hidden=valid;card.querySelector('[data-apply-discount]').disabled=!valid;}if(n.hasAttribute('data-cancel-reason'))document.querySelector('[data-confirm-cancel]').disabled=!n.value.trim();});
document.addEventListener('keydown',event=>{if(event.key==='/'&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName)){event.preventDefault();document.querySelector('#search').focus();}});
document.querySelector('#sidebar-nav').addEventListener('click',event=>{const link=event.target.closest('a');if(link)document.querySelectorAll('.nav-link').forEach(n=>n.classList.toggle('active',n===link));});
document.querySelector('#demo-dialog').addEventListener('click',event=>{if(event.target===event.currentTarget)event.currentTarget.close();});
render();
