import {useEffect,useState} from 'react';
import {Camera,Check,Plus,Trash2} from 'lucide-react';
import {AppDialog,InlineError,SelectField,SwitchField,useLanguage} from '@onebite/ui';
import {itemDefinition,itemTypes,validateCatalogItem,validateRecipe,type CatalogItem,type CatalogReference,type ReferenceKind} from '@onebite/core/inventory';
import {ActiveConfirmation,ReferenceSelect} from './CatalogReferences';
import {UnifiedRecipeEditor} from './UnifiedRecipeEditor';
import {prepareCatalogPhoto} from './photo';
export function CatalogEditor({item,catalog,photo,references,selectedReference,onCreateReference,onManageReferences,onClose,onSave}:{item:CatalogItem;catalog:CatalogItem[];photo?:string;references:CatalogReference[];selectedReference?:CatalogReference;onCreateReference:(kind:ReferenceKind)=>void;onManageReferences:(kind:ReferenceKind)=>void;onClose:()=>void;onSave:(item:CatalogItem,image?:string|null,confirmedActive?:boolean)=>Promise<void>}){
 const {t}=useLanguage(),[draft,setDraft]=useState(item),[image,setImage]=useState<string|null|undefined>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[photoBusy,setPhotoBusy]=useState(false);
 const [confirmActive,setConfirmActive]=useState<boolean|null>(null);
 const creating=item.revision===0,definition=itemDefinition(draft),material=definition.type==='raw_material'||definition.type==='supplies';
 useEffect(()=>{if(!selectedReference)return;const kind='sellable_category';
  if(selectedReference.kind===kind)setDraft(old=>({...old,category:selectedReference.value}));
  if(selectedReference.kind==='unit'&&item.revision===0)setDraft(old=>({...old,unit:selectedReference.value,packQuantity:null,packName:''}));
 },[selectedReference,item.kind,item.revision]);
 function update(value:Partial<CatalogItem>){setDraft(old=>({...old,...value}));}
 async function save(){setError('');setBusy(true);try{await onSave(validateRecipe(validateCatalogItem({...draft,active:creating?true:draft.active}),catalog),image,draft.active!==item.active);}catch(e){setError(e instanceof Error&&e.message==='invalid_recipe'?t('ពិនិត្យរូបមន្ត។ ជ្រើសសមាសធាតុដំណើរការ និងបរិមាណវិជ្ជមាន។','Check the recipe. Choose active components and positive quantities; pieces must be whole numbers.'):e instanceof Error&&e.message==='invalid_photo'?t('សូមជ្រើសរូបភាព JPG, PNG ឬ WebP មិនលើស 15 MB។','Choose a JPG, PNG or WebP image up to 15 MB.'):t('សូមពិនិត្យវាលព័ត៌មាន។ បរិមាណកញ្ចប់ត្រូវតែវិជ្ជមាន និងតម្លៃជារៀលត្រូវជាចំនួនគត់។','Check the fields. Pack quantities must be positive and KHR prices must be whole numbers.'));}finally{setBusy(false);}}
 return <><AppDialog title={creating?t('មុខទំនិញថ្មី','New item'):t('កែប្រែព័ត៌មាន','Edit item')} onClose={()=>{if(!busy&&!photoBusy)onClose();}} footer={<button form="catalog-editor" type="submit" className="d-btn d-btn-primary access-btn" disabled={busy||photoBusy}>{creating?<Plus size={18}/>:<Check size={18}/>} {busy?t('កំពុងរក្សាទុក…','Saving…'):creating?t('បង្កើត','Create item'):t('រក្សាទុក','Save changes')}</button>}>
  <form id="catalog-editor" className="access-form" onSubmit={event=>{event.preventDefault();void save();}}>
   <div className="inventory-photo-editor">{(image===undefined?photo:image)?<img src={(image===undefined?photo:image)!} alt={draft.name||t('រូបភាពមុខទំនិញ','Item photo')}/>:<Camera size={32}/>}
    <label className="d-btn d-btn-outline inventory-photo-choice"><Camera size={18}/>{photoBusy?t('កំពុងរៀបចំ…','Preparing…'):t('ជ្រើសរូបភាព','Choose photo')}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||photoBusy} onChange={async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setPhotoBusy(true);try{setImage(await prepareCatalogPhoto(file));setError('');}catch{setError(t('មិនអាចប្រើរូបភាពនេះ។ សូមជ្រើស JPG, PNG ឬ WebP មិនលើស 15 MB។','Could not use this image. Choose a JPG, PNG or WebP up to 15 MB.'));}finally{setPhotoBusy(false);}}}/></label>
    {(image===undefined?photo:image)&&<button type="button" className="d-btn d-btn-ghost" disabled={busy||photoBusy} onClick={()=>setImage(null)}><Trash2 size={17}/>{t('លុបរូបភាព','Remove photo')}</button>}
   </div>
   <label>{t('ឈ្មោះ','Name')}<input className="d-input" maxLength={100} value={draft.name} required disabled={busy} onChange={e=>update({name:e.target.value})}/></label>
   <label>{t('ឈ្មោះជាភាសាអង់គ្លេស (ជម្រើស)','English name (optional)')}<input className="d-input" maxLength={100} value={draft.nameEn} disabled={busy} onChange={e=>update({nameEn:e.target.value})}/></label>
   <label>{t('ប្រភេទមុខទំនិញ','Item type')}<SelectField presentation="dropdown" value={definition.type} disabled={busy} onChange={e=>update({definition:{...definition,type:e.target.value as typeof definition.type,lines:e.target.value==='raw_material'||e.target.value==='supplies'?[]:definition.lines}})}>{itemTypes.map(type=><option key={type} value={type}>{type==='finished_good'?t('ផលិតផលសម្រេច','Finished good'):type==='raw_material'?t('វត្ថុធាតុដើម','Raw material'):type==='supplies'?t('សម្ភារៈ','Supplies'):t('សមាសធាតុ','Component')}</option>)}</SelectField></label>
   <label className="inventory-toggle"><span>{t('អាចលក់','Can sell')}</span><SwitchField aria-label={t('អាចលក់','Can sell')} checked={definition.canSell} disabled={busy} onChange={e=>update({definition:{...definition,canSell:e.target.checked},priceKhr:e.target.checked?(draft.priceKhr??0):null})}/></label>
   <label>{t('ប្រភេទ','Category')}<ReferenceSelect kind="sellable_category" value={draft.category} references={references} disabled={busy} onChange={category=>update({category})} onCreate={onCreateReference} onManage={onManageReferences}/></label>
   <label>{t('ឯកតាមូលដ្ឋាន','Base unit')}<ReferenceSelect kind="unit" value={draft.unit} references={references} disabled={!creating||busy} onChange={unit=>update({unit,packQuantity:null,packName:''})} onCreate={onCreateReference} onManage={onManageReferences}/>{!creating&&<small>{t('ឯកតាត្រូវបានចាក់សោ ដើម្បីរក្សាបរិមាណឱ្យត្រឹមត្រូវ។','The base unit is locked after creation to keep quantities consistent.')}</small>}</label>
   {material&&<fieldset className="inventory-pack"><legend>{t('កញ្ចប់ស្នើសុំ (ជម្រើស)','Request pack (optional)')}</legend><label>{t('ឈ្មោះកញ្ចប់','Pack name')}<input className="d-input" value={draft.packName} maxLength={60} disabled={busy} onChange={e=>update({packName:e.target.value})}/></label><label>{t('បរិមាណក្នុងមួយកញ្ចប់','Quantity per pack')} ({draft.unit})<input className="d-input" type="number" inputMode="decimal" min={draft.unit==='pcs'?1:.001} max={1e9} step={draft.unit==='pcs'?1:.001} value={draft.packQuantity??''} disabled={busy} onChange={e=>update({packQuantity:e.target.value===''?null:Number(e.target.value)})}/></label><small>{t(`បញ្ចូលបរិមាណជា ${draft.unit}។ មិនបម្លែងឯកតាដោយស្វ័យប្រវត្តិទេ។`,`Enter the quantity in ${draft.unit}. Units are not converted automatically.`)}</small></fieldset>}
   {definition.canSell&&<label>{t('តម្លៃមេ (KHR)','Master price (KHR)')}<input aria-label={t("តម្លៃមេ (KHR)","Master price (KHR)")} className="d-input" type="number" inputMode="numeric" min={0} max={1e9} step={1} value={draft.priceKhr??''} required disabled={busy} onChange={e=>update({priceKhr:e.target.value===''?null:Number(e.target.value)})}/><small>{t('តម្លៃមេប្រើសម្រាប់គ្រប់សាខា។','The master price is inherited by all sites.')}</small></label>}
   <UnifiedRecipeEditor item={draft} catalog={catalog} disabled={busy} onChange={definition=>update({definition})}/>
   <label>{t('ការពិពណ៌នា (ជម្រើស)','Description (optional)')}<textarea className="d-textarea" rows={3} maxLength={2000} value={draft.description} disabled={busy} onChange={e=>update({description:e.target.value})}/></label>
   {!creating&&<label className="inventory-toggle"><span>{t('ដំណើរការ','Active')}</span><SwitchField aria-label={t('ដំណើរការ','Active')} checked={draft.active} disabled={busy} onChange={e=>setConfirmActive(e.target.checked)}/></label>}
   <InlineError message={error}/>
  </form>
 </AppDialog>{confirmActive!==null&&<ActiveConfirmation active={confirmActive} onClose={()=>setConfirmActive(null)} onConfirm={()=>{update({active:confirmActive});setConfirmActive(null);}}/>}</>;
}
