import {useState,useEffect} from 'react';
import {Boxes,ShoppingBag,LayoutGrid,RefreshCw,UserRound,ArrowUpRight,Clock3,Pencil,Check,AlertTriangle,Package,Leaf,ShieldCheck,Layers3} from 'lucide-react';
import {useScrollHidden,AppTitleBar,PageHeading,NewAction,DirectoryTools,DirectorySearch,DirectoryStatusFilter,CategoryFilter,EmptyState,ActiveStatusBadge,AppDialog,InlineError,useLanguage,useAppSettings,type DirectoryStatus} from '@onebite/ui';
import {AuthForm,MfaChallenge} from '@onebite/accounts';
import {newUnifiedItem,editUnifiedItem,itemDefinition,projectCatalog,projectReferences,newCatalogReference,type CatalogReference,type ReferenceKind,type CatalogItem} from '@onebite/core/inventory';
import {InventoryProfile} from './InventoryProfile';
import {ReferenceEditor,ReferenceManager,referenceLabel} from './CatalogReferences';
import {InventoryMessages} from './InventoryMessages';
import {UnifiedRecipeSummary} from './UnifiedRecipeEditor';
import {CatalogEditor} from './CatalogEditor';
import {useCatalog} from './useCatalog';
import icon from '../../../resources/app-icons/inventory.svg';
import logo from '../../../resources/brand/one-bite-logo-orange.svg';
import {version} from '../../../package.json';
type Tab='material'|'finished'|'sellable'|'sync'|'profile'|'hub';
export function InventoryApp(){
 const catalog=useCatalog(),{t,lang,setLang}=useLanguage(),{settings}=useAppSettings();
 const [tab,setTab]=useState<Tab>('sellable'),[search,setSearch]=useState(''),[status,setStatus]=useState<DirectoryStatus>('active'),[category,setCategory]=useState('all'),[editing,setEditing]=useState<CatalogItem|null>(null),[viewing,setViewing]=useState<CatalogItem|null>(null),[discarding,setDiscarding]=useState<string|null>(null),[discardBusy,setDiscardBusy]=useState(false);
 const [referenceEditing,setReferenceEditing]=useState<CatalogReference|null>(null),[referenceManaging,setReferenceManaging]=useState<ReferenceKind|null>(null),[selectedReference,setSelectedReference]=useState<CatalogReference>();
 const bottomHidden=useScrollHidden(tab);
 const [toast,setToast]=useState('');
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),3500);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{setEditing(null);setViewing(null);setDiscarding(null);setReferenceEditing(null);setReferenceManaging(null);setSelectedReference(undefined);setToast('');},[catalog.data?.actor.id]);
 const [themeChoice,setThemeChoice]=useState<string|null>(()=>{try{return localStorage.getItem('onebite-theme');}catch{return null;}});const dark=(themeChoice||settings.defaultTheme)==='dark';
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';},[dark]);
 function toggleTheme(){setThemeChoice(dark?'light':'dark');try{localStorage.setItem('onebite-theme',dark?'light':'dark');}catch{}}
 const text=(code:string)=>({client_update_required:t('ច្បាប់ចម្លងនេះមកពីកំណែចាស់។ ពិនិត្យ និងបង្កើតការផ្លាស់ប្ដូរថ្មី។','This saved change uses an older catalog format. Review its details before discarding and recreating the change.'),invalid_conversion:t('ពិនិត្យការបម្លែងឯកតារបស់មុខទំនិញ។','Check the item’s unit conversions.'),duplicate_reference:t('ឈ្មោះ ឬឯកតានេះមានរួចហើយ។ ពិនិត្យការផ្លាស់ប្ដូរ។','This category or UOM already exists. Review the pending change.'),inactive_reference:t('ប្រភេទ ឬឯកតាមិនដំណើរការ។ ពិនិត្យការផ្លាស់ប្ដូរ។','A selected category or UOM is inactive. Review the pending change.'),confirmation_required:t('ត្រូវបញ្ជាក់ការផ្លាស់ប្ដូរស្ថានភាព។','Confirm the active status change before saving.'),immutable_reference:t('និមិត្តសញ្ញាឯកតាមិនអាចផ្លាស់ប្ដូរ។','The reference value cannot be changed after creation.'),forbidden:t('អ្នកមិនមានសិទ្ធិចូលប្រើស្តុកទេ។ សូមទាក់ទងម្ចាស់។','Inventory access is not allowed. Contact an Owner.'),unauthorized:t('សូមចូលគណនីម្ដងទៀត។','Please sign in again.'),invalid_credentials:t('ឈ្មោះអ្នកប្រើ ឬ PIN មិនត្រឹមត្រូវ។','Incorrect username or PIN.'),invalid_pin:t('ជ្រើស PIN ថ្មី 6 ខ្ទង់ ដែលមិនងាយទាយ។','Choose a new six-digit PIN that is not a common sequence.'),login_throttled:t('សូមរង់ចាំមុនព្យាយាមម្ដងទៀត។','Please wait before retrying.'),network_failed:t('មិនអាចភ្ជាប់សេវា។ ពិនិត្យអ៊ីនធឺណិត។','Cannot reach the service. Check your connection.'),storage_failed:t('មិនអាចរក្សាទុកក្នុងឧបករណ៍នេះ។ ពិនិត្យទំហំផ្ទុក។','Could not save on this device. Check available storage.'),stale_revision:t('ព័ត៌មានបានផ្លាស់ប្ដូរលើឧបករណ៍ផ្សេង។ ពិនិត្យច្បាប់ចម្លង រួចបោះបង់ការផ្លាស់ប្ដូរចាស់ មុនកែម្ដងទៀត។','This item changed on another device. Review your saved copy, then discard the old change before editing the latest item.'),duplicate_item:t('ឈ្មោះនេះមានរួចហើយ។ បោះបង់ការផ្លាស់ប្ដូរ រួចប្រើឈ្មោះផ្សេង។','This name already exists. Discard the change, then use a different name.'),immutable_unit:t('ឯកតាមូលដ្ឋានមិនអាចផ្លាស់ប្ដូរបាន។','The base unit cannot be changed.'),offline_expired:t('ទិន្នន័យគ្មានបណ្ដាញមានអាយុលើស 24 ម៉ោង។ ភ្ជាប់ឡើងវិញដើម្បីបន្ត។','Saved authorization is over 24 hours old. Reconnect to continue.'),operation_conflict:t('ការផ្លាស់ប្ដូរនេះមានបញ្ហា។ ពិនិត្យច្បាប់ចម្លងមុនបោះបង់។','This change has a conflict. Review the saved copy before discarding it.'),photo_upload_failed:t('មិនអាចបង្ហោះរូបភាព។ ព្យាយាមធ្វើសមកាលកម្មម្ដងទៀត។','Photo upload failed. Retry syncing.'),invalid_recipe:t('រូបមន្តមិនត្រឹមត្រូវ។ ពិនិត្យសមាសធាតុ និងបរិមាណ។','Recipe is invalid. Check component availability and quantities.'),invalid_item:t('ព័ត៌មានមុខទំនិញមិនត្រឹមត្រូវ។ ពិនិត្យច្បាប់ចម្លង។','The item details are invalid. Review your saved copy.')}[code]||t('មិនអាចបញ្ចប់សំណើ។ ព្យាយាមម្ដងទៀត។','Could not complete the request. Please retry.'));
 const navigation=[{id:'material' as Tab,label:t('សម្ភារៈ','Materials'),icon:Boxes},{id:'sellable' as Tab,label:t('មុខទំនិញ','Items'),icon:ShoppingBag},{id:'sync' as Tab,label:t('ការផ្លាស់ប្ដូរ','Changes'),icon:RefreshCw},{id:'profile' as Tab,label:t('ប្រវត្តិរូប','Profile'),icon:UserRound},{id:'hub' as Tab,label:t('មជ្ឈមណ្ឌល','Hub'),icon:LayoutGrid}];
 function navigate(next:Tab){setTab(next);setSearch('');setCategory('all');setStatus('active');window.scrollTo({top:0});}
 const adminUrl=import.meta.env.BASE_URL==='/'?`${location.protocol}//${location.hostname}:5174/`:'../admin/';
 if(catalog.phase!=='ready'||!catalog.data)return <div className="access-auth"><div className="d-card auth-card"><img src={logo} alt="OneBite"/><span className="access-eyebrow">ONEBITE INVENTORY</span>
  {catalog.phase==='connecting'?<><h1>{t('កំពុងភ្ជាប់','Connecting…')}</h1><p>{t('កំពុងពិនិត្យគណនី និងស្តុក។','Checking your account and catalog.')}</p></>:catalog.phase==='mfa'?<MfaChallenge session={catalog.token} enrollment={catalog.enrollment} onVerified={reply=>void catalog.verified(reply)} onCancel={()=>void catalog.signOut()}/>:catalog.phase==='login'||catalog.phase==='change-pin'?<AuthForm key={catalog.phase} mode={catalog.phase} busy={catalog.busy} error={catalog.error?text(catalog.error):''} onSubmit={catalog.authenticate}/>:<><h1>{catalog.phase==='denied'?t('មិនអនុញ្ញាតឱ្យចូល','Access denied'):t('ត្រូវការការតភ្ជាប់','Connection needed')}</h1><p>{catalog.error?text(catalog.error):t('ភ្ជាប់អ៊ីនធឺណិត ហើយចូលគណនីដើម្បីទទួលទិន្នន័យពិត។','Connect and sign in to load your business data.')}</p><button className="d-btn d-btn-primary" disabled={catalog.busy} onClick={()=>void catalog.sync()}><RefreshCw size={18}/>{t('ព្យាយាមម្ដងទៀត','Retry')}</button><button className="d-btn d-btn-ghost" onClick={()=>void catalog.signOut()}>{t('ចាកចេញ','Sign out')}</button></>}
  <button className="access-text" onClick={()=>setLang(lang==='km'?'en':'km')}>{lang==='km'?'English':'ខ្មែរ'}</button>
 </div></div>;
 const {actor,canEdit,photos={},profilePhoto}=catalog.data;
 const references=projectReferences(catalog.data.references||[],catalog.referencePending);
 const pendingCount=catalog.pending.length+catalog.referencePending.length;
 const all=projectCatalog(catalog.data.items,catalog.pending),isDirectory=tab==='material'||tab==='finished'||tab==='sellable';
 const items=all.filter(item=>tab==='material'?['raw_material','supplies'].includes(itemDefinition(item).type):true),categories=[...new Set(items.map(item=>item.category))].sort((a,b)=>a.localeCompare(b));
 const displayed=items.filter(item=>(status==='all'||item.active===(status==='active'))&&(category==='all'||item.category===category)&&`${item.name} ${item.nameEn} ${item.category}`.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())).sort((a,b)=>new Intl.Collator(lang==='km'?'km':'en').compare(displayName(a),displayName(b)));
 function displayName(item:CatalogItem){return lang==='en'&&item.nameEn?item.nameEn:item.name;}
 function photo(item:CatalogItem){const operation=catalog.pending.find(op=>op.item.id===item.id);return operation?.image===null?undefined:operation?.image||photos[item.photoPath||''];}
 function typeName(type:string){return type==='finished_good'?t('ផលិតផលសម្រេច','Finished good'):type==='raw_material'?t('វត្ថុធាតុដើម','Raw material'):type==='supplies'?t('សម្ភារៈ','Supplies'):t('សមាសធាតុ','Component');}
 function categoryName(value:string,kind:string=tab){const reference=references.find(reference=>reference.kind==='sellable_category'&&reference.value===value);if(reference)return referenceLabel(reference,t);return value==='ingredient'?t('គ្រឿងផ្សំ','Ingredient'):value==='packaging'?t('សម្ភារៈវេចខ្ចប់','Packaging'):value;}
 const title=tab==='material'?t('សម្ភារៈ','Materials'):tab==='finished'?t('ផលិតផលសម្រេច','Finished products'):tab==='sellable'?t('មុខទំនិញ','Items'):tab==='sync'?t('ការផ្លាស់ប្ដូរ','Changes'):tab==='profile'?t('ប្រវត្តិរូបរបស់ខ្ញុំ','My profile'):t('មជ្ឈមណ្ឌល','Hub');
 const subtitle=tab==='material'?t('គ្រឿងផ្សំ និងសម្ភារៈវេចខ្ចប់សម្រាប់គ្រប់សាខា។','Ingredients and packaging shared across all sites.'):tab==='finished'?t('រូបមន្តសម្រាប់ផលិតផលសម្រេចមួយឯកតា។','Reusable recipes for one unit of a finished product.'):tab==='sellable'?t('បញ្ជីរួម៖ វត្ថុធាតុដើម សម្ភារៈ សមាសធាតុ និងផលិតផលសម្រេច។','One catalog for raw materials, supplies, components and finished goods.'):tab==='sync'?t('ការផ្លាស់ប្ដូរដែលបានរក្សាទុកក្នុងឧបករណ៍នេះ។','Changes saved on this device, waiting to publish.'):tab==='profile'?t('គណនី សិទ្ធិ និងចំណូលចិត្តរបស់អ្នក។','Your account, access, and preferences.'):t('អ្វីៗសម្រាប់គ្រប់គ្រងស្តុក។','Your Inventory workspace.');
 return <div className="access-app inventory-app"><aside className="access-sidebar"><div className="access-brand"><img src={logo} alt="OneBite"/></div><p className="access-nav-label">{t('គ្រប់គ្រងស្តុក','INVENTORY')}</p><nav>{navigation.map(link=><button key={link.id} className={tab===link.id?'active':''} onClick={()=>navigate(link.id)}><link.icon size={20}/>{link.label}{link.id==='sync'&&pendingCount>0&&<span aria-hidden="true" className="d-badge d-badge-primary">{pendingCount}</span>}</button>)}</nav><div className="access-sidebar-foot"><small>{t('កំណែកម្មវិធី','App version')} {version}</small></div></aside>
 <div className="access-workspace"><AppTitleBar message={<InventoryMessages toast={toast} onDismiss={()=>setToast('')} offline={catalog.offline} error={catalog.error?text(catalog.error):''}/>} icon={icon} title="OneBite - Inventory" name={actor.name} username={actor.username} photo={profilePhoto} syncStatus={catalog.syncStatus} pendingCount={pendingCount} connection={!catalog.network?'offline':catalog.offline?'unreachable':'online'} syncTask={pendingCount?'save':'refresh'} lastSyncedAt={catalog.verifiedAt||undefined} disabled={catalog.busy} dark={dark} offlineWrites onSync={()=>void catalog.sync()} onProfile={()=>navigate('profile')} onHub={()=>navigate('hub')} onLanguage={()=>setLang(lang==='km'?'en':'km')} onTheme={toggleTheme} onSignOut={()=>void catalog.signOut()}/>
 <main className="access-main"><PageHeading title={title} subtitle={subtitle} action={isDirectory&&canEdit?<NewAction label={t('មុខទំនិញថ្មី','New item')} onClick={()=>setEditing(newUnifiedItem())}/>:undefined}/>

 {isDirectory&&<><DirectoryTools><DirectorySearch label={t('ស្វែងរកមុខទំនិញ','Search items')} placeholder={t('ស្វែងរកឈ្មោះ ឬប្រភេទ…','Search name or category…')} value={search} onChange={setSearch}/><DirectoryStatusFilter label={t('ស្ថានភាព','Status')} value={status} onChange={setStatus}/></DirectoryTools>
 <CategoryFilter className="inventory-category" label={t('ប្រភេទ','Category')} value={category} options={['all',...categories].map(value=>({value,label:value==='all'?t('គ្រប់ប្រភេទ','All categories'):categoryName(value)||t('មិនមានប្រភេទ','Uncategorised')}))} onChange={setCategory}/>

 {displayed.length?<div className="inventory-grid">{displayed.map(item=>{const operation=catalog.pending.find(op=>op.item.id===item.id);return <button key={item.id} type="button" className="d-card inventory-card" onClick={()=>setViewing(item)} aria-label={displayName(item)}>{photo(item)?<img className="inventory-card-photo" src={photo(item)} alt=""/>:<div className="inventory-card-art">{itemDefinition(item).type==='finished_good'?<ShoppingBag size={36}/>:itemDefinition(item).type==='component'?<Layers3 size={36}/>:itemDefinition(item).type==='supplies'?<Package size={36}/>:<Leaf size={36}/>}</div>}<div className="inventory-card-body"><span className="inventory-category-label">{categoryName(item.category)||t('មិនមានប្រភេទ','Uncategorised')}</span><h2>{displayName(item)}</h2><p>{itemDefinition(item).canSell?`${new Intl.NumberFormat(lang==='km'?'km-KH':'en').format(item.priceKhr||0)} KHR / ${item.unit}`:item.packQuantity?`${item.packName} · ${item.packQuantity.toLocaleString()} ${item.unit}`:item.unit}</p><div className="inventory-card-meta"><ActiveStatusBadge active={item.active}/>{Date.parse(itemDefinition(item).effectiveAt)>Date.now()&&<span className="d-badge d-badge-info d-badge-soft">{t('បានកំណត់ពេល','Scheduled')}</span>}<span className="d-badge d-badge-soft">{typeName(itemDefinition(item).type)}</span>{itemDefinition(item).canSell&&<span className="d-badge d-badge-success d-badge-soft">{t('អាចលក់','Sellable')}</span>}{operation&&<span className={`d-badge ${operation.error?'d-badge-error':'d-badge-warning'} d-badge-soft`}>{operation.error?t('ត្រូវពិនិត្យ','Needs review'):t('រង់ចាំសមកាលកម្ម','Pending sync')}</span>}</div></div></button>;})}</div>:<EmptyState icon={tab==='material'?<Boxes size={32}/>:<ShoppingBag size={32}/>} title={items.length?t('មិនមានលទ្ធផល','No matching items'):tab==='material'?t('សម្ភារៈដំបូងរបស់អ្នក','Your first material'):tab==='finished'?t('ផលិតផលសម្រេចដំបូងរបស់អ្នក','Your first finished product'):t('មុខទំនិញដំបូងរបស់អ្នក','Your first sellable item')} body={items.length?t('សាកល្បងស្វែងរក ឬជ្រើសតម្រងផ្សេង។','Try another search or filter.'):canEdit?t('បង្កើតបញ្ជីពិតសម្រាប់ OneBite។','Start building OneBite’s real catalog.'):t('ម្ចាស់នឹងបន្ថែមមុខទំនិញនៅទីនេះ។','An Owner will add the catalog here.')} action={canEdit&&!items.length?{label:tab==='material'?t('បន្ថែមសម្ភារៈ','Add a material'):tab==='finished'?t('បន្ថែមផលិតផលសម្រេច','Add a finished product'):t('បន្ថែមមុខទំនិញ','Add a sellable item'),onClick:()=>setEditing(newUnifiedItem())}:undefined} secondaryAction={items.length?{label:t('សម្អាតតម្រង','Reset filters'),onClick:()=>{setSearch('');setStatus('active');setCategory('all');}}:undefined}/>}</>}
 {tab==='sync'&&(pendingCount?<div className="inventory-changes">{catalog.referencePending.map(operation=><section key={operation.id} className="d-card inventory-change"><h2>{operation.reference.name}</h2><p>{operation.error?text(operation.error):t('រង់ចាំសមកាលកម្ម','Pending sync')}</p><span className="d-badge d-badge-soft">{operation.reference.kind==='unit'?t('ឯកតាមូលដ្ឋាន','Base UOM'):t('ប្រភេទ','Category')}</span><button className="d-btn d-btn-ghost" disabled={catalog.busy} onClick={()=>setDiscarding(operation.id)}>{t('បោះបង់ការផ្លាស់ប្ដូរ','Discard change')}</button></section>)}{catalog.pending.map(operation=><section key={operation.id} className="d-card inventory-change"><div className="inventory-change-top"><Clock3 size={24}/><div><h2>{displayName(operation.item)}</h2><small>{new Intl.DateTimeFormat(lang==='km'?'km-KH':'en',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Phnom_Penh'}).format(operation.createdAt)}</small></div><span className={`d-badge d-badge-soft ${operation.error?'d-badge-error':'d-badge-warning'}`}>{operation.error?t('ត្រូវពិនិត្យ','Needs review'):t('រង់ចាំ','Waiting')}</span></div><p>{operation.error?text(operation.error):t('បានរក្សាទុកក្នុង SQLite លើឧបករណ៍នេះ។','Saved in SQLite on this device.')}</p><div className="inventory-change-actions"><button className="d-btn d-btn-outline" onClick={()=>setViewing(operation.item)}>{t('ពិនិត្យច្បាប់ចម្លង','Review saved copy')}</button><button className="d-btn d-btn-ghost" disabled={catalog.busy} onClick={()=>setDiscarding(operation.id)}>{t('បោះបង់ការផ្លាស់ប្ដូរ','Discard change')}</button></div></section>)}</div>:<EmptyState icon={<Check size={32}/>} title={t('គ្មានការផ្លាស់ប្ដូររង់ចាំ','No pending changes')} body={t('ការផ្លាស់ប្ដូរដែលអ្នករក្សាទុកនឹងបង្ហាញនៅទីនេះ។','Changes you save will appear here until published.')}/>)}
 {tab==='hub'&&<div className="inventory-bento">{canEdit&&(['sellable_category','unit'] as ReferenceKind[]).map(kind=><button key={kind} className="d-card inventory-hub-card" onClick={()=>setReferenceManaging(kind)}><Package size={30}/><h2>{kind==='unit'?t('ឯកតាមូលដ្ឋាន','Base UOMs'):kind==='material_category'?t('ប្រភេទសម្ភារៈ','Material categories'):t('ប្រភេទមុខទំនិញ','Item categories')}</h2><p>{t('គ្រប់គ្រងជម្រើសសម្រាប់បញ្ជីមុខទំនិញ។','Manage catalog selection options.')}</p><ArrowUpRight size={20}/></button>)}{navigation.filter(link=>link.id!=='hub').map(link=><button className={`d-card inventory-hub-card ${link.id==='material'?'inventory-hub-featured':''}`} key={link.id} onClick={()=>navigate(link.id)}><link.icon size={30}/><h2>{link.label}</h2><p>{link.id==='material'?t('គ្រឿងផ្សំ និងវេចខ្ចប់','Ingredients and packaging'):link.id==='finished'?t('គ្រឿងផ្សំ និងរូបមន្ត','Ingredients and reusable recipes'):link.id==='sellable'?t('មុខទំនិញ និងតម្លៃមេ','Items and master prices'):link.id==='sync'?t('ការផ្លាស់ប្ដូរលើឧបករណ៍','Changes on this device'):t('គណនី និងសិទ្ធិ','Account and access')}</p><ArrowUpRight size={20}/></button>)}<a href={adminUrl} target="_blank" rel="noopener noreferrer" className="d-card inventory-hub-card"><ShieldCheck size={30}/><h2>{t('រដ្ឋបាល','Admin')}</h2><p>{t('អ្នកប្រើ តួនាទី និងសាខា','Users, roles and sites')}</p><ArrowUpRight size={20}/></a></div>}
 {tab==='profile'&&<InventoryProfile key={`${actor.id}:${catalog.token}`} account={actor} photo={profilePhoto} canEditCatalog={canEdit} dark={dark} live={!catalog.offline&&catalog.network} busy={catalog.busy} token={catalog.token} adminUrl={adminUrl} onLanguage={()=>setLang(lang==='km'?'en':'km')} onTheme={toggleTheme} onSignOut={()=>void catalog.signOut()} onRefresh={()=>catalog.sync()}/>}
 </main></div>
 <div className="access-bottom-nav-region"><nav className={`access-bottom-nav inventory-bottom-nav ${bottomHidden?"is-scroll-hidden":""}`} inert={bottomHidden} aria-hidden={bottomHidden} aria-label={t('ម៉ឺនុយស្តុក','Inventory navigation')}>{navigation.filter(link=>link.id!=='finished').map(link=><button key={link.id} className={tab===link.id?'active':''} aria-current={tab===link.id?'page':undefined} onClick={()=>navigate(link.id)}><link.icon size={21}/><span>{link.label}</span></button>)}</nav></div>
 {editing&&<CatalogEditor key={editing.id} item={editing} catalog={all} references={references} selectedReference={selectedReference} onCreateReference={kind=>setReferenceEditing(newCatalogReference(kind))} onManageReferences={setReferenceManaging} photo={photo(editing)} onClose={()=>{setEditing(null);setSelectedReference(undefined);}} onSave={async(item,image,confirmedActive)=>{await catalog.save(item,image,confirmedActive);setToast(t('បានរក្សាទុកក្នុងឧបករណ៍ · រង់ចាំសមកាលកម្ម។','Saved on this device · Queued for sync.'));setEditing(null);setSelectedReference(undefined);}}/>}
 {viewing&&<AppDialog title={displayName(viewing)} onClose={()=>setViewing(null)} footer={canEdit&&!catalog.pending.some(op=>op.item.id===viewing.id)?<button className="d-btn d-btn-primary" disabled={catalog.busy} onClick={()=>{setEditing(editUnifiedItem(viewing,all));setViewing(null);}}><Pencil size={18}/>{t('កែប្រែ','Edit')}</button>:undefined}><div className="inventory-detail">{photo(viewing)&&<img src={photo(viewing)} alt={displayName(viewing)}/>}<ActiveStatusBadge active={viewing.active}/><p>{t('កំណែចុងក្រោយសម្រាប់ការគ្រប់គ្រងបញ្ជី។','Latest catalog version.')} {Date.parse(itemDefinition(viewing).effectiveAt)>Date.now()?t('ការផ្លាស់ប្ដូរនេះមិនទាន់មានប្រសិទ្ធភាពទេ។','This change is scheduled and is not effective yet.'):''}</p><dl><div><dt>{t('ប្រភេទមុខទំនិញ','Item type')}</dt><dd>{typeName(itemDefinition(viewing).type)}</dd></div><div><dt>{t('អាចលក់','Can sell')}</dt><dd>{itemDefinition(viewing).canSell?t('បាទ','Yes'):t('ទេ','No')}</dd></div><div><dt>{t('ប្រភេទ','Category')}</dt><dd>{categoryName(viewing.category)||'—'}</dd></div><div><dt>{t('ឯកតា','Unit')}</dt><dd>{viewing.unit}</dd></div>{itemDefinition(viewing).canSell&&<div><dt>{t('តម្លៃមេ','Master price')}</dt><dd>{viewing.priceKhr?.toLocaleString()} KHR</dd></div>}{viewing.packQuantity!==null&&<div><dt>{t('កញ្ចប់','Pack')}</dt><dd>{viewing.packName} · {viewing.packQuantity.toLocaleString()} {viewing.unit}</dd></div>}<div><dt>{t('បរិមាណផលិតក្នុងមួយលើក','Batch output')}</dt><dd>{itemDefinition(viewing).batchYield} {viewing.unit}</dd></div></dl>{(['ingredients','contents','packaging'] as const).map(section=><section key={section}><h3>{section==='ingredients'?t('គ្រឿងផ្សំ','Ingredients'):section==='contents'?t('មុខទំនិញក្នុងប្រអប់','Items in the box'):t('សម្ភារៈវេចខ្ចប់','Packaging used')}</h3><dl>{itemDefinition(viewing).lines.filter(line=>line.section===section).map(line=>{const child=all.find(value=>value.id===line.itemId);return <div key={line.itemId}><dt>{child?displayName(child):'—'}</dt><dd>{line.quantity} {line.unit||child?.unit}</dd></div>;})}</dl></section>)}<UnifiedRecipeSummary item={viewing} catalog={all}/>{viewing.description&&<p>{viewing.description}</p>}
 {catalog.data.versions?.filter(version=>version.item.id===viewing.id).length? <section><h3>{t('ប្រវត្តិរូបមន្ត','Version history')}</h3><p>{t('ម៉ោងកម្ពុជា · សម្រាប់ការបញ្ជាទិញថ្មី','Cambodia time · New orders only')}</p><dl>{catalog.data.versions.filter(version=>version.item.id===viewing.id).sort((a,b)=>b.item.revision-a.item.revision).map(version=><div key={version.item.revision}><dt>{t('កំណែ','Version')} {version.item.revision}</dt><dd>{new Intl.DateTimeFormat(lang==='km'?'km-KH':'en',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Phnom_Penh'}).format(new Date(version.effectiveAt))}</dd></div>)}</dl></section>:null}
 {catalog.pending.some(op=>op.item.id===viewing.id)&&<p className="d-alert d-alert-warning d-alert-soft"><AlertTriangle size={18}/>{t('កំពុងរង់ចាំសមកាលកម្ម។','Pending sync. Review it on the Changes page.')}</p>}</div></AppDialog>}
 {referenceManaging&&<ReferenceManager kind={referenceManaging} references={references} pending={catalog.referencePending} onClose={()=>setReferenceManaging(null)} onEdit={setReferenceEditing}/>}
 {referenceEditing&&<ReferenceEditor key={referenceEditing.id} reference={referenceEditing} references={references} onClose={()=>setReferenceEditing(null)} onSave={async(reference,confirmed)=>{await catalog.saveReference(reference,confirmed);setToast(t('បានរក្សាទុកក្នុងឧបករណ៍ · រង់ចាំសមកាលកម្ម។','Saved on this device · Queued for sync.'));if(reference.revision===0&&editing)setSelectedReference(reference);setReferenceEditing(null);}}/>}
 {discarding&&<AppDialog title={t('បោះបង់ការផ្លាស់ប្ដូរ?','Discard this change?')} onClose={()=>{if(!discardBusy)setDiscarding(null);}} footer={<button className="d-btn d-btn-error" disabled={discardBusy} onClick={async()=>{setDiscardBusy(true);try{if(catalog.referencePending.some(operation=>operation.id===discarding))await catalog.discardReference(discarding);else await catalog.discard(discarding);setDiscarding(null);}finally{setDiscardBusy(false);}}}>{t('បោះបង់ការផ្លាស់ប្ដូរ','Discard change')}</button>}><p>{t('លុបច្បាប់ចម្លងដែលមិនទាន់បានធ្វើសមកាលកម្មពីឧបករណ៍នេះ។ ព័ត៌មានលើ Supabase នឹងបង្ហាញឡើងវិញ។','Remove this device’s pending copy. The latest Supabase item will be shown again. A change already accepted by the server is retained.')}</p></AppDialog>}
 </div>;
}
