import {Plus,Trash2,Layers3} from 'lucide-react';
import {SelectField,useLanguage} from '@onebite/ui';
import {itemDefinition,recipeSections,recipeMaterials,cambodiaDateTime,fromCambodiaDateTime,type CatalogItem,type ItemDefinition,type RecipeSection} from '@onebite/core/inventory';
export function UnifiedRecipeEditor({item,catalog,disabled,onChange}:{item:CatalogItem;catalog:CatalogItem[];disabled:boolean;onChange:(definition:ItemDefinition)=>void}){
 const {t,lang}=useLanguage(),d=itemDefinition(item);
 const name=(value:CatalogItem)=>lang==='en'&&value.nameEn?value.nameEn:value.name;
 const update=(value:Partial<ItemDefinition>)=>onChange({...d,...value});
 const labels:Record<RecipeSection,string>={ingredients:t('គ្រឿងផ្សំ','Ingredients'),contents:t('មុខទំនិញក្នុងប្រអប់','Items in the box'),packaging:t('សម្ភារៈវេចខ្ចប់','Packaging used')};
 const available=catalog.filter(value=>value.id!==item.id&&value.active).sort((a,b)=>name(a).localeCompare(name(b)));
 return <>
 <label>{t('អនុវត្តចាប់ពី (ម៉ោងកម្ពុជា)','Effective from (Cambodia time)')}<input className="d-input" type="datetime-local" aria-label={t('អនុវត្តចាប់ពី (ម៉ោងកម្ពុជា)','Effective from (Cambodia time)')} required disabled={disabled} value={cambodiaDateTime(d.effectiveAt)} onChange={e=>{if(e.target.value)update({effectiveAt:fromCambodiaDateTime(e.target.value)});}}/><small>{t('ប្រើសម្រាប់ការបញ្ជាទិញថ្មីប៉ុណ្ណោះ។','Applies to new orders only. Existing orders keep their original recipe.')}</small></label>
 {(d.type==='finished_good'||d.type==='component')&&<>
 <label>{t('បរិមាណផលិតក្នុងមួយលើក','Recipe batch output')} ({item.unit})<input className="d-input" aria-label="Recipe batch output" type="number" min={.000001} max={1e9} step="any" required value={d.batchYield} disabled={disabled} onChange={e=>update({batchYield:Number(e.target.value)})}/><small>{t('គ្រឿងផ្សំខាងក្រោមសម្រាប់បរិមាណនេះ។','Enter all quantities below for this batch. The app calculates usage per unit.')}</small></label>
 {recipeSections.map(section=>{const lines=d.lines.filter(line=>line.section===section),next=available.find(value=>!lines.some(line=>line.itemId===value.id));return <section className="inventory-recipe" key={section}><div className="inventory-recipe-heading"><Layers3 size={20}/><h3>{labels[section]}</h3></div>
 {lines.map((line,index)=>{const actual=d.lines.indexOf(line),child=catalog.find(value=>value.id===line.itemId);const setLine=(value:Partial<typeof line>)=>update({lines:d.lines.map((old,i)=>i===actual?{...old,...value}:old)});return <div className="inventory-recipe-line" key={line.itemId}>
 <label>{t('មុខទំនិញ','Item')}<SelectField presentation="dropdown" aria-label={`${labels[section]} item ${index+1}`} disabled={disabled} value={line.itemId} onChange={e=>{const selected=catalog.find(value=>value.id===e.target.value);if(selected)setLine({itemId:selected.id,unit:selected.unit,quantity:1});}}>{!available.some(value=>value.id===line.itemId)&&<option value={line.itemId}>{child?name(child):t('មិនមាន','Unavailable')}</option>}{available.filter(value=>value.id===line.itemId||!lines.some(other=>other.itemId===value.id)).map(value=><option key={value.id} value={value.id}>{name(value)}</option>)}</SelectField></label>
 <label>{t('បរិមាណ','Quantity')}<input className="d-input" aria-label={`${labels[section]} quantity ${index+1}`} type="number" inputMode="decimal" min={.000001} max={1e9} step="any" required disabled={disabled} value={line.quantity||''} onChange={e=>setLine({quantity:Number(e.target.value)})}/><SelectField aria-label={`${labels[section]} unit ${index+1}`} disabled={disabled} value={line.unit} onChange={e=>setLine({unit:e.target.value})}>{[...new Set([line.unit,child?.unit,...itemDefinition(child||item).conversions.map(c=>c.unit),...(child?.unit==='g'?['kg']:child?.unit==='ml'?['L']:[])])].filter(Boolean).map(unit=><option key={unit} value={unit}>{unit}</option>)}</SelectField></label>
 <button type="button" className="d-btn d-btn-ghost" aria-label={`Remove ${labels[section]} item ${index+1}`} disabled={disabled} onClick={()=>update({lines:d.lines.filter((_,i)=>i!==actual)})}><Trash2 size={18}/></button></div>;})}
 {!lines.length&&<p className="inventory-recipe-hint">{t('មិនទាន់មានមុខទំនិញ។','No items added yet.')}</p>}
 <button type="button" className="d-btn d-btn-outline" disabled={disabled||!next||d.lines.length>=100} onClick={()=>{if(next)update({lines:[...d.lines,{itemId:next.id,quantity:1,unit:next.unit,section}]});}}><Plus size={18}/>{t('បន្ថែម','Add')} · {labels[section]}</button>
 </section>;})}<UnifiedRecipeSummary item={item} catalog={catalog}/>
 </>}
 <section className="inventory-recipe"><h3>{t('ការបម្លែងឯកតា','Item unit conversions')}</h3><p className="inventory-recipe-hint">{t(`កំណត់បរិមាណឯកតាផ្សេងជា ${item.unit}។ kg/g និង L/ml បម្លែងស្វ័យប្រវត្តិ។`,`Set how many ${item.unit} equal one other unit. kg/g and L/ml convert automatically.`)}</p>
 {d.conversions.map((conversion,index)=><div className="inventory-recipe-line" key={index}><label>{t('ឯកតាផ្សេង','Other unit')}<input className="d-input" aria-label={`Conversion unit ${index+1}`} maxLength={30} required disabled={disabled} value={conversion.unit} onChange={e=>update({conversions:d.conversions.map((c,i)=>i===index?{...c,unit:e.target.value}:c)})}/></label><label>1 {conversion.unit||'…'} = ({item.unit})<input className="d-input" aria-label={`Conversion factor ${index+1}`} type="number" step="any" min={.000001} max={1e9} required disabled={disabled} value={conversion.factor} onChange={e=>update({conversions:d.conversions.map((c,i)=>i===index?{...c,factor:Number(e.target.value)}:c)})}/></label><button className="d-btn d-btn-ghost" type="button" aria-label={`Remove conversion ${index+1}`} disabled={disabled} onClick={()=>update({conversions:d.conversions.filter((_,i)=>i!==index)})}><Trash2 size={18}/></button></div>)}
 <button className="d-btn d-btn-outline" type="button" disabled={disabled||d.conversions.length>=30} onClick={()=>update({conversions:[...d.conversions,{unit:'',factor:1}]})}><Plus size={18}/>{t('បន្ថែមការបម្លែង','Add conversion')}</button></section>
 </>;
}
export function UnifiedRecipeSummary({item,catalog}:{item:CatalogItem;catalog:CatalogItem[]}){
 const {t,lang}=useLanguage();let lines;try{lines=recipeMaterials(item,catalog);}catch{return <p className="inventory-recipe-hint">{t('ពិនិត្យរូបមន្ត និងការបម្លែងឯកតា។','Complete the recipe and unit conversions to see the breakdown.')}</p>;}
 if(!itemDefinition(item).lines.length)return null;
 return <div className="inventory-recipe-summary"><h3>{t('សម្ភារៈសរុប','Raw-material breakdown')}</h3><p>{t(`សម្រាប់ 1 ${item.unit}។`,`For 1 ${item.unit}.`)}</p><dl>{lines.map(line=>{const child=catalog.find(value=>value.id===line.itemId);return <div key={line.itemId}><dt>{child?(lang==='en'&&child.nameEn?child.nameEn:child.name):'—'}</dt><dd>{line.quantity.toLocaleString(undefined,{maximumFractionDigits:6})} {child?.unit}</dd></div>;})}</dl></div>;
}
